### ISSUE TITLE
How might I get twin.macro styles inline in dom markup?

### ISSUE THREAD

**Issue by rluiten** [ben-rogerson/twin.macro#10]
Thanks for this project.
I was pleasantly surprised to find this project to get tailwindcss into css in js space (after finding tailwind.macro and reading a lot of other stuff to get to twin.macro).

I have several years of React development experience but very little with css in js.
I was trying this out to get a feel for emotion css in js and nextjs.
I mocked up the small notification example from the tailwindcss documentation here https://tailwindcss.com/docs/utility-first as per this screen shot from that documentation.

![image](https://user-images.githubusercontent.com/670472/75626235-9f000700-5c11-11ea-82d5-a129d6029a17.png)

The below works fine but I think there are benefits if I could get the styling definition inline with the markup without creating those intermediate styled components.

Possibly there are other ways to approach this problem without getting the inline behaviour I am asking about. If so I happy to hear about alternatives.
(Updated the example code with better named helpers).

```javascript
const NotifyOuter = tw.div`max-w-sm mx-auto flex p-6 bg-white rounded-lg shadow-xl`
const LeftLogo = tw.div`flex-shrink-0`
const Logo = tw.img`h-12 w-12`
const RightCaption = tw.div`ml-6 pt-1`
const CaptionHeading = tw.h1`text-xl text-gray-900 leading-tight` // a11y dont use H4 here confusing.
const CaptionBody = tw.p`text-base text-gray-600 leading-normal`

const NotificationExample = () => (
  <NotifyOuter>
    <LeftLogo>
      <Logo src="/chit-chat-logo.svg" alt="ChitChat Logo" />
    </LeftLogo>
    <RightCaption>
      <CaptionHeading>ChitChat</CaptionHeading>
      <CaptionBody>You have a new message! You have a new message! You have a new message! You have a new message!</CaptionBody>
    </RightCaption>
  </NotifyOuter>
)
```

**Comment by ben-rogerson** [comment]
No worries, here's a sandbox that shows how you could approach this:
https://codesandbox.io/s/cra-tailwind-emotion-starter-mjzn9

**Comment by rluiten** [comment]
I was aware I could use style (which I didn't make clear in my post), doing that I lose benefits of using emotion for styling, like I cant use css features like `:hover` etc.

**Comment by ben-rogerson** [comment]
True, style is only good for simple styling.
Have you tried the [css prop](https://emotion.sh/docs/@emotion/babel-preset-css-prop#usage)? It's available in a babel preset or as a jsx pragma.

**Comment by rluiten** [comment]
I tried the `css` from `@emotion/core`.
Notice the `name` reference to get the class name out.

```javascript
const fooStyle = css(
  tw`max-w-sm mx-auto flex p-6 bg-white rounded-lg shadow-xl`
)

const NotificationExample2 = () => (
  <div className={fooStyle.name}>NotificationExample2</div>
)
```

This doesn't work because the className that is generated does not have its style added, doing it this way does not register it as in use at a guess.

You mention jsx which I remember reading about but not trying.

I added at the top of the file.
```javascript
/** @jsx jsx */
import { css, jsx } from '@emotion/core'
```

Then created component this way
```javascript
const NotificationExample3 = () => (
  <div
    css={tw`max-w-sm mx-auto flex p-6 bg-white rounded-lg shadow-xl`}
  >
    NotificationExample3
  </div>
)
```

This works and is where I was trying to get to.
Thank's for you illumination.
