### ISSUE TITLE
first-of-type variant?

### ISSUE THREAD

**Issue by phil-scott-78** [ben-rogerson/twin.macro#101]
I was looking to use `:first-of-type` (and likewise `:last-of-type`, `:nth-last-of-type`, `:not(:nth-last-of-type`, etc) but I didn't see them in the default variant list nor a way to add the programatically. Just getting kinda sick of seeing this message pop up thanks to #emotion-js/emotion#1105.

Any chance they could be added in a future release? Of course I'm happy to submit a PR (assuming if it's just a matter of editing `variantConfig.js` )

**Comment by rbutera** [comment]
I'm happy to review the PR if you submit it.

**Comment by phil-scott-78** [comment]
Thanks for the quick reply. Think I got things in order with #102

**Comment by ben-rogerson** [comment]
Thanks for your contribution phil - it's now live in [v1.5.0](https://github.com/ben-rogerson/twin.macro/releases/tag/1.5.0)
