### ISSUE TITLE
@tailwindcss/typography doesn't work with Twin

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#108]
![image](https://user-images.githubusercontent.com/21288568/87361521-8f270500-c5ab-11ea-8a26-fea8751dba6d.png)

Currently, the [official typography plugin](https://github.com/tailwindcss/typography) is unsupported in Twin.
~~Support is possible but maybe I'll see how popular the plugin becomes before tackling it~~.
I'm working on a patch.

[↓ See Tim's post below for some temporary workarounds](https://github.com/ben-rogerson/twin.macro/issues/108#issuecomment-661514193)

**Comment by lednhatkhanh** [comment]
I's really hope that this will be supported!

**Comment by timfee** [comment]
This might be obvious, but for a workaround in the meantime, two workarounds:

1. Add `@tailwindcss/typography` to your project, then `import '@tailwindcss/typography/dist/typography.min.css'` to enable adding `className='prose'` to a prose container.

2. Add (the CSS CDN)[https://github.com/tailwindcss/typography#using-a-cdn] to your `<head>` to also allow a container to contain `className=prose`. 

You don't get any of the customizations, but if you’re looking to kick the tires and use out-of-the-box defaults, it's not a terrible way to play around :)

**Comment by ben-rogerson** [comment]
Thanks for sharing those great workarounds Tim.

I was planning on releasing support for the plugin within the next release (1.6.0) but there are still few bugs to iron out before then. So most likely it'll be added to the release afterwards, around the 29th of July.

**Comment by ben-rogerson** [comment]
There are some other plugin issues that appear when using the latest tailwindcss with twin so I'm aiming to fast track this issue.

**Comment by ben-rogerson** [comment]
I've now added support for [@tailwindcss/typography](https://github.com/tailwindlabs/tailwindcss-typography) in [twin.macro@1.6.2](https://github.com/ben-rogerson/twin.macro/releases/tag/1.6.2) 🎉 

I also made a [demo of the prose classes in twin.macro@1.6.2](https://codesandbox.io/embed/twinmacro162-tailwindcss-typography020-plugin-demo-dj9ot?fontsize=14&hidenavigation=1&theme=dark).
Resize the window to see how the sizes change.

**Comment by ben-rogerson** [comment]
Closing this issue for now but feel free to reopen if something surfaces

**Comment by pedrohasf** [comment]
Hey everyone, it appears the color modifiers from @tailwindcss/typography are not working. I am trying to use something like "prose-indigo" and in the latest version of twin.macro (2.0.7) the error message that appears is "twin.macro: [object Object] is not a PostCSS plugin Learn more: https://www.npmjs.com/package/twin.macro"

**Comment by ben-rogerson** [comment]
> Hey everyone, it appears the color modifiers from @tailwindcss/typography are not working. I am trying to use something like "prose-indigo" and in the latest version of twin.macro (2.0.7) the error message that appears is "twin.macro: [object Object] is not a PostCSS plugin Learn more: https://www.npmjs.com/package/twin.macro"

That error displays when there's no postcss installed, check out [this issue](https://github.com/ben-rogerson/twin.macro/issues/259).

**Comment by pedrohasf** [comment]
I was able to solve that PostCSS problem but then another error showed up 
```
✕ prose-red was not found

Try one of these classes:
table-row / space-x-reverse / space-y-reverse
divide-x-reverse / divide-y-reverse / flex-row-reverse
```

This same error also occurs on the code sandbox that was posted on this issue.

**Comment by ben-rogerson** [comment]
@pedrohasf Thanks for the report, I've now created an issue to provide support on this #108
