### ISSUE TITLE
FOUC in Next + Styled Components + Tailwind Twin Starter

### ISSUE THREAD

**Issue by arangates** [ben-rogerson/twin.macro#111]
it can be seen here https://codesandbox.io/embed/next-tailwind-styled-components-starter-m1f6d?module=%2Fpages%2Findex.js . Apparently it doesnt happen in emotion

**Comment by ben-rogerson** [comment]
Ah yes I see it.
I haven't noticed that before but it's not a problem with Twin though - that's in styled-components territory.
Perhaps there's some config I can update to fix it in the demo though.

Issues:
https://github.com/styled-components/styled-components/issues/2322
https://github.com/styled-components/styled-components/issues/1472

**Comment by ben-rogerson** [comment]
Fixed it - my demo was missing the server stylesheet.

https://codesandbox.io/embed/next-styled-components-tailwind-twin-starter-m1f6d?fontsize=14&hidenavigation=1&module=%2Fpages%2F_document.js&theme=dark

**Comment by arangates** [comment]
Hey @ben-rogerson Thanks for the amazing work🤩 works perfect!!! 🦾
