### ISSUE TITLE
Some plugin classes not found when using tailwindcss >= v1.5.0

### ISSUE THREAD

**Issue by JohJonker** [ben-rogerson/twin.macro#112]
After upgrading from `twin.macro` 1.4.1 ➞ 1.5.1 and `tailwindcss` 1.4.6 ➞ 1.5.2, I'm getting errors for my custom utilities defined in tailwind.config.js:

<img width="210" alt="Screenshot 2020-07-21 at 22 30 55" src="https://user-images.githubusercontent.com/4933686/88103855-dad84080-cba1-11ea-9fb1-34f00e09f0f7.png">

`@tailwindcss/custom-forms` doesn't seem to be working anymore, either:

<img width="204" alt="Screenshot 2020-07-21 at 22 32 36" src="https://user-images.githubusercontent.com/4933686/88104039-2854ad80-cba2-11ea-859f-5c9ad41c221e.png">

Here is my tailwind.config.js:

```js
const plugin = require('tailwindcss/plugin');

module.exports = {
  theme: {
    extend: {
      ...
    },
  },
  plugins: [
    require('@tailwindcss/custom-forms'),
    plugin(({ addUtilities }) => {
      const textShadowUtils = {
        '.text-shadow': {
          textShadow: '0 0 2px rgba(0,0,0,0.5)',
        },
        '.text-shadow-lg': {
          textShadow: '0 0 10px rgba(0,0,0,0.5)',
        },
        '.text-shadow-none': {
          textShadow: 'none',
        },
      };
      addUtilities(textShadowUtils, ['responsive', 'hover']);
    }),
  ],
};
```

Has the way to add utilities changed? Or am I missing something major?

**Comment by ben-rogerson** [comment]
Howdy Joh,

There is is a breaking change in tailwindcss@1.5.0 affecting plugins: https://github.com/tailwindcss/tailwindcss/releases/tag/v1.5.0

Downgrade tailwindcss to fix:
```bash
npm i tailwindcss@1.4.6
```

This incompatibility will be fixed when we start supporting the typography plugin #108

**Comment by JohJonker** [comment]
Hi Ben,

That fixed it. I'll follow the progress on #108. 👍

As always, thanks for your excellent help!
