### ISSUE TITLE
Nesting groups in tailwind/twin?

### ISSUE THREAD

**Issue by tettoffensive** [ben-rogerson/twin.macro#116]
I was reading your [doc on groups in twin](https://github.com/ben-rogerson/twin.macro/blob/cb52e3fc1b9ce6700234e5a307f9b323f6e2f33b/docs/group.md) and I'm not sure if this is a limitation of tailwind or specific to twin.

I have a `<div className="group">` which on hover shows a nested `<button>` when the user hovers on that button I want to show a tooltip. I could do this with javascript,  but I'd like to have the `<button className="group">` and that would override the parent group so the `group-hover:visible` only happens when the user hovers over this nested button.

**Comment by ben-rogerson** [comment]
The group stuff has a limitation of a single group, you can't go nesting them because of the way the css is written.

But you can always drop back into css to add a hover that's more specific.
Here are two examples using css.

![hover](https://user-images.githubusercontent.com/21288568/88858188-cac20000-d236-11ea-83e6-88483075ea3e.gif)

```js
const tooltipStyles = [
  tw`absolute bg-red-500 hidden`,
  css`
    ${Button}:hover & {
      ${tw`block`}
    }
  `
]

const PropExample = () => (
  <div className="group" tw="bg-gray-500 p-20">
    <button tw="invisible group-hover:visible">
      <div>Hover button</div>
      <div css={tooltipStyles}>Tooltip</div>
    </button>
  </div>
)
```

You can see that using Styled Components has an edge here because you can include the styled-component in the css selector:

```js
const Group = tw.div`bg-gray-500 p-20`
const Button = tw.button`invisible group-hover:visible`
const Tooltip = tw.div`invisible group-hover:visible`

const tooltipStyles = [
  tw`absolute bg-red-500 hidden`,
  css`
    ${Button}:hover & {
      ${tw`block`}
    }
  `
]

const StyledComponentsExample = () => (
  <Group className="group">
    <Button tw="invisible group-hover:visible">
      <div>Hover</div>
      <Tooltip css={tooltipStyles}>Tooltip</Tooltip>
    </Button>
  </Group>
)
```

**Comment by ben-rogerson** [comment]
Closing this one up, feel free to ask a question if you're unsure of the group usage still.

**Comment by ben-rogerson** [comment]
You've found a hole in the types there.
Try this:

```js
// twin.d.ts
import 'twin.macro'
import styledImport from '@emotion/styled'
import { css as cssImport } from '@emotion/core'

// Allow interpolation: css`${MyStyledComponent}:hover & { //... }`
type Interpolation = ObjectInterpolation<undefined>

declare module 'twin.macro' {
  // The styled and css imports
  const styled: typeof styledImport | Interpolation
  const css: typeof cssImport | Interpolation
}
```
