### ISSUE TITLE
How do I use plugins to set default list style?

### ISSUE THREAD

**Issue by tettoffensive** [ben-rogerson/twin.macro#120]
I'm using a third-party component which renders `<ul><li>Stuff in here</li></ul>` with no classes or id associated. I wanted to set the default list style that tailwind erases in base style to disc.

I tried doing this:

```ts
plugins: [({ addUtilities }) => addUtilities({ 'ul > li': { listStyleType: 'disc' } })],
```

But I must be misunderstanding how to use these methods because this and everything I've tried have not worked.

Am I on the right track or way off? What am I missing? (using 1.7.0)

**Comment by ben-rogerson** [comment]
Try something like this:

```js
module.exports = {
  // theme: {},
  plugins: [discChildren],
}

function discChildren({ addComponents }) {
  addComponents({
    '.my-class': {
      'ul > li': {
        listStyleType: 'disc',
      },
    },
  })
}
```

You'd add the class (`tw="my-class"`) either on the component or a parent of the component.

**Comment by tettoffensive** [comment]
@ben-rogerson This worked, but something funny is happening. I tried to add:

```js
'ol > li': {
  listStyleType: 'decimal',
}
```

However, it wasn't showing up. Inspecting the CSS in the browser for some reason it's not there. It feels like a caching issue, but with very peculiar behavior because if I change the 'ul' to be decimal it still shows up as disc.

I'm restarting my server and I've also tried clearing the browser cache. But I haven't been able to get the 'ol' rule to show up.

**Comment by ben-rogerson** [comment]
There's some Gatsby sized caching happening by the sounds, [try making a change in the code to force a recompile](https://github.com/kentcdodds/babel-plugin-macros#babel-cache-problem) if that doesn't work, delete your .cache and restart the server. #11

**Comment by tettoffensive** [comment]
Turns out to be an import issue. I had never used the syntax `tw="my-class"` before. Always did ```css={tw`my-class`}``` (because I didn't know about the former).

In either case, I must `import tw from 'twin.macro';` for the classes to be applied. I didn't notice because there's no complaint of missing import when using `tw=`

But when using `tw=` and `import tw from 'twin.macro';` TypeScript does complain that `'tw' is declared but its value is never read.ts(6133)`.

_(Hope that wasn't too confusing)_

**Comment by fvanwijk** [comment]
You can do `import 'twin.macro` if you are using `tw` as prop instead of template function

**Comment by ben-rogerson** [comment]
I recommend having a quick read through the [examples in the readme](https://github.com/ben-rogerson/twin.macro/blob/master/README.md). I'm also working on some guides for the [css prop](https://github.com/ben-rogerson/twin.macro/blob/d25b984a6f713ed96173e29cd49992fd4d783e78/docs/css-prop-guide.md) and the [styled import](https://github.com/ben-rogerson/twin.macro/blob/d25b984a6f713ed96173e29cd49992fd4d783e78/docs/styled-import-guide.md).
