### ISSUE TITLE
react-native support?

### ISSUE THREAD

**Issue by babsonmatt** [ben-rogerson/twin.macro#121]
Any consideration for supporting react-native as well?

**Comment by ben-rogerson** [comment]
I haven't tried it in that environment yet, what's the status?

**Comment by carl0s** [comment]
Is there any update on this? Would be interesting to know in advance if it's supported

**Comment by ben-rogerson** [comment]
It's a big step to stay on top of React Native support and I'm spread thin enough as it is.
So I'm going to label React Native as 'Unsupported' - sorry!

**Comment by carl0s** [comment]
too bad :( alright.
Do you have any recommended alternative to your library?

**Comment by ben-rogerson** [comment]
Give [tailwind-rn](https://github.com/vadimdemedes/tailwind-rn) a look, I haven't used it but I'm a fan of Vadim's work.

**Comment by ekiwi111** [comment]
For anyone coming from google, searching for twin macro for react native - [twrnc](https://github.com/jaredh159/tailwind-react-native-classnames)
