### ISSUE TITLE
Add intellisense 

### ISSUE THREAD

**Issue by Eriickson** [ben-rogerson/twin.macro#122]
When I'm using your plugin it's a bit tedious to write tailwindcss classes, since I don't have any kind of help or autocompletion, is there any way to solve this problem, some kind of intellisense, and if it doesn't exist, when will you be adding it?

![image](https://user-images.githubusercontent.com/38663299/89709328-d5724880-d94c-11ea-8332-8a9eced74e2b.png)

**Comment by ben-rogerson** [comment]
This is on the same line as #64 

You can install this vscode plugin but it's not perfect. It doesn't cover all the unique features of twin:
![image](https://user-images.githubusercontent.com/21288568/89710069-199e3100-d9bf-11ea-95f2-bc49f4f069fb.png)

**Comment by ben-rogerson** [comment]
See #64 🎉

**Comment by IniZio** [comment]
Seems the link is now moved to https://github.com/ben-rogerson/twin.macro/discussions/227
