### ISSUE TITLE
Using the style attribute doesn't apply all styles

### ISSUE THREAD

**Issue by garrrettt** [ben-rogerson/twin.macro#123]
I was pretty confused for a while about why variants such as `focus:` only work in certain places. Specifically, I was trying to use ``style={tw`focus:some-property`}`` and it refused to work until I changed my approach and used ``tw.button`focus:some-property` ``. I didn't find this info in the docs, so I was hoping you could add it to the README or something. I only realized after reading Issue #80

**Comment by ben-rogerson** [comment]
Ah damn! I hoped the examples at the top of the readme would help demonstrate how twin can be used.
Apart from stating twin doesn't work with the style prop, what do you think is missing that would have helped you?

There are a decent number of demos linking off the readme to demonstrate the variant usage [on the logo](https://codesandbox.io/s/react-tailwind-emotion-starter-3d1dl?file=/src/components/Logo.js) and [the buttons](https://codesandbox.io/s/react-tailwind-emotion-starter-3d1dl?file=/src/components/Button.js).

More advanced usage docs are also [on the way](https://github.com/ben-rogerson/twin.macro/pull/105).

**Comment by ben-rogerson** [comment]
I think you're right, I should explain that styling within the `style` prop will only apply basic styles.

**Comment by garrrettt** [comment]
Oh interesting. The reason I was using the `style` was because I saw an example somewhere using it (perhaps unofficial). I'm new to Tailwind, so this is helpful information. So far, everything has worked with `style` (without using any variants), so I didn't realize there was a problem until now.

**Comment by ben-rogerson** [comment]
Yeah all good - I totally understand how this could be confusing, especially if only some of the styles are seemingly working with the style tag.
I'm considering going heavy-handed on this by popping an error if tw is used directly on the style tag.

**Comment by ben-rogerson** [comment]
For others stumbling over this issue.

This works with the style prop:
```js
<div style={tw`block`} />

// ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓

React.createElement("div", {
  style: {
    "display": "block"
  }
});
```

Css like this doesn't work with the style prop:
```js
<div style={tw`hover:block`} />

// ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓

React.createElement("div", {
  style: {
    ":hover": {
      "display": "block"
    }
  }
});
```

Solution:

Use the tw prop, the css prop or styled-components.

```js
// Use the tw prop
const Component = <div tw="block" />

// or the css prop
const Component = <div css={tw`hover:block`} />

// or the tw import
const Component = tw.div`hover:block` 

// or the tw import within the styled import
const Component = styled.div(tw`hover:block`)

const Component = styled.div`
  ${tw`hover:block`}
`

const Component = styled.div(() => [tw`hover:block`])
```

**Comment by ben-rogerson** [comment]
From v1.10.0, twin will now pop an error when you try to use `tw` within a style prop 🎉
