### ISSUE TITLE
Documentation to address [Next.js?] Type errors using css prop inline.

### ISSUE THREAD

**Issue by timfee** [ben-rogerson/twin.macro#124]
hey @ben-rogerson and friends!

I'm putzing around with Next.js and I got errors using the `css={tw``}` syntax:
```html 
<div css={tw`flex mt-1 rounded-md shadow-sm`}>foo</div>
```

> Type error: Type '{ children: Element[]; css: TwStyle; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.

I followed [this guidance](https://github.com/styled-components/styled-components/issues/2528#issuecomment-509780963) (except in `twin.d.ts`) and it resolved the issue:

```ts
declare module 'react' {
  interface HTMLAttributes<T> extends DOMAttributes<T> {
    css?: CSSProp
  }
}
```

Not sure exactly if this is Next.js specific, but might be worthwhile to include in the Next.js starter code if so :)

**EDIT:** I also noticed SVG elements get cranky, so inside of the `declare` block, I also added
```ts
  interface SVGProps<T> extends SVGAttributes<T> {
    css?: CSSProp
  }
```

**Comment by ben-rogerson** [comment]
Thanks for bringing this up Tim.
I have "adding css prop types to docs" in my todo list but the svg one is new.

After the changes, `twin.d.ts` should look something like this:

```js
import 'twin.macro';
import styledComponent, {
  CSSProp,
  css as cssProperty,
} from 'styled-components';

// For the css and styled imports
declare module 'twin.macro' {
  const css: typeof cssProperty;
  const styled: typeof styledComponent;
}

// For the css prop
declare module 'react' {
  interface HTMLAttributes<T> extends DOMAttributes<T> {
    css?: CSSProp;
  }
}

// For styling on svg elements
interface SVGProps<T> extends SVGAttributes<T> {
  css?: CSSProp
}
```

I'll perform some testing and those docs should be updated soon after, thanks!

**Comment by ben-rogerson** [comment]
Documentation has been updated, thanks Tim!

**Comment by xuchaobei** [comment]
> Documentation has been updated, thanks Tim!

I have the same issue. But I haven't found the solution in docs...

**Comment by ben-rogerson** [comment]
> > Documentation has been updated, thanks Tim!
> 
> I have the same issue. But I haven't found the solution in docs...

In [the typescript section](https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components#complete-the-typescript-setup), open the collapsable item.
