### ISSUE TITLE
Error with my custom classes

### ISSUE THREAD

**Issue by Eriickson** [ben-rogerson/twin.macro#130]
Hello, I previously had a problem, I commented on it in this way and they responded quickly and with an effective response, now I have a small problem and that is that when I try to add my own class, I get an error (it works as it should) but it is Annoying to see red lines marking errors everywhere
![image](https://user-images.githubusercontent.com/38663299/91351514-6d2dbe80-e7b6-11ea-92c7-85f305028b34.png)

**Comment by ben-rogerson** [comment]
Hey Eriikson, that error isn't coming from twin. It's most likely coming from a vscode extension. Try disabling some of the tailwind extensions and see if the error disappears.
