### ISSUE TITLE
Support for styletron-react

### ISSUE THREAD

**Issue by abhijithvijayan** [ben-rogerson/twin.macro#137]
This is more of a question rather than feature request.

I have used `twin.macro` with `styled-components`

It works perfectly.

I was wondering if `twin.macro` could be used to style [Baseweb ui](https://baseweb.design/) which uses `styletron` by default?

**Comment by ben-rogerson** [comment]
Heya abhijith, I took a look at the source for some of their components. Looks like they aren't spreading the props onto the root components so I don't think twin will work with baseweb.

**Comment by abhijithvijayan** [comment]
Thanks :)
