### ISSUE TITLE
justify-evenly class missing

### ISSUE THREAD

**Issue by sikloidz** [ben-rogerson/twin.macro#139]
Hi!,

I was trying out twin.macro with a new website I'm building and came across this issue, I was trying to use `justify-evenly` (present in tailwind https://tailwindcss.com/docs/justify-content), but start getting an error that `justify-evenly` was not found, so I had a look in the source code and found out that the class is not included

https://github.com/ben-rogerson/twin.macro/blob/b6a701951bc3a15e1b03f7cd21e56d01de03a2ec/src/config/staticStyles.js#L225-240

Thanks for the awesome work on this macro!

**Comment by ben-rogerson** [comment]
heya, no worries - thanks for pointing out the missing class.
I've added [`justify-evenly` in v1.8.1](https://github.com/ben-rogerson/twin.macro/releases/tag/1.8.1) 👍
