### ISSUE TITLE
group class not found

### ISSUE THREAD

**Issue by Jfelix61** [ben-rogerson/twin.macro#14]
https://tailwindcss.com/docs/pseudo-class-variants/#group-hover 

Is this class scheduled to be added?

**Comment by ben-rogerson** [comment]
Group hover is available but perhaps it's not the same implementation as tailwind, could you confirm?
https://github.com/ben-rogerson/twin.macro/blob/925152ca39c2270584a2ae14aa1943369e4665a3/src/variants.js#L60

**Comment by Jfelix61** [comment]
![image](https://user-images.githubusercontent.com/21092519/76579495-cf159880-64a2-11ea-888d-c7ec395ab42a.png)

The app crashes since it does not find the class. It must be a bug then.

**Comment by ben-rogerson** [comment]
Thanks, I'll take a look into it

**Comment by ben-rogerson** [comment]
This is now fixed in 1.0.0-alpha.8 🎉
I've added some extra group classes too:

- group-hocus
- group-focus
- group-active
- group-visited
