### ISSUE TITLE
Support Tailwind CSS v1.8.0

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#141]
Damn @adamwathan has been busy!
Twin needs to catch up so we can all use these new toys:

## Easy

- [8x new font variant utilities](https://github.com/tailwindlabs/tailwindcss/pull/2305)
Done - see #143 
- [28x grid alignment utilities](https://github.com/tailwindlabs/tailwindcss/pull/2306)
Done - see #145 

## Over easy 🍳 

- [Dark mode variant](https://github.com/tailwindlabs/tailwindcss/pull/2279)
Done - see #142

**Comment by lednhatkhanh** [comment]
Woohoo, can't wait for the release!

**Comment by ben-rogerson** [comment]
1.9.0 is up! 🎉
