### ISSUE TITLE
Error using twin.macro with react-testing-library

### ISSUE THREAD

**Issue by duranmla** [ben-rogerson/twin.macro#147]
Hi! Apologize if this may not be the right place to add this issue but I have seen several issues "around" this within the issues section nevertheless, I still can't find a solution for my problem.

So far I have been enjoying the library a lot and it is a shame that the support for a testing lib like https://github.com/testing-library/react-testing-library seems to now come out of the box. Is there any place where I can find an example of this integration working?

The project I am contributing to is https://github.com/debtcollective/home/tree/donation-widget/form-base-aesthetics and the configuration files can be seen at https://github.com/debtcollective/home/blob/donation-widget/form-base-aesthetics/jest.setup.js https://github.com/debtcollective/home/blob/donation-widget/form-base-aesthetics/jest.config.js https://github.com/debtcollective/home/blob/donation-widget/form-base-aesthetics/jest-preprocess.js 

I'm pretty much try to follow the guidance from Gatsby and Storybook to set everything up and I have found a project that helps me at https://github.com/rbutera/greater-gatsby but I can't finalise to get this done. The error I am having is

```
Test suite failed to run

    MacroError: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros. This indicates that you don't have the babel plugin "babel-plugin-macros" configured correctly. Please see the documentation for how to configure babel-plugin-macros properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md
```

![image](https://user-images.githubusercontent.com/1425162/92997935-28748800-f517-11ea-8f55-9628fe3f05ae.png)

**Comment by duranmla** [comment]
Well... After seeing this closer I have done the following:

```js
// jest.config.js
module.exports = {
  transform: {
    // be careful not to add 'ts-jest'
    '^.+\\.[jt]sx?$': '<rootDir>/jest-preprocess.js'
  },
  // your things...
};
```

and

```js
//jest-preprocess.js

const babelOptions = {
  presets: ['@babel/env', 'babel-preset-gatsby', '@babel/preset-typescript'],
  plugins: ['babel-plugin-macros']
};

// eslint-disable-next-line @typescript-eslint/no-var-requires
module.exports = require('babel-jest').createTransformer(babelOptions);
```

And it should work!! 🎉

**Comment by lukesmurray** [comment]
Update with what worked for me

```tsx
const babelOptions = {
  presets: ["@babel/env", "@babel/preset-react", "@babel/preset-typescript"],
  plugins: ["babel-plugin-macros"],
};

// eslint-disable-next-line @typescript-eslint/no-var-requires
const transformer = require("babel-jest").default;

module.exports = transformer.createTransformer(babelOptions);

```

**Comment by ben-rogerson** [comment]
Here's a related link to the [jest + react testing library example →](https://github.com/ben-rogerson/twin.examples/tree/master/jest-testing-typescript)
