### ISSUE TITLE
Can not use gap-x and gap-y

### ISSUE THREAD

**Issue by bnhr** [ben-rogerson/twin.macro#149]
I facing issues where I can not use gap-x and gap-y in GatsbyJS the terminal shows error : 
`✕ gap-y-6 was not found
Try one of these classes:
gap-6 [1.5rem] / gap-64 [16rem]`

**Comment by ben-rogerson** [comment]
Hey Heru, I've made a [demo to show it's working in twin v1.8.0](https://codesandbox.io/s/gatsby-styled-components-tailwind-twin-starter-forked-tz5we?file=/src/pages/index.js).

If you're already using 1.8.0+, could you please post your full `tailwind.config.js`? I suspect there could be an issue there.

**Comment by bnhr** [comment]
I used twin v1.7. After run yarn upgrade, it's working fine. Thank you
