### ISSUE TITLE
Apply style conditionally

### ISSUE THREAD

**Issue by gulzaryousaf** [ben-rogerson/twin.macro#150]
How can we apply the styles conditionally? it doesn't take any variable even if that variable has the String value in it, there should be a way or applying styles based on specific conditions.

**Comment by ben-rogerson** [comment]
Take a look at these guides I'm working on:

- [The css prop guide](https://github.com/ben-rogerson/twin.macro/blob/d25b984a6f713ed96173e29cd49992fd4d783e78/docs/css-prop-guide.md)
- [The styled import guide](https://github.com/ben-rogerson/twin.macro/blob/d25b984a6f713ed96173e29cd49992fd4d783e78/docs/styled-import-guide.md)

**Comment by gulzaryousaf** [comment]
This is cool, Thanks.

I was thinking to apply styles conditionally to tw="border-gray-500" like we add or remove class  conditionally in React JS but the above solution works perfect. 👍
