### ISSUE TITLE
Custom "css" config isn't invoked when using tagged literals

### ISSUE THREAD

**Issue by edible-programs** [ben-rogerson/twin.macro#152]
In an attempt to adapt twin to react native, I've configured it as follows:

```
{
  "babelMacros": {
    "twin":{
      ...
      "styled": {
        "import": "default",
        "from": "styled-components/native"
      },
      "css": {
         "import": "default",
         "from": "my-custom-thing"
      }
    }
  }
}
```
To illustrate: what I am expecting from this configuration is that when using twin for tagged literals like so ``tw`flex-1`;`` that the output is processed through `my-custom-thing` just like ``tw(View)`flex-1`;`` is processed through `styled-components/native`

Unfortunately, this is not the case as ``tw`flex-1`;`` will return the same value regardless of what I specify under the "css" property in my config.

This is critical for working with react-native as I need to use a custom function to transform raw css rules, like `margin-top: 10px;` to react-native compatible objects,  like `{ marginTop: 10 }`. As I am unsure how you architected this internally, I don't know if there is any way to configure twin such that I have access to this processing step (or if this is a processing step at all).

I did notice, however, that `import tw, { css } from 'twin.macro'` imports `my-custom-thing` as `css`.

Hope this question is clear. Thank you!

**Comment by ben-rogerson** [comment]
Hey there, twin does the tailwind class processing during Babel compilation, so you'll only be able to pass a css object through to a custom function of your own.

> This is critical for working with react-native as I need to use a custom function to transform raw css rules, like margin-top: 10px; to react-native compatible objects, like { marginTop: 10 }

You can specify custom tailwind.config.js values that should work with react native.
That way you could use tw.div`` or styled.div`` for the styling.

```js
module.exports = {
  theme: {
    margin: {
        10: '10',
    },
}
```

Using tw to make styled-components:

```js
import tw from 'twin.macro'

const View = () => {}
tw(View)`mt-10`

// ↓ ↓ ↓ ↓ ↓ ↓

import _styled from "styled-components/native";

const View = () => {};
_styled(View)({
  "marginTop": "10"
});
```

or using styled to make styled-components:

```js
import tw, { styled } from 'twin.macro'

const View = () => {}
styled(View)([tw`mt-10`])

// ↓ ↓ ↓ ↓ ↓ ↓

import _styled from "styled-components/native";

const View = () => {};
_styled(View)([{
  "marginTop": "10"
}]); 
```

You can also use css with a custom config like this (but you can't style existing components):

```js
import tw, { css } from 'twin.macro'

css([tw`mt-10`])

// ↓ ↓ ↓ ↓ ↓ ↓

import _css from "my-custom-thing";

_css([{
  "marginTop": "10"
}]);
```

and my config in package.json to create this output:

```js
"babelMacros": {
    "twin": {
      "styled": {
        "import": "default",
        "from": "styled-components/native"
      },
      "css": {
        "import": "default",
        "from": "my-custom-thing"
      }
    }
  },
```

**Comment by edible-programs** [comment]
Thank you so much for the detailed response. As you pointed out
```JSX
import { View } from 'react-native'
import tw, { css, styled } from 'twin.macro'

tw(View)`mt-10`

// ↓ ↓ ↓ ↓ ↓ ↓

import _styled from "styled-components/native";

const View = () => {};
_styled(View)({
  "marginTop": "10"
});
```
works fantastically. To achieve what I wanted, I made sure the use the `css` prop, as follows:
```JSX
import { View } from 'react-native'
import tw from 'twin.macro'

export default ({ style, children, ...props }) => {
  return <View css={tw`absolute`} style={style} >{children}</View>
}
```
but the following does _not_ work

```JSX
import { View } from 'react-native'
import tw from 'twin.macro'

export default ({ style, children, ...props }) => {
  return <View style={[tw`absolute`, style]}>{children}</View>
}
```
With a couple custom plugins, I have twin working on react native! Very happy with the result, it has been a major source of productivity. Thank you for this project.

**Comment by ben-rogerson** [comment]
That's great news, next time I'm making a native app this will come in handy 👍 

It would be great to post your plugin code here so others can have a quicker setup.

**Comment by JimmyLv** [comment]
> With a couple custom plugins, I have twin working on react native!

Hi @edible-programs @ben-rogerson , could you please help to post the plugin code? 😁 Thanks

**Comment by joshmeads** [comment]
I wonder if we could leverage https://github.com/styled-components/css-to-react-native?

I also saw this macro: https://github.com/kristerkari/css-to-react-native-transform, which appears to use the above. It would be great if we could add a preset of "react-native" and simply import from styled-components/native automatically and do the unit transformation. Of course, I know nothing about the inner workings of twin.macro currently so I'm not going to speak for others.

While I don't personally have time to look into it right now, I may do in the coming months if no one else has taken it upon themselves. I hope this at least helps someone :).

Great work and thank you @ben-rogerson - love twin.macro
