### ISSUE TITLE
Not able to use group class

### ISSUE THREAD

**Issue by yashSangai** [ben-rogerson/twin.macro#156]
#### The problem

When I am trying to add group class to an element using tw, it is throwing an error and suggesting me to use class names instead.

**For Reference:** https://tailwindcss.com/docs/pseudo-class-variants#group-hover

#### Bug reproduction

```
<div css={tw`group bg-white hover:bg-blue-500`}>
  <p css={tw`text-gray-700 group-hover:text-white`}>Hello World.</p>
</div>
```

**Comment by ben-rogerson** [comment]
The group classes work a little differently to others, they need to be added as a `className`, [take a look at this doc](https://github.com/ben-rogerson/twin.macro/blob/master/docs/group.md).

**Comment by yashSangai** [comment]
> The group classes work a little differently to others, they need to be added as a `className`, [take a look at this doc](https://github.com/ben-rogerson/twin.macro/blob/master/docs/group.md).

Thanks for the info!
