### ISSUE TITLE
Disabling textOpacity/backgroundOpacity should remove the variables similar to tailwind's output

### ISSUE THREAD

**Issue by cybervaldez** [ben-rogerson/twin.macro#160]
In Tailwind, disabling the text and background opacity would remove the variables but this is not the case for twin.macro.

```
// tailwind.css (original)
.bg-red-400 {
  --bg-opacity: 1;
  background-color: #fc8181;
  background-color: rgba(252, 129, 129, var(--bg-opacity));
}

// tailwind.config.js
  corePlugins: {
    textOpacity: false,
    backgroundOpacity: false,
  },

// tailwind.css (with above settings)
.bg-red-400 {
  background-color: #fc8181;
}

// twin.macro
console.log(tw`bg-red-400`) // { --bg-opacity: "1", backgroundColor: "rgba(252, 129, 129, var(--bg-opacity))"}
```

this is adding some unnecessary overhead, in my case i'm using twin.macro to animate object properties so I would prefer to only manipulate the background or color properties(as it should).

_Originally posted by @cybervaldez in https://github.com/ben-rogerson/twin.macro/issues/86#issuecomment-707237243_

**Comment by ben-rogerson** [comment]
I'm keen on hearing your thoughts on the overhead.
Are you noticing poor animation performance because of the css variable?

**Comment by r0skar** [comment]
Sidenote: disabling the CSS variables also helps with IE11. While there are a couple of polyfills, none of them handles nested variables very well and we had a hard time making it work.

**Comment by cybervaldez** [comment]
> I'm keen on hearing your thoughts on the overhead.
> Are you noticing poor animation performance because of the css variable?

It does since many of the animation libraries(I'm using framer motion) goes through each property every animation frame. Those extra props also makes debugging very unwieldy when there's a lot of animation going on. Also the issues the variables bring with IE11 as @r0skar as pointed out

But ultimately, we should be expecting the same output similar to that of tailwind.css

**Comment by ben-rogerson** [comment]
There are no plans to add true IE11 support to Twin, but perhaps there could be something in the twin config that disables the css variables within colors?

Eg:

```js
"babelMacros": {
    "twin": {
        // ...
        "disableColorVariables": true
    }
}
```

Anyone feel like leading the charge?

**Comment by ben-rogerson** [comment]
@cybervaldez @r0skar Could you please check my PR and see if this covers your use-cases?

**Comment by ben-rogerson** [comment]
The feature is now in [v1.12.0](https://github.com/ben-rogerson/twin.macro/releases/tag/1.12.0) 🎉
