### ISSUE TITLE
String interpolation inside tw macro doesn't work

### ISSUE THREAD

**Issue by semirart** [ben-rogerson/twin.macro#17]
Hi!

I have a problem with string interpolation in tw macro. 
For example I need to customize border color, so I'm trying to do it like this:

```javascript
export const PrimaryButton = styled(Button)`
  ${({ color }) => tw`hover:border-${color ?? 'blue'}`};
`;
```

But I get the following error:
`✕ Class “hover:border-” shouldn’t have a trailing dash.`

It also doesn't work without variables:
```javascript
export const PrimaryButton = styled(Button)`
  ${({ color }) => tw`hover:border-${'blue'}`};
`;
```

**Comment by rbutera** [comment]
I've run into this issue before. I think the only solution is to do something like this instead:

```javascript
export const PrimaryButton = styled(Button)`
  ${({ color }) =>  color === 'blue' ?  tw`hover:border-blue-400` : tw`hover:border-gray-400`};
`;
```
or you could do something like this

```javascript
const generateBorderColor = (color) {
 switch(color) { 
      case 'blue': 
           return tw`hover:border-blue-400`
      default:
           return tw`hover:border-gray-400`
    }
} 

const PrimaryButton = styled(Button)`
   ${({color}) => ${generateBorderColor(color}}}
`
```

**Comment by semirart** [comment]
@rbutera Thanks for suggestions. 
Unfortunately, it's very inflexible solution, because we have lots of colors.
I wonder if we could make it work properly with interpolation.

**Comment by ben-rogerson** [comment]
I think everyone comes across this limitation sooner or later.
It's because babel macros (the plugin twin uses) run before the interpolation occurs.

@rbutera has some good recommendations, especially with the generateBorderColor function. Otherwise, try using a combination of vanilla css and a theme provider to pass the tailwind config colours down into the component.

**Comment by semirart** [comment]
@ben-rogerson I think it's not a babel-plugin-macros issue, because I couldn't find any such issue in their repo.

Also I see that it works properly here: https://github.com/vinhlh/tagged-translations#via-babel-plugin-macros

And maybe if function calls like `tw()` worked we wouldn't have this problem?

**Comment by ben-rogerson** [comment]
Interesting, I think that's worth looking into for sure.

**Comment by MMT-LD** [comment]
Personally this would be a huge benefit for using this plugin. I did take a look, however, my knowledge of writing babel plugins/macros is somewhat slim. I would imagine this is a small change. It might be worth looking at how emotion { css } prop works, as they have a function that get utilised via a macro (css) but is still able to be used as a function... super super cool

**Comment by MMT-LD** [comment]
Update: @semirart suggests  https://github.com/vinhlh/tagged-translations#via-babel-plugin-macros having played with this  ... so for quickness. I installed the tagged-translations macro .... added a folder to cra app called translations/default.json added `{
    "%s": "%s"
  }`
```javascript
import t from 'tagged-translations/macro';

export const styles = (ts) => t`${ts}`;

console.log(styles(`text-red-100 hover:bg-blue-200`))
```
in another file...
```javascript
import React from 'react';
import { styles } from "./App";

export default () => <div>cool{styles(`text-red-100 hover:bg-blue-200`)}</div>;
```
and the output...

matched the correct string 'text-red-100 hover:bg-blue-200' so dynamic passing of styles works which could mean way more flexibility. This would mean library authors could use this in many different ways.

**Comment by ben-rogerson** [comment]
thanks for the bump on this - I've taken a look into the tagged translations output.
In this test you can see that `t` doesn't support being used in a function:

```js
// In
import t from "tagged-translations/macro";

const styles = ts => t`${ts}`;
styles(`text-red-100 hover:bg-blue-200`);

// Out
const styles = ts => `${ts}`;
styles(`text-red-100 hover:bg-blue-200`);
```

I'm going to look at how the css prop can be used as a macro, hopefully that leads to something.

**Comment by ben-rogerson** [comment]
I've takes a look at Emotions css macro and it's switching the css macro out with their runtime library when babel runs:

```js
// In
import css from "@emotion/css/macro";
const test = (...args) => css(...args);

// Out
import _css from "@emotion/css";
const test = (...args) => _css(...args);
```

and if you're using it with css (I've stripped away their dev stuff):

```js
// In
import css from "@emotion/css/macro";
css`color: black`;

// Out
import _css from "@emotion/css";
({
  name: "1xu3tth",
  styles: "color:black;"
});
```

Twin doesn't have a runtime (it compiles away when Babel runs) so this approach isn't a possibility.
Here are the same tests with Twin:

```js
// In
import tw from "twin.macro";
const test = (...args) => tw(...args);

// Out
const test = (...args) => tw(...args);
```

and with a class:

```js
// In
import tw from "twin.macro";
tw`text-black`;

// Out
({
  "color": "#000"
});
```

I'm open to further ideas, keeping in mind there are no plans to create a `tw` runtime.

**Comment by MMT-LD** [comment]
> thanks for the bump on this - I've taken a look into the tagged translations output.
> In this test you can see that `t` doesn't support being used in a function:
> 
> ```js
> // In
> import t from "tagged-translations/macro";
> 
> const styles = ts => t`${ts}`;
> styles(`text-red-100 hover:bg-blue-200`);
> 
> // Out
> const styles = ts => `${ts}`;
> styles(`text-red-100 hover:bg-blue-200`);
> ```
> 
> I'm going to look at how the css prop can be used as a macro, hopefully that leads to something.

Maybe i'm missing the point. But at the moment how would you support theming using this type of macro? For me id like to pass in dynamic tags to tw to make it something a bit more dynamic otherwise i may as-well just include tailwind manually and use their classnames. Im not saying this isn't a good macro as i can see its benefits when using it in for example emotions css selector. 

The only thing is that if i built a ui library using tw.macro (maybe not the right tool) then how when in the project that is using these components would you style (override) the components. You would have to include tw macro in the project as well has the lib to utilise tailwind as when you ship the ready made component the css will have been generated upfront by the macro.

No idea if i'm making any sense, maybe styled-system is a better approach for this :-)

**Comment by ben-rogerson** [comment]
>... when you ship the ready made component the css will have been generated upfront by the macro.
Yeah, your library components should be pre-generated.

I understand you're seeking a more dynamic way of passing Tailwind through but I currently don't know how that would be possible with Twin.
There's a couple of ways you could then restyle your lib components (but I'm not saying it's pretty 😄 ):

```js
import { List, ListItem } from 'mylib'

const RestyledList = tw(List)`mt-3`

<>
<RestyledList>
    <ListItem tw="text-red-500">Item</ListItem>
</RestyledList>
<>
```

**Comment by nightgrey** [comment]
> I think everyone comes across this limitation sooner or later.
> ~It's because babel macros (the plugin twin uses) run before the interpolation occurs.~
> Edit: Interpolation coming soon.

Hey Ben, is interpolation still coming / do you have a solution for it?

If yes, is there a way to help?

**Comment by ben-rogerson** [comment]
hey Nico, no solution yet.
I had a crack at it a week ago but didn't get too far.

Help is welcomed for sure - I believe [this is where to start](https://github.com/ben-rogerson/twin.macro/blob/4aec33b920a20db6e8305559d3ae2edddabf3aa0/src/macroHelpers.js#L152).
Previous experience with Babel plugins or traversing ASTs is a plus 😃

**Comment by JohJonker** [comment]
Hi @ben-rogerson, thanks for looking into this. Interpolation support would be a game-changer for flexibility, even if just with a basic variable like the example you show above. Is this planned for inclusion soon, or is it better to fork for now?

PS. Twin is probably the tool that brings me the most developer happiness at the moment. :) Thanks for all your hard work!

**Comment by rbutera** [comment]
If you can fork it and implement this ai think I speak on behalf of everyone and please submit a PR, Johannes 😃

Sent via Superhuman iOS ( https://sprh.mn/?vip=rai@rbutera.com )

**Comment by JohJonker** [comment]
Hi @rbutera, I was just referring to replacing the line like Ben suggested above. Unfortunately I don’t have any other insight into solving the issue. :(

Happy to try submit a PR changing the line as per Ben’s suggestion if he prefers that?

**Comment by JohJonker** [comment]
@ben-rogerson I tested out the patch you suggested.

> Edit: Not sure if this is useful, but replacing that line with this:
> 
> ```js
> const string = path.get('quasi').evaluate().value
> ```
> 
> Will allow you to pass a plain variable into the backticks but it's quite limited. It can't be conditional or a function:
> 
> ```js
> const className = 'flex';
> tw`${className}`
> ```

I thought I'd add a further data point. As you say, it works for simple variables. It doesn't seem to work for this use case, though:

```js
const { styles } = config.button; // = 'inline-block font-semibold rounded tracking-wider border border-transparent`
const styles2 = `inline-block font-semibold rounded tracking-wider border border-transparent`;

console.log(styles === styles2); // = true

console.log(tw`${styles2}`); // = {display: "inline-block", fontWeight: "600", borderRadius: "0.25rem", letterSpacing: "0.05em", borderWidth: "1px", ...}
console.log(tw`${style}`); // bombs out
```

I have some predefined styles stored as raw Tailwind classes (`styles`). The value hereof is equivalent to a simple variable definition (`styles2`). However, when I use this with the macro, it bombs out with:

`twin.macro: Cannot read property 'match' of undefined`

I can't figure out exactly where this is happening in the plugin, but the 'match' function call is only present in these locations:

/src/getStyles.js:20
`const classList = string.match(/\S+/g) || []`
/src/utils.js:129
`const match = x.selector.match(/^\.(\S+)(\s+.*?)?$/)`
/src/variants.js:87
`modifier = className.match(/^([_a-z-]+):/)`

Any ideas as to why the string/selector/className would be coming through undefined, and how to add a workaround? 

Thanks for your help! Unfortunately, I'm not familiar with Babel Macros, otherwise I could've been of more use.

**Comment by ben-rogerson** [comment]
I think it may be happening in `/src/getStyles.js:20`and it's failing because the string isn't being interpolated and getting passed as `undefined`.
I'll have a new version out shortly and I'll take another look into it shortly afterwards.

**Comment by yeungc** [comment]
> 
> 
> I've run into this issue before. I think the only solution is to do something like this instead:
> 
> ```js
> export const PrimaryButton = styled(Button)`
>   ${({ color }) =>  color === 'blue' ?  tw`hover:border-blue-400` : tw`hover:border-gray-400`};
> `;
> ```
> 
> or you could do something like this
> 
> ```js
> const generateBorderColor = (color) {
>  switch(color) { 
>       case 'blue': 
>            return tw`hover:border-blue-400`
>       default:
>            return tw`hover:border-gray-400`
>     }
> } 
> 
> const PrimaryButton = styled(Button)`
>    ${({color}) => ${generateBorderColor(color}}}
> `
> ```

Hi anyone, I got stuck with this issue too, the switch approach is good enough if we have only a few colors, but what if 20+ colors, or even 30+? The code will be super long and incompatible with reusing logic.

**Comment by ben-rogerson** [comment]
You could try a style map:

```js
const styleMap = {
  primary: tw`bg-black text-white`,
  secondary: tw`bg-white text-black`
}

const getStyleName = ({ name }) => styleMap[name] || tw`bg-gray-500`

const ButtonStyled = styled.button(getStyleName)

const Buttons = () => (
  <>
    <ButtonStyled name="primary">Primary</ButtonStyled>
    <ButtonStyled name="secondary">Secondary</ButtonStyled>
    <ButtonStyled>Secondary</ButtonStyled>
  </>
)
```

**Comment by hmajid2301** [comment]
Hi, is there any update on this ? What is happening with this issue ? Can I help out at all ?

**Comment by alexhillel** [comment]
I remember when working with Vue, I could apply Tailwind classes to the `class` attribute of a custom component, and they would automatically get appended to the component's root element, creating a really powerful override workflow that sat really nicely with Tailwind.

I'm new to both React and twin.macro, so please correct me if I'm wrong - if I wanted a similar workflow using `className` I'd need to explicitly pass the prop down and use string interpolation to add the passed down `className` prop to the component's root element's `className`.

Am I correct in thinking that this string interpolation issue prevents a similar overriding workflow being possible with twin.macro's `tw` prop?

**Comment by ben-rogerson** [comment]
@hmajid2301 I've halted work on it for now, but feel free to help out. Maybe jump in our discord to discuss sometime.
@alexhillel There are decent ways around interpolating classes, take a look at [this codepen that shows different ways your styles could be assembled](https://codesandbox.io/s/prop-example-kfhgd?file=/src/App.js).

**Comment by hmajid2301** [comment]
I know this isn't a great solution but one possible one i've gotten around it using emotionjs and tw. Is doing something  like

```jsx
const Container = styled.div`${tw`-mx-8 -mb-8`}`;

const Component = ({
  background = 'gray-200',
  color = 'gray-700',
}: Props) => (
     <Container className={`bg-${background} text-${color}`}>
          Text Here
     </Container>
)
```

Where the dynamic tailwind options are passed as props to `className`.

**Comment by IRediTOTO** [comment]
this should be future feature :D

**Comment by Acidic9** [comment]
This is especially useful when using padding in the tailwind macro - eg: `gap`.

```typescript
declare const gap: number

const styles = tw`px-${gap}`
```

I'm not sure whats the best workaround currently.

**Comment by ben-rogerson** [comment]
> This is especially useful when using padding in the tailwind macro - eg: `gap`.
> 
> ```ts
> declare const gap: number
> 
> const styles = tw`px-${gap}`
> ```
> 
> I'm not sure whats the best workaround currently.

Interpolation isn't possible with Babel macros so try using something like this:

```js
const gapSize = size => ({
  small: tw`px-2`,
  large: tw`px-4`,
}[size]);

const smallGap = gapSize('small')
```

**Comment by Acidic9** [comment]
@ben-rogerson yep that's what I ended up doing, it's just a shame because I needed to also accomodate for `sm`, `md`, `lg` and `xl` of all the sizes, and my gapSize objects ended up being over 225 lines of code - but I don't think there's any other option so it's fine for now

**Comment by fvanwijk** [comment]
I documented all the spacings in Storybook and therefore stumbled upon the same issues.
This does not work:
```jsx
const { spacing } = useTheme();
Object.entries(spacing).map(([key, value]) =>
  <div key={key}>
    <div>{key}</div>
    <div tw={`px-${key}`}>...</div> // error, no interpolation allowed
  </div>
);
```
I fixed it by using the 'raw' spacing values from the tailwind config instead of using `tw`:
```jsx
<div css={{ paddingRight: value, paddingLeft: value }}>...</div>
```

**Comment by ben-rogerson** [comment]
Worth noting is that this won't get the combined config values, only the ones you define in your tailwind.config.js.
Perhaps the theme import could be updated to grab the entire combined theme if you leave off the backticks. Currently, the theme import only grabs a single theme value.
eg: 
```js
import { theme } from 'twin.macro'
const { spacing } = theme

Object.entries(spacing).map(([key, value]) =>
  <div key={key}>
    <div>{key}</div>
    <div tw={`px-${key}`}>...</div> // error, no interpolation allowed
  </div>
);
```

**Comment by wahyupriadi** [comment]
> 
> Interpolation isn't possible with Babel macros so try using something like this:
> 
> ```js
> const gapSize = size => ({
>   small: tw`px-2`,
>   large: tw`px-4`,
> }[size]);
> 
> const smallGap = gapSize('small')
> ```

can we simplify it like
```js
const gapSize =  {
small: tw`px-2`,
large: tw`px-4`,
};

console.log(gapSize['small'])
```
it will return the same

**Comment by ben-rogerson** [comment]
@wahyupriadi Sure - that works too 👍  You just need use `tw` alongside the value.

**Comment by rattrayalex** [comment]
Naive question, and possibly not constructive, from someone without twin experience: Could TS types be used (and thus required) for interpolation? Eg;

```ts
// lib:
module TW {
  type Color = 'blue' | 'red' | ...;
}

// in:
import {TW} from 'twin.macro';
export const PrimaryButton = styled(Button)`
  ${({ color }: { color: TW.Color }) => tw`border-${color ?? 'blue'}`};
`;

// out:
export const PrimaryButton = styled(Button)(color => ({
  border: `1px solid ${{ blue: '#00F', red: '#F00' }[color]}`
}));
```

Of course, since Babel does not have access to TS's toolchain during compilation, the union types used would have to be quite simplistic, like only unions coming directly from twin, or defined as a single literal within the file. Anything "fancy" like `type AllowedColors = Exclude<TW.Color, 'orange'>` or a shared union of colors defined in another file, wouldn't work – and I can definitely imagine design system engineers really wanting those.

Worth noting also that ~any interpolation scheme would probably cause a surprising amount of code bloat. Perhaps better to rely on raw `css` or `style` attributes if you want truly dynamic "pass whatever you want" styling, and switch statements or equivalent when the options used in practice are limited to a handful.

**Comment by ben-rogerson** [comment]
@rattrayalex Twin doesn't know how to work with TS interpolation like that, perhaps take a look at [these guides I'm working on](https://github.com/ben-rogerson/twin.macro/pull/105) for all the ways you can use conditional styling

**Comment by kelvindecosta** [comment]
I tried this approach with a simple `Button` component:

```jsx
import React from "react"
import tw, { styled } from "twin.macro"

const ButtonWrapper = styled.button(() => [
  tw`p-1 text-base text-white border-b-2 rounded active:border-none focus:outline-none`,
  handleHue,
])

const handleHue = ({ hue = "default" }) => hueStyleMapping[hue]

const hueStyleMapping = {
  red: tw`bg-red-600 border-red-800`,
  default: tw`text-gray-700 bg-white border-gray-300 dark:bg-gray-600 dark:text-white dark:border-gray-700`,
}

const Button = ({ children, ...props }) => (
  <ButtonWrapper {...props}>{children}</ButtonWrapper>
)

export default Button
```

![Screenshot_20210122_053416](https://user-images.githubusercontent.com/38982451/105438308-cb7ea080-5c73-11eb-8a3e-6901e9e3bc90.png)
![Screenshot_20210122_053440](https://user-images.githubusercontent.com/38982451/105438309-cc173700-5c73-11eb-9e0f-2120970b35f2.png)

The first button, is a simple Dark Mode toggler, with `hue` set as "default".
The second button has `hue` set as "red".

For some reason, the `dark` variant is having an issue.
As per my understanding, the red button should remain red, even in dark mode.

Any help is appreciated!

**Comment by kelvindecosta** [comment]
I figured it out!

```jsx
const hueStyleMapping = {
  default: [
    tw`text-gray-700 bg-white border-gray-300`,
    tw`hover:bg-gray-100 hover:border-gray-400`,
    tw`dark:bg-gray-600 dark:text-white dark:border-gray-700`,
    tw`dark:hover:bg-gray-700 dark:hover:border-gray-800`,
  ],
  red: [tw`bg-red-600 border-red-800`],
}
```

It works by placing them in an array. I honestly don't know why. 

![Screenshot_20210122_060208](https://user-images.githubusercontent.com/38982451/105440289-62992780-5c77-11eb-99fd-ee59bd1f293e.png)

**Comment by ben-rogerson** [comment]
@kelvindecosta If you're using `styled-components` [you're probably hitting the & issue](https://github.com/ben-rogerson/twin.macro/issues/297) with those dark classes. Great job with that workaround though, I think it's working because you're forcing styled-components to create separate styling objects.

**Comment by kelvindecosta** [comment]
Unfortunately, I forgot that I had changed a few styles.
The bug only _seemed_ to have disappeared.

@ben-rogerson, I looked into the `&` issue a little closer.
I decided to downgrade `styled-components`, and that definitely fixed it.

Thank you!

**Comment by AlaDouagi** [comment]
This an unfortunate big limitation :cry: .

**Comment by ben-rogerson** [comment]
> This is an unfortunate big limitation 😢 .

I can help out - do you have an example of what you'd like to achieve?

**Comment by onesneakymofo** [comment]
@ben-rogerson I would like to see your thoughts on how you would refactor [my button component](
https://github.com/onesneakymofo/mantle/tree/master/src/components/Button). I converted this over the weekend and hit this road block as soon as I was done converting. Like @AlaDouagi, this is a huge limitation on what I'm trying to accomplish (generic Tailwind UI component library).

Unfortunately my JS skills aren't deep enough to help fix the problem so I may have to revert to [how I was doing it](https://github.com/onesneakymofo/mantle/blob/67f8b5410a437ae9444d90cabcfc5efa7eaca242/src/components/Button/style.js).  I would love to see your thoughts though.

**Comment by ben-rogerson** [comment]
@onesneakymofo If you're in the mindset that your components should be able to accept every combination of color/border etc then I'm afraid you won't get too far here.
You'll need to analyse the components your site/app requires and develop styles that create the look with a minimal amount of props driving them.

Something along these lines:

```js
const styleMap = {
  primary: tw`bg-black text-white`,
  secondary: tw`bg-white text-black`,
  default: tw`bg-gray-500`
}

const getStyleName = ({ name }) => styleMap[name] || styleMap.default

const Button = styled.button(getStyleName)

const Buttons = () => (
  <>
    <Button name="primary">Primary</Button>
    <Button name="secondary">Secondary</Button>
    <Button>Default</Button>
  </>
)
```

You can combine styleMaps but the rule is that your components can't build any classes up from interpolated strings.

Sidenote: I'm limiting this thread as it's getting a little too spammy for the people who have commented before this. 
If anyone is still unsure of what's required, feel free to [open a discussion](https://github.com/ben-rogerson/twin.macro/discussions/new) or [drop into our discord server](https://discord.gg/Xj6x9z7). Thanks!

**Comment by ben-rogerson** [comment]
Apologies for the deletions here, just doing a bit of housework to make this thread a little more scannable for solutions ✌️

**Comment by ben-rogerson** [comment]
Closing this issue in favor of [this discussion](https://github.com/ben-rogerson/twin.macro/discussions/393)
