### ISSUE TITLE
Maximum call stack size exceeded in v1.11.0

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#175]
In v1.11.0, you'll see a `Maximum call stack size exceeded` error often when you get a class wrong.

Fix: Either downgrade to v1.10.0 or wait for the patch which will be released shortly.

**Comment by eddiewang** [comment]
Worth clarifying that this bug only occurs when there is an invalid class in twin.macro. Once that's removed the error goes away. The bug here is that it's difficult to target which specific class we need to remove to fix tw's compilation.

**Comment by ben-rogerson** [comment]
Fixed in 1.11.1 🎉
