### ISSUE TITLE
CRA + Twin.Macro Component UI Monorepo

### ISSUE THREAD

**Issue by skene** [ben-rogerson/twin.macro#18]
To start off, I wanna say thank you @ben-rogerson for building this! I was in the process doing just that for tailwindcss 2.0 support but then came across this, so thank you.

Im in the process of setting up a monorepo with a CRA app + components ui library and I end up getting the following error when building the CRA:

`MacroError: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros. This indicates that you don't have the babel plugin "babel-plugin-macros" configured correctly. Please see the documentation for how to configure babel-plugin-macros properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md`

Im assuming this is from default CRA babel config, but it works when removing `tw` from the styled-component macro from the component library. I set up the following repro for reference: https://github.com/skene/cra-twin.macro-monorepo

I have a feeling im being stupid and missing something obvious.

**Comment by ben-rogerson** [comment]
I had a good crack at trying to get babel-plugin-macros to work from your components library but no luck.
I suspect that you need to get `babel-plugin-macros` working in your component library so it's compiled correctly with rollup before being imported into your app.

**Comment by ben-rogerson** [comment]
Please let me know if you get your component library working (with tw) and I'll add an example to the readme.

**Comment by skene** [comment]
Will do, i had some other business to take care of but ill get back to it sometime this week.

**Comment by MMT-LD** [comment]
@ben-rogerson @skene Well i had that issue and for some reason "es5" in tsconfig.json bundle removes some elements and does not transpile #30 . If you swap to "esnext" in your tsconfig,json it will bundle correctly. Im not sure who's this issue lies with?? any thoughts??

**Comment by ben-rogerson** [comment]
It doe seem like the same issue is happening here. 
Let's close this one and move the discussion to https://github.com/ben-rogerson/twin.macro/issues/30
