### ISSUE TITLE
Goober preset does not work

### ISSUE THREAD

**Issue by justicecurcian** [ben-rogerson/twin.macro#183]
#### The problem

I expect goober preset to work out of the box, but it does not.

Am I missing something or just no one tested twin.macro + goober?

```jsx
//throws `_goober.styled.div is not a function`
const Wrapper = tw.div`text-green-600`

//throws `u is not a function`  error when component is used
const Wrapper = tw('div')`text-green-600`

// both produces unstyled <div css="[object Object]">
<div css={tw`text-green-600`}></div>
<div css={tw`text-green-600`}></div>
```

#### Bug reproduction

https://codesandbox.io/s/vibrant-noether-tz429?file=/src/App.js

**Comment by ben-rogerson** [comment]
Hey, thanks for making that demo.
I've been meaning to provide some docs around Goober support.

Using Goober with Twin gives you the ability to make styled components but doesn't match the features of emotion / styled-components.

With `{ preset: 'goober' }`:

**✓ Supported**
- The `styled` import: `styled('div')` < Must be this format
- The `css` import: `css`` `

**✗ Unsupported**
- The `tw` import: `tw.div`` `
 - The tw prop: `tw=""`
 - The css prop: `css={}`

[Check out the goober demo](https://codesandbox.io/s/goober-test-q6b09?file=/src/App.js)

**Comment by justicecurcian** [comment]
Thanks for your fast reply and good explanation on goober support in twin. It's a shame that it lacks all those features.
And, in my opinion, it's wierd that goober transform does not transpiles `styled.div` into `styled('div')`.
Will goober support be improved in later versions of twin?

**Comment by ben-rogerson** [comment]
Goober does have a [babel plugin](https://www.npmjs.com/package/babel-plugin-transform-goober) that transforms `styled.div` but I had no luck using it with the object spread styles in [the demo](https://codesandbox.io/s/goober-test-q6b09?file=/src/index.js:679-898).

I'm aiming for better support for sure but I much of it depends on the features Goober decides to add.
