### ISSUE TITLE
Emotion version 11 + Twin issues

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#184]
There are some issues with the next major emotion version around imports.

See the workaround below.

**Comment by nghiepit** [comment]
`Emotion 11.0.0` has been released and renamed to `@emotion/react` instead of `@emotion/core`.
Any twin updates yet?

**Comment by ben-rogerson** [comment]
Emotion moved from `@emotion/core` to `@emotion/react` so here's the upgrade instructions while we wait for the twin import presets to catch up:

```bash
npm install @emotion/react@11 @emotion/styled@11
# yarn add @emotion/react@11 @emotion/styled@11

# and remove core as it's unused now:

npm rm @emotion/core
# yarn remove @emotion/core
```

Then add these imports to your twin config:

```js
// package.json
{
  "babelMacros": {
    "twin": {
      "styled": {
        "import": "default",
        "from": "@emotion/styled"
      },
      "css": {
        "import": "css",
        "from": "@emotion/react"
      },
      "global": {
        "import": "Global",
        "from": "@emotion/react"
      },
    }
  },
}

// or babel-plugin-macros.config.js
module.exports = {
  twin: {
    styled: {
      import: 'default',
      from: '@emotion/styled'
    },
    css: {
      import: 'css',
      from: '@emotion/react'
    },
    global: {
      import: 'Global',
      from: '@emotion/react'
    }
  }
}
```

Note: Make sure there's no `preset` in the twin config - that setting will override these custom imports.

---

### For `@emotion/babel-plugin-jsx-pragmatic` users

Also if you're using `@emotion/babel-plugin-jsx-pragmatic` to get around the jsx pragma, you'll need to update the imports to use the new react package too:

```js
// .babelrc
{
  "plugins": [
    "babel-plugin-macros",
    [
      "@emotion/babel-plugin-jsx-pragmatic",
      {
        "export": "jsx",
        "import": "__cssprop",
        "module": "@emotion/react"
      }
    ],
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "__cssprop",
        "pragmaFrag": "React.Fragment"
      }
    ]
  ]
}
```

---  
I'll update the `emotion` preset to use these new imports when Twin v2 rolls out.

**Comment by soilSpoon** [comment]
@ben-rogerson how to use `tw` prop without `import "twin.macro"` on [Emotion 11](https://emotion.sh/docs/emotion-11) and [Nextjs 10](https://nextjs.org/blog/next-10)?

**Comment by ben-rogerson** [comment]
hey @soilSpoon, babel-plugin-macros like Twin need an import to work, there was some [discussion](https://github.com/ben-rogerson/twin.macro/discussions/182) about this a few days ago.

**Comment by mhaagens** [comment]
Possibly related, i'm getting `Can't resolve '@emotion/core` every time I try to use `<GlobalStyle />` with Next.js.

**Comment by soilSpoon** [comment]
## For `Typescript` users
To fix this, create a twin.d.ts file in your project root (src/twin.d.ts with create-react-app) and add these declarations:
```ts
// twin.d.ts
/// <reference types="twin.macro"/>
/// <reference types="@emotion/react/types/css-prop" />
```
Then add the following in tsconfig.json:
```js
// tsconfig.json
{
  "files": ["twin.d.ts"],
  // or
  // "include": ["twin.d.ts"],
}
```

**Comment by soilSpoon** [comment]
> Possibly related, i'm getting `Can't resolve '@emotion/core` every time I try to use `<GlobalStyle />` with Next.js.
> I'm trying to use Styled Components, not emotion, this is my config;
> 
> ```
> module.exports = {
>   twin: {
>     config: 'tailwind.config.js',
>     preset: 'styled-components',
>     debugProp: true,
>     debugPlugins: false,
>     debug: false,
>   },
> }
> ```
@mhaagens 
Do you enable babel-macros?
[Reference](https://github.com/ben-rogerson/twin.macro/blob/master/docs/styled-components/next.md#2-enable-babel-macros-and-configure-styled-components)

**Comment by ben-rogerson** [comment]
> Possibly related, i'm getting `Can't resolve '@emotion/core` every time I try to use `<GlobalStyle />` with Next.js.
> I'm trying to use Styled Components, not emotion, this is my config;
> 
> ```
> module.exports = {
>   twin: {
>     config: 'tailwind.config.js',
>     preset: 'styled-components',
>     debugProp: true,
>     debugPlugins: false,
>     debug: false,
>   },
> }
> ```

I think your twin config isn't being picked up and so it's falling back on the defaults (`@emotion/core`). Perhaps you could [compare your setup against the demo](https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-m1f6d?file=/components/Button.js).

**Comment by onceLearner** [comment]
> Emotion moved from `@emotion/core` to `@emotion/react` so here's the upgrade instructions while we wait for the twin import presets to catch up:
> 
> ```shell
> npm install @emotion/react@11 @emotion/styled@11
> # yarn add @emotion/react@11 @emotion/styled@11
> 
> # and remove core as it's unused now:
> 
> npm rm @emotion/core
> # yarn remove @emotion/core
> ```
> 
> Then add these imports to your twin config:
> 
> ```js
> // package.json
> {
>   "babelMacros": {
>     "twin": {
>       "styled": {
>         "import": "default",
>         "from": "@emotion/styled"
>       },
>       "css": {
>         "import": "css",
>         "from": "@emotion/react"
>       },
>       "global": {
>         "import": "Global",
>         "from": "@emotion/react"
>       },
>     }
>   },
> }
> 
> // or babel-plugin-macros.config.js
> module.exports = {
>   twin: {
>     styled: {
>       import: 'default',
>       from: '@emotion/styled'
>     },
>     css: {
>       import: 'css',
>       from: '@emotion/react'
>     },
>     global: {
>       import: 'Global',
>       from: '@emotion/react'
>     }
>   }
> }
> ```
> 
> Note: Make sure there's no `preset` in the twin config - that setting will override these custom imports.
> 
> ### For `@emotion/babel-plugin-jsx-pragmatic` users
> Also if you're using `@emotion/babel-plugin-jsx-pragmatic` to get around the jsx pragma, you'll need to update the imports to use the new react package too:
> 
> ```js
> // .babelrc
> {
>   "plugins": [
>     "babel-plugin-macros",
>     [
>       "@emotion/babel-plugin-jsx-pragmatic",
>       {
>         "export": "jsx",
>         "import": "__cssprop",
>         "module": "@emotion/react"
>       }
>     ],
>     [
>       "@babel/plugin-transform-react-jsx",
>       {
>         "pragma": "__cssprop",
>         "pragmaFrag": "React.Fragment"
>       }
>     ]
>   ]
> }
> ```
> 
> I'll update the `emotion` preset to use these new imports when Twin v2 rolls out.

thanks man !  I spent two hours figuring out why I have the issue even though I followed the docs for NextJs Emotion .

**Comment by ben-rogerson** [comment]
I've updated the default preset in v2 to use `@emotion/react` so you can remove the custom imports and rely on that now 👍

**Comment by scottyeung** [comment]
@ben-rogerson Can I know what's the right setting for styled-components?

**Comment by ben-rogerson** [comment]
> @ben-rogerson Can I know what's the right setting for styled-components?

@scottyeung `preset: 'styled-components'` with no custom imports + styled-components@5.1.1
