### ISSUE TITLE
Show all not found classes at once

### ISSUE THREAD

**Issue by kingdaro** [ben-rogerson/twin.macro#19]
I change my tailwind config classes every now and then (maybe more than I should 😅), and the not-found errors help a ton already, but it'd be even nicer if the plugin could print all of the invalid class errors at once, instead of me having to go through the rhythm of saving and waiting for the next one.

**Comment by ben-rogerson** [comment]
I'd prefer to show an error at a time as I think it's easier to focus on a single task rather than multiple.
Keen to hear some more views on this.

**Comment by kingdaro** [comment]
I see "fix all of the invalid classes" as a single task, though. ¯\\\_(ツ)\_/¯

**Comment by ben-rogerson** [comment]
haha I see what you mean. I've got 'finish website' as a single task too.
