### ISSUE TITLE
Tailwind v2 support

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#190]
**Update:** 
Now that we're through these Tailwind changes, [I'm now making some tweaks to twin](https://github.com/ben-rogerson/twin.macro/discussions/170) before it also receives a version 2.
If all goes smoothly, you can expect a twin.macro v2 this weekend (around 2nd Dec) 🎉

---

Tailwind has released a bunch of [new or updated features](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.0.0) that Twin needs to catch up with.

I'll be making [some other changes](https://github.com/ben-rogerson/twin.macro/discussions/170) at the same time and we'll have a Twin v2 release by the end of it 🥳 

I've bagged some of the more difficult updates but if you want to help out with a PR, just sing out and I'll reserve the update for you.

## Easy

- [x] [Add transform-gpu to force hardware acceleration on transforms when desired](https://github.com/tailwindlabs/tailwindcss/pull/1380)
Thanks soilSpoon (#200)

- [x] [Add `overflow-ellipsis` and `overflow-clip` utilities](https://github.com/tailwindlabs/tailwindcss/pull/1289) ([Docs](https://tailwindcss.com/docs/text-overflow))
Thanks alessbell (#202)

- [x] [Namespace all internal custom properties under tw- to avoid collisions with end-user custom properties](https://github.com/tailwindlabs/tailwindcss/pull/2771)
Ben did this (#201)

- [x] [Rename `whitespace-no-wrap` to `whitespace-nowrap`](https://github.com/tailwindlabs/tailwindcss/pull/2664)
[Rename `flex-no-wrap` to `flex-nowrap`](https://github.com/tailwindlabs/tailwindcss/pull/2676)
Thanks Crisis2010 (#195)

- [x] [Remove `clearfix` utility](https://github.com/tailwindlabs/tailwindcss/pull/2766)
Thanks Crisis2010 (#193)

- [x] [Remove `scrolling-touch` and `scrolling-auto` utilities](https://github.com/tailwindlabs/tailwindcss/pull/2573)
Thanks Crisis2010 (#194) 

- [x] [Use `[hidden]` elements within `space-` and `divide-` utilities instead of `template` elements](https://github.com/tailwindlabs/tailwindcss/pull/2642)
Thanks Crisis2010 (#196) 

- [x] [Change special use of 'default' in config to 'DEFAULT'](https://github.com/tailwindlabs/tailwindcss/pull/2580)
Ben did this ([8abbd36](https://github.com/ben-rogerson/twin.macro/commit/8abbd36d9154f2af80f8ba8bd4c516b18f8b4e40))

- [x] [Rename `dark` to `darkMode` in tailwind.config](https://github.com/tailwindlabs/tailwindcss/pull/2631)
Ben did this ([d3113de](https://github.com/ben-rogerson/twin.macro/commit/d3113de5d9a142af5a4e193d8fac7d83205b3f70))

- [x] [Extend default spacing scale](https://github.com/tailwindlabs/tailwindcss/pull/2630)
Tests need to be added for the new/updated config items like `spacing`, `inset`, `height`, `grid`, `fontSize`, `screen`, `maxWidth`, `opacity` etc
Ben did this ([caf91fe](https://github.com/ben-rogerson/twin.macro/commit/caf91fe4fd079475a980738bb3dae9e7268f8385))

## Over easy 🍳 

- [x] [Remove shadow-outline, shadow-solid, and shadow-xs by default in favor of new ring API](https://github.com/tailwindlabs/tailwindcss/pull/2747)
Ben did this ([caf91fe](https://github.com/ben-rogerson/twin.macro/commit/caf91fe4fd079475a980738bb3dae9e7268f8385))

- [x] [Added new ring utilities for creating outline/focus rings using box shadows](https://github.com/tailwindlabs/tailwindcss/pull/2747) (+[879f088](https://github.com/tailwindlabs/tailwindcss/commit/879f088))
Ben did this (#204)

- [x] [Make theme retrieve the expected resolved value when theme value is complex
Support defining theme values using arrays for CSS properties that support comma separated values](https://github.com/tailwindlabs/tailwindcss/commit/e13f083c4bc48bf9870d27c966136a9584943127)
Ben's did this (#205)

- [x] [Add support for default duration and timing function values whenever enabling transitions](https://github.com/tailwindlabs/tailwindcss/pull/2755)
Ben did this (#199)

If you need to reference the new output, you can check the [tailwindcss v2 output](https://unpkg.com/tailwindcss@2.0.1/dist/tailwind.css) here (large file warning).

**Comment by alessbell** [comment]
👋 Thanks for your work on this! I should have time to pick up a task or two once they're split out.

**Comment by eddiewang** [comment]
same here! working deeply with the twin.macro library so happy to help out if there's low hanging fruit.

**Comment by ben-rogerson** [comment]
I've now updated the task list, let me know if you want to bag any of the tasks.

**Comment by michaelpanik** [comment]
Hey @ben-rogerson I use twin.macro daily now, would love to contribute on some of these.

**Comment by ben-rogerson** [comment]
> Hey @ben-rogerson I use twin.macro daily now, would love to contribute on some of these.

Great to hear that!
Looks like there are two baggable features left at the top.

**Comment by pix2D** [comment]
I have nothing to add to this particular issue, but I just wanted to take a moment to thank you for all your hard work @ben-rogerson. This library is truly enjoyable to use. Rock on. 🥇

**Comment by ayox** [comment]
Thank you @ben-rogerson for your amazing work, I have been enjoying myself building stuff using this library.

**Comment by ben-rogerson** [comment]
Thanks to everyone that helped out with the updates + sponsoring me too @pix2D 

I'm now making some tweaks to twin before it also receives a version 2.
If all goes smoothly, you can expect a twin.macro v2 this weekend (around 2nd Dec) 🎉

**Comment by dananw** [comment]
Thank you @ben-rogerson I can't wait for it.

**Comment by hansfpc** [comment]
Ty @ben-rogerson ! 
Can't wait for it 😎

**Comment by sebastianfast** [comment]
Thanks!

**Comment by alexperronnet** [comment]
_(just for participants receive a notification)_

Twin v2 is out! https://github.com/ben-rogerson/twin.macro/releases/tag/2.0.0

**Comment by ben-rogerson** [comment]
Thanks again to everyone who helped out with the release, if you'd like to help out next time around I'll be doing the same thing here. Just monitor the issues to snag one for yourself.
Thanks!
