### ISSUE TITLE
twin.macro: Invalid or unexpected token

### ISSUE THREAD

**Issue by axe312ger** [ben-rogerson/twin.macro#2]
Hey Ben,

thank you for your work. I was really looking forward to get tailwind working with emotion :)

My code was working quiet ok with tailwind.macro, I moved on to twin.macro and now end up with:

```
header.js: twin.macro: Invalid or unexpected token Learn more: https://www.npmjs.com/package/twin.macro
```

As soon I import the macro this error happens, I dont have to actually call it.

Unfortunately the error message does not tell me a lot about what and where sth went wrong :(

Related PR with my migration commit: https://github.com/axe312ger/gatsby-mdx-suite/pull/28

Any ideas?

Thanks again,
Benedikt

**Comment by ben-rogerson** [comment]
Hey Benedikt, 
Many thanks for the bug report, I'll troubleshoot and get back to you 👍

**Comment by ben-rogerson** [comment]
I wasn't able to replicate the issue and I haven't seen that error anywhere during testing.

**Comment by axe312ger** [comment]
Alright, ill try to encapsulate a simple project that raises the same issue

**Comment by axe312ger** [comment]
Could replicate my project setup with twin, but I do not run into this error as well. It has to be something I dont cover in my test repo, maybe lerna. I'll dig deeper. For now:

https://github.com/axe312ger/gatsby-starter-theme-ui-emotion-tailwind

**Comment by ben-rogerson** [comment]
Thanks for your report, hopefully you can get it all sorted. Sweet starter you got there too 👌

**Comment by axe312ger** [comment]
Thanks, was just a test. Works fine except some issues with theme-ui -> tailwind config conversion. But we gonna fix this over there 💪 

So far my second try to implement twin in my project does work seamlessly. I don't run into that bug anymore, even with lerna etc.

https://github.com/axe312ger/gatsby-mdx-suite/pull/49

For now I guess the original error might be related to some weird dependency hick-up as I tried to implement tailwind.macro in several different ways before and then switched to twin

**Comment by ben-rogerson** [comment]
ok I'll close this for now, feel free to reopen if you come across it again
