### ISSUE TITLE
Can't resolve @emotion/core

### ISSUE THREAD

**Issue by johnhayesio** [ben-rogerson/twin.macro#203]
When importing css from twin.macro, I am getting can't resolve @emotion/core. I am using Next.js with the @emotion/react variant and also Tailwind 2. I'm not sure what the conflict is. In order to use the css tag, I have to import it from @emotion/react instead of twin.macro.

**Comment by ben-rogerson** [comment]
Hey John, this is due to the changes made in emotion@11, check [this post](https://github.com/ben-rogerson/twin.macro/issues/184#issuecomment-725810203) for the fix.

Twin v2 will update the default import to use the ones provided from `@emotion/react`.

**Comment by johnhayesio** [comment]
Thanks, @ben-rogerson! That worked and fixed everything! Appreciate everything!
