### ISSUE TITLE
2xl variant was not found

### ISSUE THREAD

**Issue by neilnahid** [ben-rogerson/twin.macro#213]
1. the new screen size variant for tailwind v2 called "2xl" was not found
2. Should be able to find the 2xl variant
3. using styled-components
4. https://codesandbox.io/s/next-styled-components-tailwind-twin-starter-forked-37491?file=/pages/index.js

**Comment by ben-rogerson** [comment]
Thanks so much for the excellent bug report.

I've now fixed the issue in 2.0.2 👍

**Comment by neilnahid** [comment]
No problem! Happy to help 😅
