### ISSUE TITLE
Add support for @tailwindcss/forms plugin

### ISSUE THREAD

**Issue by anark** [ben-rogerson/twin.macro#225]
As of tailwind 2.0, tailwind has dropped the tailwindui plugin in favour of 3 1st party plugins(https://tailwindui.com/documentation)

```
All of the examples in Tailwind UI rely on the default Tailwind CSS v2.0 configuration, but some rely on additional first-party plugins like @tailwindcss/forms, @tailwindcss/typography, and @tailwindcss/aspect-ratio.
```

It looks like https://github.com/tailwindlabs/tailwindcss-forms works by adding additional css resets for form elements, however when using twin and GlobalStyles these do not seem to be applied as the plugin uses `addBase` to add these changes.

**Comment by KenLee-Meek** [comment]
i found this.

If you are using @tailwindcss/custom-forms, you will want to migrate to @tailwindcss/forms which replaces it. Learn more about the new forms plugin in the release notes.

The @tailwindcss/custom-forms plugin is not compatible with Tailwind CSS v2.0.

[update-typography-and-forms-plugins](https://tailwindcss.com/docs/upgrading-to-v2#update-typography-and-forms-plugins)

**Comment by rodolphoasb** [comment]
Yeah, @anark is right. 

I migrated to `@tailwindcss/forms` but i'm not able to add custom style to checkbox inputs for example...

**Comment by ben-rogerson** [comment]
Good news, I'm feeling pretty positive I can add support for `addBase`.

**Comment by ben-rogerson** [comment]
Just a quite update, twin will soon have support for plugins using addBase, just some testing and tweaking before it's released 👍

**Comment by ben-rogerson** [comment]
Twin now has support for `@tailwindcss/forms` and also any plugin that uses `addBase` 🎉 
Upgrade to `twin.macro@2.0.6` to give it a whirl.

```js
npm install @tailwindcss/forms
yarn add @tailwindcss/forms
```

PS: Now twin only has one function to cover before gaining full plugin support - `addVariants`!

**Comment by migueloller** [comment]
@ben-rogerson, is adding `addVariants` support possible? If someone wanted to contribute that, do you have any info on where it would be best to start?

**Comment by ben-rogerson** [comment]
I've just started [a discussion on the missing addVariant feature](https://github.com/ben-rogerson/twin.macro/discussions/320) - keen to hear your thoughts on it.
