### ISSUE TITLE
GlobalStyles import results in error

### ISSUE THREAD

**Issue by snaerth** [ben-rogerson/twin.macro#230]
**BUG**
After updating to version 2.04 I get an error when I try to use GlobalStyles
![image](https://user-images.githubusercontent.com/8678089/100789983-1cf67600-340f-11eb-8ff2-823fff366288.png)

**The error**
![image](https://user-images.githubusercontent.com/8678089/100790097-41eae900-340f-11eb-99c3-cd0c44ed7316.png)

  2. What should be happening instead
The default styles should load
  3. If you're using styled-components, emotion, or something else
I am using styled-components

**Comment by snaerth** [comment]
I have tried cleaning node_modules so it is not that

**Comment by snaerth** [comment]
Never-mind I did not install tailwindcss

**Comment by ben-rogerson** [comment]
@snaerth Yes, that's the fix for now - did you install using Yarn or Npm? I'm troubleshooting this issue.

**Comment by george-dotdev** [comment]
@ben-rogerson  I experienced the same issue using Yarn.

**Comment by snaerth** [comment]
@ben-rogerson I used yarn
