### ISSUE TITLE
Tailwind animation not working, missing @keyframes animaition

### ISSUE THREAD

**Issue by Crisis2010** [ben-rogerson/twin.macro#232]
Hello!

[Animations utilities](https://tailwindcss.com/docs/animation) seems to be broken, tried `animate-pulse` and `animate-pulse` inline and in styled-components, but there is no any animation effects.

On element `animation: pulse 2s cubic-bezier(0.4,0,0.6,1) infinite` is exist, but in header `<style></style>` can't find `@keyframes pulse`

React 17.0.1
Twin.macro 2.0.4
Styled-components 5.1.4

**Comment by ben-rogerson** [comment]
The [keyframes are added via `<GlobalStyles />`](https://github.com/ben-rogerson/twin.examples/tree/master/react-styled-components#3-add-the-global-styles) - has that been added to your project?

**Comment by Crisis2010** [comment]
My mistake, forgot to import...
