### ISSUE TITLE
use of css attributes results in css="[object Object]"

### ISSUE THREAD

**Issue by aaronshaf** [ben-rogerson/twin.macro#238]
`import "twin.macro";`

`tw="border-2 border-red-400"`

Results in:

![image](https://user-images.githubusercontent.com/122654/101176199-c73aed00-360b-11eb-9190-ffc6dbf25db8.png)

**Comment by ben-rogerson** [comment]
I think by the sounds of things you worked this out already, but for anyone else stumbling across this it's because the css prop isn't enabled.

Take a look at the examples which show how to set it up.

Cheers!

**Comment by Xairoo** [comment]
A bit more detailed... how to enable `css` prop in react (https://emotion.sh/docs/css-prop)!

I use `craco` with `create-react-app` to modify webpack, babel, ...

Just install `@emotion/babel-preset-css-prop` and add it to your `craco.config.js`:
```
module.exports = {
	babel: {
		presets: ['@emotion/babel-preset-css-prop'],
		plugins: [],
		loaderOptions: {
			/* Any babel-loader configuration options: https://github.com/babel/babel-loader. */
		},
		loaderOptions: (babelLoaderOptions, { env, paths }) => {
			return babelLoaderOptions;
		},
	],
};

```

Thanks for `twin.macro`!

**Comment by tballast** [comment]
@ben-rogerson I'm stumbling across it right now, however I'm not exactly sure which examples you mean!

**Comment by tballast** [comment]
Got it. For anyone else who stumbles upon this here's how I did it. 

First, use a custom .babelrc file like this:
https://www.gatsbyjs.com/docs/how-to/custom-configuration/babel/

then, import the `"@emotion/babel-preset-css-prop"` preset. 

1. `npm install --save-dev babel-preset-gatsby`
2. Create a .babelrc in the root of your project, and add the following: 
```
{
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": [">0.25%", "not dead"]
        }
      }
    ],
    "@emotion/babel-preset-css-prop"
  ]
}

```

**Comment by ben-rogerson** [comment]
@tballast Great you got that working.

Did you try [gatsby-plugin-emotion](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-emotion)? The plugin also uses [@emotion/babel-preset-css-prop](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/src/gatsby-node.js#L3).

**Comment by ben-rogerson** [comment]
If you want something to compare your setup with, I've got [an example using gatsby-plugin-emotion and the css prop](https://github.com/ben-rogerson/twin.examples/blob/master/gatsby-emotion/src/pages/index.js#L15).
