### ISSUE TITLE
DEFAULT values in tailwind config for containers not being applied

### ISSUE THREAD

**Issue by phil-scott-78** [ben-rogerson/twin.macro#239]
With a tailwind 2 config that looks like this

``` js
module.exports = {
    purge: ['./pages/**/*.js', './components/**/*.js'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1rem',
                sm: '2rem',
                lg: '4rem',
                xl: '5rem',
                '2xl': '6rem',
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};

```

and a component that looks like

``` js
const Container = styled.div`
    ${tw`container`}
`;
```

the padding values get set for everything but the default.

padding set with breakpoints

![image](https://user-images.githubusercontent.com/2447331/101232762-a614e380-3681-11eb-8402-c3780c92592c.png)

padding not set for default

![image](https://user-images.githubusercontent.com/2447331/101232787-c5ac0c00-3681-11eb-90f6-009cce451920.png)

Here's a quick repo
https://github.com/phil-scott-78/styled-comp-default-bug-repo

**Comment by ben-rogerson** [comment]
Thanks for the great bug report here.
I've added a fix and I'll let you know when it goes live 👍

**Comment by ben-rogerson** [comment]
Twin now has support for the DEFAULT value in the container config in 2.0.5 🎉
