### ISSUE TITLE
Compile error when calling getUserPluginRules on Tailwind aspect-ratio plugin

### ISSUE THREAD

**Issue by bennettrogers** [ben-rogerson/twin.macro#240]
I'm not sure if this is technically a bug with twin.macro or the Tailwind [aspect ratio plugin](https://github.com/tailwindlabs/tailwindcss-aspect-ratio), but a compile error is thrown when using that plugin with twin.macro. The error says `Cannot read property 'split' of undefined`.

The error is thrown [here](https://github.com/ben-rogerson/twin.macro/blob/ab30b6cc97f51a8cfbc486618dcf521d8c6fb100/src/utils/getUserPluginData.js#L64).

It looks like in this particular Tailwind plugin, `selector` is undefined on the rules so trying to call `split` on the selector throws the error. A few lines up twin.macro is checking for `selector === null`, so maybe the solution is a simple as also checking for `undefined`?

**Comment by dpovey** [comment]
Yeah I also encountered the same issue.  You can see that this method above:

```
var parseSelector = function (selector) {
  if (!selector) { return; }
  var matches = selector.trim().match(/^(\S+)(\s+.*?)?$/);
  if (matches === null) { return; }
  return matches[0].replace(/\./g, '');
};
```

Has several cases where it will return undefined.  By changing the second line here:

```
 var selector = parseSelector(rule.selector); // Rule isn't formatted correctly

  if (selector === null) { return null; }
```

to:
```
if (!selector) { return null; } 
```

It at least compiles. Whether this still means that the aspect ratio plugin is broken I'm not sure, but the code does look wrong.

**Comment by ben-rogerson** [comment]
Thanks for raising this issue.
I'll take a better look into plugin support shortly as there's a couple of popular plugins that were updated for tailwindcss@2 that now that need some attention.

**Comment by ben-rogerson** [comment]
Twin now has support for the aspect-ratio plugin in 2.0.5 👍
