### ISSUE TITLE
Error "Identifier '_styled' has already been declared" with styled-components + ts + next.js

### ISSUE THREAD

**Issue by lopezjurip** [ben-rogerson/twin.macro#241]
Looks like the compiler duplicates the import statement of `styled-components` with the one created by the babel macro when mixing `<div tw="..." />` usage with <code>tw.div``</code>.

This happens when using:
* twin.macro
* Nextjs
* styled-components
* Typescript

Error:
```
Module parse failed: Identifier '_styled' has already been declared (3:7)
File was processed with these loaders:
 * ./node_modules/@next/react-refresh-utils/loader.js
 * ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
You may need an additional loader to handle the result of these loaders.
| import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
| import _styled from "styled-components";
> import _styled from "styled-components";
```

To reproduce:
* With error: https://github.com/lopezjurip/twin.macro-nextjs-styled-ts-error
* With commented lines to make it work: https://github.com/lopezjurip/twin.macro-nextjs-styled-ts-error/commit/507900c0e295bab5a5408cd8e98fbaffdda2ccf8

Maybe this is related to https://github.com/ben-rogerson/twin.macro/issues/192?

**Comment by ben-rogerson** [comment]
Thanks for posting this error, I've identified the issue and currently chasing it up. 

The workaround for now is to downgrade `babel-plugin-macros` to v2.8.0.

**Comment by ben-rogerson** [comment]
A [PR has been opened to fix the issue](https://github.com/kentcdodds/babel-plugin-macros/pull/165), Kent has very limited bandwidth these days but hopefully he can patch it soon 🤞

**Comment by ben-rogerson** [comment]
This was fixed in the new babel-plugin-macros patch 🎉 

![image](https://user-images.githubusercontent.com/21288568/102539376-865bd180-40fd-11eb-8cc2-c6ea8ca919f6.png)

**Comment by coffee-cup** [comment]
I am seeing a similar issue after upgrading to the latest twin.macro (2.6.1) from 2.3.3.

I am using

- twin.macro@2.6.1
- next@11.0.1
- styled-components@5.1.0
- typescript@4.3.4

![image](https://user-images.githubusercontent.com/3044853/124523380-bf167c00-ddab-11eb-8a35-bd82f1bece8e.png)

Any idea why it might be happening or any configuration changes I can make to fix it?

**Comment by ben-rogerson** [comment]
@coffee-cup Have you got some code I can take a look at?

**Comment by yy921010** [comment]
@coffee-cup @ben-rogerson I am seeing a similar issue , on next@11.0.1, twin.macro@2.6.1

**Comment by yy921010** [comment]
> @coffee-cup Have you got some code I can take a look at? What code creates this error?

https://codesandbox.io/s/elegant-bassi-twx91?file=/components/two.js 

You can see this example; when using tw.div, there will be an error; when you enter the command `yarn run dev -p 8080` in the console, the error will appear

**Comment by jeremyzilar** [comment]
I too am seeing this error:
- NEXT `10.0.5`
- twin.macro `2.6.1`
- styled-components `5.3.0`
- typescript `4.2.4`
- tailwind `2.2.4`

**Comment by jeremyzilar** [comment]
Rolling back to `"twin.macro": "2.5.0",` for the time being seems to fix it.

**Comment by yy921010** [comment]
> Rolling back to `"twin.macro": "2.5.0",` for the time being seems to fix it. 

I tried the 2.5.0 version, no errors, but this version 2.6.1 can still report errors

**Comment by ben-rogerson** [comment]
I see the error in the attached example (thanks @yy921010), I've had issues replicating the issue outside of next.js but I'll keep at it and release a patch once fixed.

**Comment by ben-rogerson** [comment]
Okay, a patch is up in twin.macro@2.6.2 👍

**Comment by jeremyzilar** [comment]
This works now in `2.6.2`, thank you @ben-rogerson 🚀

**Comment by isabirahmed** [comment]
I'm still facing this issue,
 "babel-plugin-macros": "3.1.0",
 "tailwindcss": "^2.2.11",
 "twin.macro": "^2.5.0"/ "2.7.0",
 
 Is there any other resolution, can't get any older versions to work either.

**Comment by ben-rogerson** [comment]
@isabirahmed I haven't seen this error for a while now, could you perhaps put a minimum reproduction together?
