### ISSUE TITLE
TypeScript Types for two Missing in 2.0.4

### ISSUE THREAD

**Issue by femetrie** [ben-rogerson/twin.macro#242]
Just noticed that I’m getting TypeScript errors when using tw=“something” with 2.0.4. Downgrading to 2.0.3 fixes the issues. Perhaps just a botched release? I’m using Yarn 2 and Next JS (following your guide), but since 2.0.3 fixes it I don’t think it’s related.

Also, thanks for the amazing macro!

**Comment by ben-rogerson** [comment]
hey there, the only thing I can think of that caused this was the removal of `@types/react`.

Could you please try installing the types and report back? 

```js
npm i -D @types/react
yarn add @types/react -D
```

**Comment by femetrie** [comment]
Strange, I updated to 2.0.5 today and it’s fine again. I have a feeling it was a caching issue on my side. Sorry for reporting!
