### ISSUE TITLE
Ring not working when only some classes are used

### ISSUE THREAD

**Issue by fvanwijk** [ben-rogerson/twin.macro#249]
When I try to render a ring, the box shadow is not rendered because some default fallback CSS vars are missing.
```html
<button tw="border-2 p-2 ring">XXX</button>
```
![image](https://user-images.githubusercontent.com/963136/101769766-c280a800-3ae7-11eb-83de-4cdec292f5c1.png)

I had to add some default ring styles (`ring-offset-0 ring-offset-transparent ring-inset ring-blue-500`) to make it work;
```html
<button tw="border-2 p-2 ring ring-offset-0 ring-offset-transparent ring-inset ring-blue-500">XXX</button>
```
![image](https://user-images.githubusercontent.com/963136/101769808-d1675a80-3ae7-11eb-937e-ee084e313bb5.png)

Note that creating a ring that has no `inset` is not even possible, because that is done in Tailwind by omitting the class.

Might be related to the fix for #224?

**Comment by ben-rogerson** [comment]
I fixed an issue with a fallback class in the latest patch.

Just testing it now on the latest version - seems like it's working:

```js
<div tw="border-2 p-2 ring">...</div>
```
With twin

![image](https://user-images.githubusercontent.com/21288568/101828180-1e4b3f80-3b81-11eb-904a-7b1c19cf2721.png)

With play.tailwind.com

![image](https://user-images.githubusercontent.com/21288568/101828329-4e92de00-3b81-11eb-8fc7-6c8ab9f7d988.png)

**Comment by fvanwijk** [comment]
You are right. I was still on 2.0.6. I can't keep up with your release cycle ;)
However, after bumping, still no ring styles...

This is what I see on play.tailwindcss.com but not in my app.
![image](https://user-images.githubusercontent.com/963136/101885720-c7eafa80-3b9a-11eb-8805-c80ae436672f.png)

I fixed it by adding the `GlobalStyles` import from twin.macro. This seems to be required, not optional, which I wasn't aware of.
I was still on the old solution with the styled-components import and the keyframes boilerplate :)

Thanks for the quick reply and rubber ducking though.

**Comment by ben-rogerson** [comment]
All good, I can understand the confusion if you've been using twin for a while 👍 

FYI, here's the list of global styles that are now added within `<GlobalStyle />`: 

```js
@keyframes spin {
    to { 
        transform: rotate(360deg);
    }
}
@keyframes ping {
    75%, 100% { 
        transform: scale(2); opacity: 0;
    }
}
@keyframes pulse {
    50% { 
        opacity: .5;
    }
}
@keyframes bounce {
    0%, 100% { 
        transform: translateY(-25%);    animationTimingFunction: cubic-bezier(0.8,0,1,1);
    }
    50% { 
        transform: none; animationTimingFunction: cubic-bezier(0,0,0.2,1);
    }
}
* {
    --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59, 130, 246, 0.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
}
* {
  --tw-shadow: 0 0 #0000;
}
```
