### ISSUE TITLE
Add support for Tailwind `presets`

### ISSUE THREAD

**Issue by r0skar** [ben-rogerson/twin.macro#255]
Tailwind has this handy feature called [presets](https://tailwindcss.com/docs/presets). I have tried to use it in combination with twin.macro (+ styled-components if that matters), but it seems to have no effect.

```js
// tailwind.config.js
module.exports = {
  presets: [
    {
      theme: {
        colors: {
          red: "red",
        },
      },
    },
  ],
  theme: {
    colors: {
      black: "#000000",
      white: "#ffffff",
    },
  },
};
```

Using `bg-red` results in `✕ bg-red was not found`.

**Comment by ben-rogerson** [comment]
Thanks for bringing this up, I'll look into it.
