### ISSUE TITLE
Preflight base styles aren't adding the dynamic styles

### ISSUE THREAD

**Issue by simonsayshf** [ben-rogerson/twin.macro#260]
As title suggests, unable to change the default font family from the tailwind.config.js.

tailwind.config.js
```
module.exports = {
  theme: {
    fontFamily: {
      sans: ['serif'],
    },
    extend: {},
  },
  plugins: [],
}
```

In bare Tailwindcss, setting the theme.fontFamily.sans changes the default font used on the `html` element.
![image](https://user-images.githubusercontent.com/61751476/102267375-cba6b600-3ee7-11eb-996f-6e66e64264a4.png)

See Tailwindcss Play [here](https://play.tailwindcss.com/iIF6AW0xcL).

However, in this [example](https://codesandbox.io/s/misty-thunder-nfd1j?file=/src/App.js), the same config doesn't result in any change to the font family.
![image](https://user-images.githubusercontent.com/61751476/102267551-11fc1500-3ee8-11eb-801b-6db4d1a471c4.png)

Upon inspection of the `html` element it seems to be just the default base css from tailwind, with no user overrides. 

Unclear how any user styles are being applied ontop of the base css import from here: https://github.com/ben-rogerson/twin.macro/blob/master/src/macro/globalStyles.js#L26 

The expected outcome is that changes to the tailwind.config.js using twin.macro would be applied similarly to how it's applied for tailwind normally.

**Comment by ben-rogerson** [comment]
A patch will fix this in the next version
