### ISSUE TITLE
@tailwindcss/typography prose colors not working (prose-xxx)

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#261]
Twin needs a few adjustments to support some generated color classes in the typography plugin.

```
✕ prose-red was not found

Try one of these classes:
table-row / space-x-reverse / space-y-reverse
divide-x-reverse / divide-y-reverse / flex-row-reverse
```
_Originally posted by @pedrohasf in https://github.com/ben-rogerson/twin.macro/issues/108#issuecomment-745609189_

Twin seems to lack support for [classes added in this fashion](https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js#L1072).
Once fixed, twin will add correct styles for the following default classes:

```shell
→ prose-red {}
→ prose-yellow {}
→ prose-green {}
→ prose-blue {}
→ prose-indigo {}
→ prose-purple {}
→ prose-pink {}
```

**Comment by ben-rogerson** [comment]
After testing, I'm seeing these classes generating correctly

```shell
→ prose-red a {"color":"#dc2626"}
→ prose-red a code {"color":"#dc2626"}
→ prose-yellow a {"color":"#d97706"}
→ prose-yellow a code {"color":"#d97706"}
→ prose-green a {"color":"#059669"}
→ prose-green a code {"color":"#059669"}
→ prose-blue a {"color":"#2563eb"}
→ prose-blue a code {"color":"#2563eb"}
→ prose-indigo a {"color":"#4f46e5"}
→ prose-indigo a code {"color":"#4f46e5"}
→ prose-purple a {"color":"#7c3aed"}
→ prose-purple a code {"color":"#7c3aed"}
→ prose-pink a {"color":"#db2777"}
→ prose-pink a code {"color":"#db2777"}
```

with this config

```js
// tailwind.config.js
module.exports = {
  theme: {},
  plugins: [require("@tailwindcss/typography")],
};
```

**Comment by borodean** [comment]
I'm still having this issue with color-related classes (e.g. `prose-red`, `prose-inverse`), but not with the sizing ones (`prose-lg`). It won't find the class.

**Comment by ben-rogerson** [comment]
Just tested on the latest version and generated the classes correctly for `prose-lg`. 
What's your tailwind.config look like?

Tested:

```js
import tw from "twin.macro";

tw`prose-lg`

// ↓ ↓ ↓ ↓ ↓ ↓

({
  "fontSize": "1.125rem",
  "lineHeight": "1.7777778",
  ":where(p):not(:where([class~=\"not-prose\"] *))": {
    "marginTop": "1.3333333em",
    "marginBottom": "1.3333333em"
  },
  ":where(hr):not(:where([class~=\"not-prose\"] *))": {
    "marginTop": "3.1111111em",
    "marginBottom": "3.1111111em"
  },
  // ...
});
```

**Comment by borodean** [comment]
> Just tested on the latest version (`@tailwindcss/typography@0.5.0`) and generated the classes correctly for `prose-lg`.

Could you please try this?

```ts
tw`prose prose-inverse`
```
