### ISSUE TITLE
'css' is not exported from 'styled-components/macro'

### ISSUE THREAD

**Issue by hendrul** [ben-rogerson/twin.macro#264]
import css using twin.macro with styled-components fails. Below is the error when running local in my machine the [cra-styled-component](https://github.com/ben-rogerson/twin.examples/tree/master/cra-styled-components) example. It works on codesandbox, but not local.

```
./src/components/Button.js
Attempted import error: 'css' is not exported from 'styled-components/macro' (imported as '_css').
```

**Comment by audishos** [comment]
> @ben-rogerson thanks a million for the fast response.
> `npm works fine`
> To me It's failing on both yarn or npm

I'm seeing the same. The strangest thing about it is that it works fine in one component, but fails when I try and import into another. Both components are in the same directory.

**Comment by ben-rogerson** [comment]
I've now adjusted the preset in 2.0.8 to remove the macro import, this will avoid this error in CRA now.

**Comment by jeremyzilar** [comment]
FYI, I just tried this with `npm install` and I got the same error
```
'css' is not exported from 'styled-components/macro'
```
So I cleared away the repo, and tried again using `yarn` and everything seems to work.

**Comment by ben-rogerson** [comment]
> FYI, I just tried this with `npm install` and I got the same error
> 
> ```
> 'css' is not exported from 'styled-components/macro'
> ```
> 
> So I cleared away the repo, and tried again using `yarn` and everything seems to work.

Sounds like some caching happening there 🤷‍♂️

**Comment by jonleopard** [comment]
Was anyone able to resolve this? I just ran `npx degit` on the styled-components repo and I'm getting this error on a fresh install.

**Comment by jeremyzilar** [comment]
I think @ben-rogerson is correct. The cache needed to be cleared. I have been blowing away my Next.js folder (`rm -rf .next`) after each edit to my `tailwind.config.js`

**Comment by isaif** [comment]
For me clearing the `.next` directory doesn't work but using `yarn` does.

**Comment by ben-rogerson** [comment]
Nuking your node_modules and npm installing may have fixed it too
