### ISSUE TITLE
css prop with an array of styles strings before tw prop ends with no styling

### ISSUE THREAD

**Issue by hendrul** [ben-rogerson/twin.macro#268]
Look at [src/App.js](https://codesandbox.io/s/css-tw-props-order-o73uf?file=/src/App.js), both headers are styled the same using css and tw props, though only the h1 gets styled correctly, with the only difference being the order css and tw  props are declared.

**Comment by hendrul** [comment]
The issue occur when using arrays of string templates on css prop in front of tw prop
`css={[`color: blue`]}`
but if you change to object style it works
`css={{color: "blue"}}`

**Comment by ben-rogerson** [comment]
styled-components is picky about semi-colons. Just like css you'll need to add them in the css block unless you're using css object syntax.

```diff js
export default function App() {
  return (
    <div className="App">
-     <h1 tw="bg-indigo-300" css={[`color: blue`]}>
+     <h1 tw="bg-indigo-300" css={[`color: blue;`]}>
        Hello CodeSandbox
      </h1>
-     <h2 css={["color: blue"]} tw="bg-indigo-300" >
+     <h2 css={["color: blue;"]} tw="bg-indigo-300" >
        Start editing to see some magic happen!
      </h2>
    </div>
  );
}

```
