### ISSUE TITLE
tw prop is not working without css prop on tsx files

### ISSUE THREAD

**Issue by klaskow** [ben-rogerson/twin.macro#271]
1. The buggy behavior you’re experiencing and what should be happening instead

tw prop is not working on tsx files, styles are not applied but should working

2. If you're using styled-components, emotion, goober, or something else

emotion and gatsby

3. A link to a minimal demo showing the bug in action

https://github.com/ben-rogerson/twin.examples/tree/master/gatsby-emotion

Then rename src/pages/index.js to index.tsx and copy following code

```
import React from 'react'
import tw from 'twin.macro'
import { Layout } from '../components'

const App = () => (
  <Layout>
    <div tw="bg-black text-white">Buttons</div>
  </Layout>
)

export default App
```

What is the most interesting, it starts working immediatly when you just use css prop as you can see on first screenshots. I am not sure this is bug or configuration issue but I can't handle this. 

1) tw prop is working when you use css prop
![tsx_css_and_tw](https://user-images.githubusercontent.com/51476475/102712826-19466880-42c4-11eb-8d36-d9e6d8a5fa8b.png)

2) tw prop is not working properly alone
![tsx_only_tw](https://user-images.githubusercontent.com/51476475/102712827-19466880-42c4-11eb-8870-497ea6fb5c1b.png)

3) tw prop working on js/jsx file extension
![jsx_only_tw](https://user-images.githubusercontent.com/51476475/102712825-18add200-42c4-11eb-8dbc-17d50ace3d52.png)

**Comment by ben-rogerson** [comment]
Hey there

In the second example, the tw must be removed from your import otherwise it gets stripped:

```diff
import React from 'react'
-import tw from 'twin.macro'
+import 'twin.macro'
import { Layout } from '../components'

const App = () => (
  <Layout>
    <div tw="bg-black text-white">Buttons</div>
  </Layout>
)

export default App
```

**Comment by cs50victor** [comment]
> Hey there
> 
> In the second example, the tw must be removed from your import otherwise it gets stripped:
> 
> ```diff
> import React from 'react'
> -import tw from 'twin.macro'
> +import 'twin.macro'
> import { Layout } from '../components'
> 
> const App = () => (
>   <Layout>
>     <div tw="bg-black text-white">Buttons</div>
>   </Layout>
> )
> 
> export default App
> ```

I'm having this issue (I'm using styled-components, react 17, tailwindcss 2.0).
I imported twin macro as instructed -> import "twin.macro"

i.e <a href="somewhere" tw="text-4l **sm:text-xl**"/>
The font remains the same size even on small devices / after the breakpoint.

**Comment by klaskow** [comment]
Oh! It was so obvious. It works. 
Why does it work in js/jsx without that import but it doesn't work in tsx without import? I thought this was a bug but now I think it's not.

**Comment by ben-rogerson** [comment]
It seems to be a TypeScript thing, Ive been bitten by it before also 👍

**Comment by lightyen** [comment]
How about this option?
- tsconfig.json
   ```json
   {
     "compilerOptions": {
       "importsNotUsedAsValues": "preserve"
     }
   }
   ```

**Comment by klaskow** [comment]
I tried but it didn't work in my setup. Anyway I don't think it is a good practice to preserve "importsNotUsedAsValues".
Just simple import solves the issue.
