### ISSUE TITLE
Overriding existing utilities in tailwind.config.js has no effect when using with Next.js

### ISSUE THREAD

**Issue by amrnn90** [ben-rogerson/twin.macro#284]
Hello, 
I'm using twin.macro with emotion and Next.js.
Whenever I make a change inside `tailwind.config.js` that overrides an existing utility, that change is ignored and restarting the server has no effect...the only way to make it work is by deleting the `.next` folder.

### Steps to reproduce:
1. `npx degit https://github.com/ben-rogerson/twin.examples/next-emotion folder-name`
2. `yarn && yarn dev`
3. override an existing utility in `tailwind.config.js`  (must be an existing utility, if it's a new utility things work fine), for example: 
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        red: {
          100: 'black'
        }
      },
    },
  },
  plugins: [],
}
```
4. apply this utility somewhere, for example `<div tw="bg-red-100"></div>`
5. the created div will show the old red instead of the new black
6. restarting the server doesn't work, you have to delete the `.next` folder and run the server again to make it work.

**Comment by ben-rogerson** [comment]
You've hit the [babel caching issue](https://github.com/kentcdodds/babel-plugin-macros#babel-cache-problem), to fix it you'll just need to make a change in your file to force babel to recompile.
This only happens in dev and never in production.

**Comment by drymek** [comment]
In my case, it is not enough to change the file or restart service. I looked for this bug for a while (I thought it was a wrong tailwind configuration) - only removing the `.next` directory works for me. However, I use it everywhere, so I'm not able to easy test it without `twin.macro`

**Comment by amrnn90** [comment]
@drymek 
Yes, that's what happens with me also.
I don't usually override existing utilities anyway, so I'll just remove the `.next` directory for now 😅

**Comment by ben-rogerson** [comment]
Ah yes, it's similar for Gatsby also but it's the .cache dir in that case. If I'm adjusting the config often enough I'll change the dev script to rimraf the dir before starting the dev server.

**Comment by amrnn90** [comment]
@ben-rogerson 
Yes, I think that's the best solution for now...thank you for this excellent project.
