### ISSUE TITLE
Vue + Emotion + Tailwind Starter: babel-preset-css-prop alternative required

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#29]
I've put together a sandbox demo for using twin.macro in Vue and need some help.

I want to use a `css` function so I can write css alongside tw classes in a styled block. 
I've got it working using `@emotion/babel-preset-css-prop` however there's a dependency chain that requires `react` to be installed 😱

 [🔥 Vue + Emotion + Tailwind Starter](https://codesandbox.io/s/vue-emotion-tailwind-starter-2yd61?file=/src/components/Button.vue)

Looking for a little help on how I can remove this React dependency and still use the `css` function.

**Comment by kamontat** [comment]
You might change `css()` to use only `styled()` instead ??

ref: https://codesandbox.io/s/vue-emotion-tailwind-twin-starter-cl1h9

**Comment by ben-rogerson** [comment]
That seems like the best (and only 😆) option right now, thanks!

Worth noting is that because we aren't using the css prop, we need to use backticks to define our styles.
The array method (``styled('div')([`styles`])``) can't be used because that would require the `css` prop which isn't available to Vue like it is to React.  

**👍 Backticks work**
```js
const Wrap = styled('div')`
  * {
    ${tw`mt-6`}
  }
`
```

**👎 Arrays don't**
```js
const Wrap = styled('div')([
  `* {
    ${tw`mt-6`}
  }`
])
```

Hope everyone is okay with this.
I think it's still pretty cool.

Thanks again @kamontat
