### ISSUE TITLE
twin.macro not playing nicely with Next.JS and shared components in a yarn workspaces

### ISSUE THREAD

**Issue by PaddyMann** [ben-rogerson/twin.macro#293]
Our monorepo has both a create-react-app (CRA) and a Next.JS app.

I'm trying to set up a shared components library, and have got it working for the CRA app.

I've also managed to set up Next.JS to load shared components using next-transpile-modules, but I'm having issues when importing {styled} from twin.macro.

With this code... :

```
import tw, {styled} from 'twin.macro';
```

... `styled` is coming out as `undefined`.

I've recreated the issue here: https://github.com/PaddyMann/twin-yarn-workspaces-issue

**Comment by ben-rogerson** [comment]
Thanks for the great issue repo.
I've used Rollup to create a [shared component library](https://github.com/ben-rogerson/twin.examples/tree/master/component-library-styled-components/packages/components) and the trick there was to pre-compile the library before importing it into my project.
I believe what's happening here is that `shared-components` doesn't precompile the library beforehand so when next attempts to use the component, `styled` hasn't been replaced with the css-in-js library import.

**Comment by PaddyMann** [comment]
Thanks for reviewing @ben-rogerson (and epic work on twin btw — amazing to find so much support + examples of making it work with so many other libraries!)

I'm a little unclear on what the next steps are. Is this something I can resolve at my end, or does it need to be addressed either in twin or styled-components? :)

**Comment by PaddyMann** [comment]
I've now got it working with rollup — thank you sir!

**Comment by PaddyMann** [comment]
The rollup solution I've got currently works well with a simple styled component, e.g.:

```
import tw, {styled} from 'twin.macro';

const PageCenter = styled.div((props) => [
  tw`
    flex
    items-center
    justify-center
    h-screen
  `,
]);

export default PageCenter;
```

However, it doesn't seem to support something a little more complex:

```
import React from 'react';
import PropTypes from 'prop-types';
import tw, {styled} from 'twin.macro';

Input.propTypes = {
  icon: PropTypes.func,
};

Input.defaultProps = {
};

function Input (props) {
  const {
    icon,
  } = props;

  return <InputWrapper>
    {icon && icon({size: 24})}
    <TextInput />
  </InputWrapper>;
}

const InputWrapper = styled.div((props) => [
  tw`
    flex
    border
    w-full
    px-3
    pl-2.5
    h-11
    border-gray-300
    text-gray-700
    svg:self-center
    svg:text-gray-400
  `,
]);

const TextInput = styled.input((props) => [
  tw`
    outline-none
    w-full
    ml-2
  `,
]);

export default Input;
```

The error I get is:

```
TypeError: TextInput is not a function
```

In the built module, I can see TextInput is included, but it's wrapped as a styled-components object:

```
;

var TextInput = _styled2.input.withConfig({
  displayName: "Input__TextInput",
  componentId: "sc-15h421e-1"
})(function (props) {
  return [{
    "outline": "2px solid transparent",
    "outlineOffset": "2px",
    "width": "100%",
    "marginLeft": "0.5rem"
  }];
});
```

Any ideas how to resolve this?

**Comment by fvanwijk** [comment]
I would say that `const TextInput` is not hoisted. What about changing the order?

**Comment by PaddyMann** [comment]
Thanks Frank — that thought did occur to me.

Unfortunately tweaking the order, in the built module file, doesn't help.

Here's how TextInput is being called in that built file:

```
function Input(props) {
  var icon = props.icon,
      rest = _objectWithoutProperties(props, ["icon"]);

  return InputWrapper(null, [icon && icon({
    size: 24
  }), TextInput(Object.assign({}, rest))]);
}
```

Unfortunately, TextInput seems to be returned as an object by _styled2.

**Comment by ben-rogerson** [comment]
Hey paddy, how did you go with this?

**Comment by PaddyMann** [comment]
I'm afraid I got stuck at the bit above, and wasn't able to put further time into it. In the short term, I'm back to copy and pasting across components which is a bit of a nightmare.

If you have any suggestions on next steps here, I'd be happy to test them out :)

**Comment by ben-rogerson** [comment]
Yeah that's horrible!

I think the next step might be to verify if it's twin at fault or the underlying css-in-js library (styled-components).
To test if twin is causing the issue you could remove the twin imports (and usage of the tw import) and instead use the raw `styled` import from styled-components

**Comment by ben-rogerson** [comment]
Closing this for now but feel free to reopen with an minimal example repo so I can help out.

**Comment by PaddyMann** [comment]
Apologies — a hundred other priorities have taken me away from this issue. The issue is still outstanding and I expect to come back to it at some point in the coming months :)
