### ISSUE TITLE
framer-motion + styled-components doesn't work with prop styling

### ISSUE THREAD

**Issue by migueloller** [ben-rogerson/twin.macro#296]
## Problem
We ran into this issue when attempting to use Framer Motion with twin.macro. The gist of it is that using the `tw` prop on an element like `motion.div` results in the commonjs transpilation improperly importing the bindings, which causes this error: 
![image](https://user-images.githubusercontent.com/5677929/104781953-731a4100-5751-11eb-987c-de25139b24d3.png)

## Details
Here's what some transpiled output looks like:

```javascript
var _framerMotion = require("framer-motion");

// snip

var _StyledMotionDiv = (0, _styledComponents.default)(motion.div).withConfig({
  displayName: "Dialog___StyledMotionDiv",
  componentId: "sc-1ji47xs-0"
})({
  "position": "absolute",
  "top": "0px",
  "right": "0px",
  "bottom": "0px",
  "left": "0px",
  "pointerEvents": "none",
  "--tw-bg-opacity": "1",
  "backgroundColor": "rgba(0, 0, 0, var(--tw-bg-opacity))"
});
```

Notice that instead of `_framerMotion.motion.div`, the styled component is just called with `motion.div` and since `motion` isn't defined, that results in an error. The code that transpiles to this looks somewhat like this:

```javascript
import { motion } from 'framer-motion'

// snip

  <motion.div tw="absolute inset-0 pointer-events-none bg-black">
```

## Reproduction
This can easily be reproduced by doing the following:

Follow the instructions at https://github.com/ben-rogerson/twin.examples/tree/master/react-styled-components:

```bash
npx degit https://github.com/ben-rogerson/twin.examples/react-styled-components folder-name
cd folder-name
npm install framer-motion
```

And apply the following changes to `src/App.js`:

```diff
 import React from 'react'
 import tw from 'twin.macro'
 import { Button, Logo } from './components'
+import { motion } from 'framer-motion'
 
 const App = () => (
-  <div
+  <motion.div
     css={[
       tw`flex flex-col items-center justify-center h-screen`,
       tw`bg-gradient-to-b from-electric to-ribbon`,
     ]}
   >
-    <div tw="flex flex-col justify-center h-full space-y-5">
+    <motion.div tw="flex flex-col justify-center h-full space-y-5">
       <Button isPrimary>Submit</Button>
       <Button isSecondary>Cancel</Button>
       <Button isSmall>Close</Button>
-    </div>
+    </motion.div>
     <Logo />
-  </div>
+  </motion.div>
 )
 
 export default App
```

Run `npm start` and open the console in the browser and you'll see the error.

**Comment by ben-rogerson** [comment]
When testing this, I had no issues using `yarn`, _but_ I experienced the described error when using `npm` to install the dependencies.
I also had no issues with emotion so this issue seems localised to twin + styled-components + npm.

Here's the workaround I've found:

```js
import React from 'react'
import tw from 'twin.macro'
import { Button, Logo } from './components'
import { motion } from 'framer-motion'

const Motion = tw(motion.div)``

const App = () => (
  <Motion
    as="span"
    css={[
      tw`flex flex-col items-center justify-center h-screen`,
      tw`bg-gradient-to-b from-electric to-ribbon`,
    ]}
  >
    <Motion tw="flex flex-col justify-center h-full space-y-5">
      <Button isPrimary>Submit</Button>
      <Button isSecondary>Cancel</Button>
      <Button isSmall>Close</Button>
    </Motion>
    <Logo />
  </Motion>
)

export default App
```

Note that you can change from a div to another element with the `as` prop.

I'll have to have a better dig into this before I can explain exactly what's happening.

**Comment by migueloller** [comment]
@ben-rogerson, interesting. While the reproduction uses NPM, we ran into this issue in our Yarn workspaces monorepo. And yes, we were able to work around it as well by doing this:

```typescript
const MotionDiv = motion.div

// snip

<MotionDiv tw="..." />
```

In that case, the transpilation properly defined `var MotionDiv = _framerMotion.motion.div`. My uneducated guess here is that the Babel transform is probably just taking what it finds in the JSX call (i.e., `<motion.div>`) and putting it in the styled component (i.e., `styled(motion.div)`) in a way that doesn't consider ES6 -> CommonJS interop changes.

I'd be happy to dig in a bit more and help implement a fix if you could point me in the right direction, specifically where the AST fransformation is happening within the Babel macro implementation.

Thanks!

**Comment by ben-rogerson** [comment]
It doesn't look like this transform is happening in twin or the styled-components macro, so perhaps start at [the styled-components styled entry](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constructors/styled.js).

Tested in twin:

```js
<motion.div tw="flex">hi</motion.div>;

// ↓ ↓ ↓ ↓ ↓ ↓

import _styled from "styled-components";

var _StyledMotionDiv = _styled(motion.div).withConfig({ /* config */ })({
  display: "flex",
});

React.createElement(
  _StyledMotionDiv,
  {
    "data-tw": "flex",
  },
  "hi"
);
```

**Comment by ben-rogerson** [comment]
Here's their [babel macro](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/macro/index.js), it's not doing too much so hopefully you'll find an answer quickly.

**Comment by migueloller** [comment]
Thanks for sharing that @ben-rogerson. I'll take a look soon and see if I find any issues there.

**Comment by ben-rogerson** [comment]
Just took another peek at the output for this in emotion + sc and looks okay - feel free to reopen if not the case
