### ISSUE TITLE
border-t/r/b/l doesn't automatically apply border style

### ISSUE THREAD

**Issue by designbyadrian** [ben-rogerson/twin.macro#3]
```javascript
tw.div`border-b border-black`
```

Should render a div width

```css
border-bottom-width: 1px;
border-bottom-style: solid;
border-colour: #000000;
```

But what I get is

```css
border-bottom-width: 1px;
border-colour: #000000;
```

If, instead, I write:

```javascript
tw.div`border-b border-solid border-black`
```

I get

```css
border-bottom-width: 1px;
border-style: solid;
border-colour: #000000;
```

Which renders a div with 2px border around, and 1px bottom!

---

I don't understand how to write an example with babel macros in CodePen. I'd happily fork one if one exists.

**Comment by designbyadrian** [comment]
My solution now is to write:

```javascript
tw.div`border-0 border-b border-solid border-black`
```

**Comment by ben-rogerson** [comment]
Yeah that's an annoying one - but lucky it's an easy fix, you need to add the tailwind base css.
I've just added an [installation step about the base.css file](https://github.com/ben-rogerson/twin.macro/blob/master/README.md#3-import-the-tailwind-reset) in the readme.

In Tailwind's base css, this is the magic that makes borders work the way you're used to:

```css
/* tailwindcss/dist/base.css */
*,
::before,
::after {
  border-width: 0;
  border-style: solid;
  border-color: #e2e8f0;
}
```

**Comment by designbyadrian** [comment]
@ben-rogerson Thank you! That's a good solution, as we also get basic CSS resets as well 👍
