### ISSUE TITLE
GlobalStyles in Goober

### ISSUE THREAD

**Issue by gerhardsletten** [ben-rogerson/twin.macro#302]
In a project with Preact-cli and Goober I did experience that `GlobalStyles` was not always able to insert all needed styles in ssr extraction, resulting in flicker when the pages loaded. And while inspecting how styles was inserted I did see that Goobers `glob` was used.

```
import { glob as _globalImport } from 'goober'
_globalImport\`
  *,
  *::before,
  *::after {
    box-sizing: border-box;
  }
```
From their docs its say that `createGlobalStyles` should be used over the old `glob`

> Before the global addon, goober/global, there was a method named glob that was part of the main package that would do the same thing, more or less. Having only that method to define global styles usually led to missing global styles from the extracted css, since the pattern did not enforced the evaluation of the styles at render time. The glob method it is still exported from goober/global if you have a hard dependency on it.

[createglobalstyles in goobers readme](https://github.com/cristianbote/goober#createglobalstyles)

**Comment by gerhardsletten** [comment]
@ben-rogerson Let me know if a PS for this will be accepted, and I will fix this.

**Comment by ben-rogerson** [comment]
Thanks for letting me know - sure I'll accept your PR.

You'll need to make some changes [here](https://github.com/ben-rogerson/twin.macro/blob/master/src/macro/globalStyles.js#L174) and [here](https://github.com/ben-rogerson/twin.macro/blob/master/src/config/userPresets.js#L58).

**Comment by gerhardsletten** [comment]
@ben-rogerson Thanks, the PR is ready #303 here
