### ISSUE TITLE
Classes for pseudo-elements are read with full rule as classname

### ISSUE THREAD

**Issue by Cybolic** [ben-rogerson/twin.macro#306]
twin.macro tries to find the literal name of the class from any Tailwind plugin that generated pseudo-element rules.

Setup:
A plugin generates:
```
`.${e(`name-of-class`)}::before`
```
An element uses the class:
```
<div tw="name-of-class" />
```

Result:
twin.macro will error that the class `name-of-class` was not found.
`name-of-class::before` is listed in the output with `debugPlugins: true`

I'm using styled-components.
[Minimal demo here](https://codesandbox.io/s/mystifying-napier-b6qg5?file=/package.json)

**Comment by ben-rogerson** [comment]
Looks like you're using `addUtilities` in your plugin which doesn't support `:before`.
The solution is to switch to `addComponents` - just a replacement will do it.

**Comment by Cybolic** [comment]
Thanks that solves it :) I do think it should work for utilities as well, but maybe I misunderstand the definitions.

**Comment by ben-rogerson** [comment]
You could be right there, might need a couple of tweaks. I'll have to revisit the tailwind implementation.
