### ISSUE TITLE
`css` dom attribute and `styled` is not declared in `index.d.ts`.

### ISSUE THREAD

**Issue by itaysmalia** [ben-rogerson/twin.macro#312]
Hi, I saw that you changed the `css` dom attribute to `cs`, and `styled` is not declared in `index.d.ts`, is that on purpose? I can submit a pr for it, but I don't really know what are you planning 😄 , Amazing job btw!!!

_Originally posted by @itaysmalia in https://github.com/ben-rogerson/twin.macro/discussions/311_

**Comment by ben-rogerson** [comment]
Hey there!

I've added the `cs` prop (and it's types) but it's different to the `css` prop and allows the short css syntax to be written in there. It also works with the css prop, so you can use both props at the same time if you need to.

eg: 

```js
<div cs="md:maxWidth[calc(100vw - 2em)]" css={`color: red;`} />
```

The types for `styled` come from your chosen css-in-js library, if you want to set that up check out one of the example readmes for the setup.

**Comment by ben-rogerson** [comment]
Let's move this back to the discussion so we're not doubling up :)
