### ISSUE TITLE
short CSS doesn't find `transition-property`

### ISSUE THREAD

**Issue by kelvindecosta** [ben-rogerson/twin.macro#322]
## Overview

Hello!

I have run into a minor issue while using the **short CSS syntax**.
[`transition-property`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property) doesn't work.

## Tools

- **Styled Components**
- **Gatsby**

## Behaviour

```jsx
import tw, {styled} from "twin.macro"

const Component = styled.span`
  ${tw`transition-all duration-200 transition-property[margin]`}
`
```

For the above snippet, I get the following error message:

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

<path/to/file/with/error>:

✕ transition-property[margin] was not found
```

I have a temporary workaround:

```diff
import tw, {styled} from "twin.macro"

const Component = styled.span`
-  ${tw`transition-all duration-200 transition-property[margin]`}
+ ${tw`transition-all duration-200`}
+ transition-property: margin;
`
```

## Reproduction

[Link](https://codesandbox.io/s/recursing-raman-ywrzf)

**Comment by ben-rogerson** [comment]
Thanks for letting me know about this and for the great reproduction.

I need to prioritise the matching on short css items as it's trying to match a core plugin here.
Easy fix though - I'll push a patch shortly.

**Comment by ben-rogerson** [comment]
Fixed in twin.macro@2.2.2 🎉

**Comment by kelvindecosta** [comment]
Wow, that was fast! Thanks for the fix!
