### ISSUE TITLE
theme value validation

### ISSUE THREAD

**Issue by lightyen** [ben-rogerson/twin.macro#325]
When i use:
```js
import { theme } from "twin.macro"
console.log(theme`colors.black`)

// Output:
// #000

// Good!
```

But in this case:
```js
import { theme } from "twin.macro"
console.log(theme`colors[][....]....black`)

// Expect:
// error

// Output:
// #000

// Bad.
```

**Comment by ben-rogerson** [comment]
That doesn't sound like the right behaviour! I'll fix that up.

**Comment by ben-rogerson** [comment]
I've swapped to the lodash.get method for this - will be fixed next release.

**Comment by ben-rogerson** [comment]
Fixed in [twin.macro@2.3.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.3.0) 🎉

**Comment by lightyen** [comment]
I still got some weird behaviour in edge case:
```js
import { theme } from "twin.macro"
console.log(theme`fontSize[2xl][0]`)
console.log(theme`fontSize.[2xl].[0]`)

// Except:
//
// 1.5rem
// error!

// Output:
//
// 1.5rem
// 1.5rem
```

**Comment by ben-rogerson** [comment]
Those two cases are a nice feature of lodash.get. 
They're handy in twin if you need to work around some of the [applied rules with certain value types](https://github.com/ben-rogerson/twin.macro/blob/02baa8be3871a6ea1900750406ba9ed7d9a4bb89/src/utils/misc.js#L43).
I'm keen to call those two cases "feature" 😆
