### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by locona** [ben-rogerson/twin.macro#326]
1. The buggy behavior you’re experiencing and what should be happening instead
 
I would like to resolve the following warning.

```
Critical dependency: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
 
twin.macro + emotion is used to create the design system component.
We'll call it `design-system-package`. 

Import the `design-system-package` and run
After importing the `design-system-package` and executing `next `, the

```
warn  - ../use-design-system-package/node_modules/twin.macro/node_modules/babel-plugin-macros/dist/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

../use-design-system-package/node_modules/twin.macro/macro.js
Critical dependency: the request of a dependency is an expression

../use-design-system-package/node_modules/import-fresh/index.js
Critical dependency: the request of a dependency is an expression
```

2. `emotion`

3. A link to a minimal demo showing the bug in action

The following will be the verification environment

https://github.com/locona/use.twin.macro

**Gettings Started**
```
cd packages/use-design-system

yarn install

yarn dev
```

**Comment by ben-rogerson** [comment]
Hey there, thanks for pushing that example repo.

This error pops up because [your design system is using tsc for the build](https://github.com/locona/use.twin.macro/blob/main/packages/design-system/package.json#L14) instead of relying on`@babel/preset-typescript`.

Perhaps take a look at how I'm [building the component library example with rollup](https://github.com/ben-rogerson/twin.examples/blob/master/component-library-styled-components/packages/components/package.json#L20) for some ideas.

**Comment by locona** [comment]
@ben-rogerson 

Thank you!

I did exactly what you told me to do.
It worked fine!

**Comment by elvc** [comment]
@ben-rogerson do you mind reposting your tutorial? The link seems broken. Thanks in advance.

**Comment by ben-rogerson** [comment]
@elvc Twin has two repos showing the component library setup: one with [next + styled-components](https://github.com/ben-rogerson/twin.examples/tree/master/component-library-styled-components) and one with [emotion + rollup](https://github.com/ben-rogerson/twin.examples/tree/master/component-library-emotion)
