### ISSUE TITLE
cssConflict - css property conflict with root element and pseudo elements with the same property

### ISSUE THREAD

**Issue by joeynimu** [ben-rogerson/twin.macro#328]
Hey! This is not really a bug rather than a false warning for conflicting CSS properties I get when I apply styles on the pseudo-elements that have also been applied to the element in question. 

```
<div tw="flex relative flex-col items-center pt-4 pb-2 justify-items-center before:(content absolute top-0 left-0 w-1/2 h-2px) after:(content absolute top-0 right-0 w-1/2 h-2px bg-blue)">some text</div>
```
 For example, given the above markup, I get the error `'relative' applies the same CSS property as 'absolute' and 'absolute'."`. This is not the case for I have three different elements, the root div, the before and after pseudo-elements. I am sure someone else has encountered this. Would be nice to know how they got around it, thanks!

**Comment by ben-rogerson** [comment]
I think that's a warning from the [vscode intellisense plugin](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/167) rather than twin.
I haven't seen the error before  - maybe it's worth asking about it over there?

**Comment by joeynimu** [comment]
It must be. Closing this for now, thanks!
