### ISSUE TITLE
Css prop styles not compiled when tw is prop is omitted

### ISSUE THREAD

**Issue by fvanwijk** [ben-rogerson/twin.macro#339]
It appears that after bumping twin.macro from 2.1.1 to 2.2.3 this will not render correctly:

```tsx
// Loader.tsx
import React, { ReactElement } from 'react';

export const Loader = (): ReactElement => <div role="progressbar" aria-live="polite" aria-busy />;
```

```tsx
// Button.tsx
import React, { ButtonHTMLAttributes, ReactElement } from 'react';
import tw from 'twin.macro';

import { Loader } from './Loader';

export const Button = ({ children, loading, ...props }: ButtonHTMLAttributes<HTMLButtonElement>): ReactElement => {
  return (
    <button
      css={[tw`bg-blue-400`]} // not applied
      {...props}
    >
      {loading ? <Loader /> : children}
    </button>
  );
};
```

Output is `<button css="[object object]">` so it looks like styled-components prcessing isn't activated. Probably something with the twin import stripped out during compilation?
It can be 'fixed' by adding `tw=""` prop to the button or by not importing/using Loader.

I also bumped tailwindcss and styled-components to latest, so I'm not completely confident that twin is the culprit. Could anyone verify my bug report :)

**Comment by fvanwijk** [comment]
Related to this I observed other (related?) weird behavior too:
```
import tw from 'twin.macro';

// ReferenceError: tw is not defined
<button css={tw`bg-blue-500`} {...props}>

// Works
<button css={[tw`bg-blue-500`]} {...props}>
```

**Comment by ben-rogerson** [comment]
Thanks for the report Frank, verified there's definitely a bug here - I'm on it.

**Comment by ben-rogerson** [comment]
Should be all patched up in [twin.macro@2.3.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.3.0)
