### ISSUE TITLE
"Use Twin with TypeScript + emotion" guide isn't working

### ISSUE THREAD

**Issue by dspacejs** [ben-rogerson/twin.macro#340]
I'm following the [repo's guide](https://github.com/ben-rogerson/twin.macro/blob/master/docs/emotion/typescript.md) to enable imports, such as `css` and `styled`.

For reference, this is everything I'm referring to:

```typescript
// twin.d.ts
import 'twin.macro'
import styledImport from '@emotion/styled'
import { css as cssImport } from '@emotion/react'

// The css prop
// https://emotion.sh/docs/typescript#css-prop
import {} from '@emotion/react/types/css-prop'

declare module 'twin.macro' {
  // The styled and css imports
  const styled: typeof styledImport
  const css: typeof cssImport
}

// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string
    }
  }
}
```

But I've encountered a few problems with this code block:

```typescript
// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string
    }
  }
}
```

Firstly, I had to import `DOMAttributes` (this wasn't included in the guide, but I fixed it):

```typescript
import { DOMAttributes } from "react"
```

Secondly, I'm getting the following error for the `IntrinsicAttributes` interface:

> All declarations of 'IntrinsicAttributes' must have identical type parameters.

I've tried playing around with this and looking for similar errors online with no luck. Am I doing something wrong here, or is this code broken? The module declaration's imports don't work at all, which I assume is due to this error.

Thirdly, I don't understand this import:

```typescript
import {} from "@emotion/react/types/css-prop"
```

Why is an empty object being imported, and how is this supposed to fulfil `typeof cssImport`? If it's just to import the definitions, isn't `import "@emotion/react/types/css-prop"` sufficient?

Also, I'm new to TypeScript, so please forgive me if I've made a rudimentary mistake. Additionally, it'd be great if there's a DefinitelyTyped library added for this, so it's not necessary to manually set this up.

I can provide more details of my environment if necessary, but haven't because I figured it's probably not.

**Comment by alexolivier** [comment]
I'm also struggling with this

**Comment by ben-rogerson** [comment]
Heya great to see another Adelaidian around here!

Typescript + emotion have updated and I'm now looking into what needs changing.

## Fixing the css prop

This doesn't work anymore:

```js
import {} from "@emotion/react/types/css-prop"
```

Instead, you can add this to your tsconfig.js:

```js
{
  "compilerOptions": {
    "jsxImportSource": "@emotion/react"
  }
}
```

[Source](https://emotion.sh/docs/typescript#css-prop)

## Fixing 'as' types

I can see that [some work was done in July 2020](https://github.com/emotion-js/emotion/pull/1874) to add support for it but I've been unable to get this working myself.

I'm not sure the best way forward with this so I'll need some help with this one.

---

I'll update the typescript docs with my findings so far.

**Comment by dspacejs** [comment]
@ben-rogerson oh haha, I didn't even realise you were from there. Yep, I haven't come across many developers here online, nice to meet you.

Your updated example works fine for me, thanks. I'll report back if I encounter any other issues.

**Comment by ortonomy** [comment]
```
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string | React.ElementType; // CHANGE TO THIS
    }
  }
}
```

this is still throwing an error:

`All declarations of 'IntrinsicAttributes' must have identical type parameters.ts(2428)`

**Comment by ben-rogerson** [comment]
@ortonomy Looks like a clash with other types - what's the rest of your types look like?

**Comment by ortonomy** [comment]
@ben-rogerson -- thansk for following up -- it's actually in a gatsby project, so I will have to get back to this one. I've made almost zero changes to the typing config except for this. will report back.
