### ISSUE TITLE
Negative Inset error

### ISSUE THREAD

**Issue by Quinten-6wines** [ben-rogerson/twin.macro#347]
I am moving a tailwind html to react/nextjs but I am running into a problem.

I am using:

`tw="-top-5"`

But it is throwing this error at me:

`-top-5 was not found
    at Array.reduce (<anonymous>)`

Seems to throw an error at all negative insets.

any ideas on how to solve this?

**Comment by ben-rogerson** [comment]
Just tested and working here.

What's your tailwind.config.js look like? Perhaps you're overwriting the values by not using `extend`?

**Comment by Quinten-6wines** [comment]
Currently I am merging 2 configs as I am porting a site to a new design

`const resolveConfig = require('tailwindcss/resolveConfig')
const demoConfig = require('./tailwind.demo.config.js') //old
const sixWinesConfig = require('./tailwind.6wines.config.js') // new

module.exports = resolveConfig(demoConfig, sixWinesConfig)`

In both configs the theme is extended:

Config 1 (old):

`module.exports = {
  future: {
    purgeLayersByDefault: true,
    applyComplexClasses: true,
  },
  purge: {
    content: [
      './pages/**/*.{js,ts,jsx,tsx}',
      './components/**/*.{js,ts,jsx,tsx}',
    ],
    options: {
      safelist: {
        standard: ['outline-none'],
      },
    },
  },
  theme: {
    extend: {
      maxWidth: {
        '8xl': '1920px',
      },
      colors: {
        primary: 'var(--primary)',
        'primary-2': 'var(--primary-2)',
        secondary: 'var(--secondary)',
        'secondary-2': 'var(--secondary-2)',
        hover: 'var(--hover)',
        'hover-1': 'var(--hover-1)',
        'hover-2': 'var(--hover-2)',
        'accents-0': 'var(--accents-0)',
        'accents-1': 'var(--accents-1)',
        'accents-2': 'var(--accents-2)',
        'accents-3': 'var(--accents-3)',
        'accents-4': 'var(--accents-4)',
        'accents-5': 'var(--accents-5)',
        'accents-6': 'var(--accents-6)',
        'accents-7': 'var(--accents-7)',
        'accents-8': 'var(--accents-8)',
        'accents-9': 'var(--accents-9)',
        violet: 'var(--violet)',
        'violet-light': 'var(--violet-light)',
        pink: 'var(--pink)',
        cyan: 'var(--cyan)',
        blue: 'var(--blue)',
        green: 'var(--green)',
        red: 'var(--red)',
      },
      textColor: {
        base: 'var(--text-base)',
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
      },
      boxShadow: {
        'outline-2': '0 0 0 2px var(--accents-2)',
        magical:
          'rgba(0, 0, 0, 0.02) 0px 30px 30px, rgba(0, 0, 0, 0.03) 0px 0px 8px, rgba(0, 0, 0, 0.05) 0px 1px 0px',
      },
      lineHeight: {
        'extra-loose': '2.2',
      },
      scale: {
        120: '1.2',
      },
    },
  },
  plugins: [require('@tailwindcss/ui')],
}
`

Config 2 (new)

`const defaultTheme = require('tailwindcss/defaultTheme')
const plugin = require('tailwindcss/plugin')

module.exports = {
  future: {
    purgeLayersByDefault: true,
    applyComplexClasses: true,
  },
  purge: {
    content: [
      './pages/**/*.{js,ts,jsx,tsx}',
      './components/**/*.{js,ts,jsx,tsx}',
    ],
    options: {
      safelist: {
        standard: ['outline-none'],
      },
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    customForms: (theme) => ({
      default: {
        checkbox: {
          backgroundColor: 'transparent',
          height: '1.5em',
          width: '1.5em',
          color: defaultTheme.colors.gray[500],
          borderRadius: '7px',
          borderWidth: '1px',
          borderColor: 'currentColor',
          icon: (iconColor) =>
            `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="${iconColor}"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" /></svg>`,
          '&:focus': {
            borderColor: 'currentColor',
            backgroundColor: 'transparent',
          },
          '&:checked': {
            borderColor: 'currentColor',
            backgroundColor: 'transparent',
          },
          iconColor: theme('colors.kermit'),
        },
      },
    }),
    extend: {
      colors: {
        grape: '#881943',
        rouge: '#c31c37',
        pink: '#e9436a',
        strawberry: '#e73748',
        rose: '#ed706b',
        champagne: '#f39568',
        copy: {
          DEFAULT: '#240d22',
          100: '#240d22',
          50: '#928088',
          20: '#C4BEC3',
        },
        gray: {
          light: 'E5E1E0',
        },
        creme: {
          DEFAULT: '#fff2ef',
          extra: '#EBD6CE',
          dark: '#f2dbd1',
        },
        kermit: '#4DDB59',
      },
      fontFamily: {
        aeonik: ['Aeonik', 'Arial', ...defaultTheme.fontFamily.sans],
      },
      gridTemplateColumns: {
        header: '1fr 8.5rem 1fr',
        footer: '12rem repeat(2, 20rem) 1fr 20rem',
        'footer-lg': '12rem repeat(2, 15rem) 1fr 15rem',
        '1-col': 'repeat(1, 20rem)',
        '2-cols': 'repeat(2, 20rem)',
        '3-cols': 'repeat(3, 20rem)',
        '4-cols': 'repeat(4, 20rem)',
        'cart-item-large': '9rem 1fr repeat(3, 10rem) 7rem',
        'cart-item-small': '9rem 1fr 10rem',
      },
      width: {
        34: '8.5rem',
        85: '21.25rem',
        90: '22.5rem',
        100: '25rem',
        120: '30rem',
        160: '40rem',
        200: '50rem',
        275: '68.75rem',
        '1-col': '20rem',
        '2-cols': '40rem',
        '3-cols': '60rem',
        '4-cols': '80rem',
        'screen-2x': '200vw',
      },
      height: {
        100: '25rem',
        130: '32.5rem',
        140: '35rem',
        180: '45rem',
      },
      maxWidth: {
        '1-col': '20rem',
        '2-cols': '40rem',
        '3-cols': '60rem',
        '4-cols': '80rem',
        275: '68.75rem', //cart
      },
      minHeight: {
        180: '45rem',
      },
      screens: {
        sm: '20rem',
        // => @media (min-width: 640px) { ... }

        md: '40rem',
        // => @media (min-width: 768px) { ... }

        lg: '60rem',
        // => @media (min-width: 1024px) { ... }

        xl: '80rem',
        // => @media (min-width: 1280px) { ... }

        mh: { raw: '(max-height: 700px)' },
        // => @media (min-height: 700px) { ... }
      },
      spacing: {
        18: '4.5rem',
      },
    },
  },
  variantOrder: [
    'first',
    'last',
    'odd',
    'even',
    'second-col',
    'visited',
    'checked',
    'group-hover',
    'group-focus',
    'focus-within',
    'hover',
    'focus',
    'focus-visible',
    'active',
    'disabled',
  ],
  variants: {
    extend: {
      scale: ['group-hover'],
      display: ['group-hover'],
      opacity: ['group-hover'],
      transitionProperty: ['group-hover'],
      translate: ['hover', 'group-hover', 'second-col', 'even'],
      backgroundColor: ['second-col', 'even'],
      visibility: ['hover', 'focus', 'group-hover'],
      rotate: ['hover', 'group-hover'],
      justifyContent: ['odd'],
      borderWidth: ['last', 'even'],
    },
  },
  plugins: [
    require('tailwindcss-debug-screens'),
    require('@tailwindcss/custom-forms'),
    plugin(function ({ addVariant, e }) {
      addVariant('second-col', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `.${e(`second-col${separator}${className}`)}:nth-child(3n+2)`
        })
      })
    }),
  ],
}
`

**Comment by ben-rogerson** [comment]
You'll need to [add negative items to your inset config](https://tailwindcss.com/docs/top-right-bottom-left#negative-values).

Here are the inset values from your combined configs above:

```js
"inset": {
  "0": "0",
  "1": "0.25rem",
  "2": "0.5rem",
  "3": "0.75rem",
  "4": "1rem",
  "5": "1.25rem",
  "6": "1.5rem",
  "7": "1.75rem",
  "8": "2rem",
  "9": "2.25rem",
  "10": "2.5rem",
  "11": "2.75rem",
  "12": "3rem",
  "13": "3.25rem",
  "14": "3.5rem",
  "15": "3.75rem",
  "16": "4rem",
  "18": "4.5rem",
  "20": "5rem",
  "24": "6rem",
  "28": "7rem",
  "32": "8rem",
  "36": "9rem",
  "40": "10rem",
  "44": "11rem",
  "48": "12rem",
  "52": "13rem",
  "56": "14rem",
  "60": "15rem",
  "64": "16rem",
  "72": "18rem",
  "80": "20rem",
  "96": "24rem",
  "auto": "auto",
  "px": "1px",
  "0.5": "0.125rem",
  "1.5": "0.375rem",
  "2.5": "0.625rem",
  "3.5": "0.875rem",
  "1/2": "50%",
  "1/3": "33.333333%",
  "2/3": "66.666667%",
  "1/4": "25%",
  "2/4": "50%",
  "3/4": "75%",
  "1/5": "20%",
  "2/5": "40%",
  "3/5": "60%",
  "4/5": "80%",
  "1/6": "16.666667%",
  "2/6": "33.333333%",
  "3/6": "50%",
  "4/6": "66.666667%",
  "5/6": "83.333333%",
  "1/12": "8.333333%",
  "2/12": "16.666667%",
  "3/12": "25%",
  "4/12": "33.333333%",
  "5/12": "41.666667%",
  "6/12": "50%",
  "7/12": "58.333333%",
  "8/12": "66.666667%",
  "9/12": "75%",
  "10/12": "83.333333%",
  "11/12": "91.666667%",
  "full": "100%"
},
```
