### ISSUE TITLE
position/inset not detected

### ISSUE THREAD

**Issue by thisisablock** [ben-rogerson/twin.macro#35]
hi @ben-rogerson , and thanks for your plugin.

trying to migrate vom tailwind-canary.macro to twin.macro. everything works except one thing.

1. positions not working for me

```
import tw from "twin.macro";

const Base = styled.div`
    ${tw`top-0 hidden md:flex flex-row mb-4 md:sticky z-50`}
`
```

results in 

```
top-0 was not found
```

in my config im not using inset

**Comment by ben-rogerson** [comment]
Great to hear you migrated over to twin :)

I'm seeing the `top-0` class working correctly on [this demo](https://codesandbox.io/s/react-top-0-demo-ysluy?file=/src/App.js) with the code you've supplied.

If you still need a hand then it would really help if you post a minimal working example on codesandbox.

Thanks

**Comment by thisisablock** [comment]
@ben-rogerson cool thx for the sandbox. i just checked my tailwind config and found the solution. the reason was my custom insets added to module.exports.theme.

adding that to module.exports.theme.extend. fixed the issues.

thx and Frohe Ostern!
