### ISSUE TITLE
Deeply nested color issue 

### ISSUE THREAD

**Issue by fasetto** [ben-rogerson/twin.macro#355]
I am using emotion with Next JS setup. Why twin.macro showing this error ?
```term
MacroError: ...\NavMenu.tsx:
✕ bg-atlas-blue-500 was not found

Try one of these classes:
bg-atlas-blue-500 ["#0747A6"] .....
```
My `tailwind.config.js` file looks like this;
```json
...
theme: {
  extend: {
    colors: {
       atlas: {
          blue: {
             500: "#0747A6"
          }
      }
    }
  }
}
```

**Comment by ben-rogerson** [comment]
I think you’ve found a bug here, twin has an issue with the deep nesting - I'll take a look into that.

Workaround is 1 less level of nesting:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        "atlas-blue": {
          500: "#0747A6",
        },
      },
    },
  },
};
```

**Comment by fasetto** [comment]
Yeah, I was thinking about that but couldn't test more. Thanks for the reply.

**Comment by leog** [comment]
Bumped into the same issue. Any progress @ben-rogerson? I was debugging a bit but couldn't find where the issue originates in order to contribute.

**Comment by ben-rogerson** [comment]
I needed to tackle some other issues first, but I'll be swinging back around to fix this one soon, along with a [similar nesting issue](https://github.com/ben-rogerson/twin.macro/issues/354).
