### ISSUE TITLE
pseudo classes such as :hover :active and :disabled not applied from plugin

### ISSUE THREAD

**Issue by TimvdEijnden** [ben-rogerson/twin.macro#356]
There’s an issue in twin.macro 2.3.0 which causes pseudo classes such as :hover :active and :disabled to not be applied.

Example repo:
https://github.com/TimvdEijnden/twin.macro-issue-pseudo-classes

The psuedo classes are defined in `plugins/buttons.js`

Here's are 2 video's where you'll see the difference between 2.2.3 (working correctly) and 2.3.0

https://user-images.githubusercontent.com/951290/110836917-eb5c3900-82a0-11eb-92a2-c50de5bdfc3b.mp4

https://user-images.githubusercontent.com/951290/110836924-ed25fc80-82a0-11eb-8dd1-20419be07d86.mp4

**Comment by ben-rogerson** [comment]
Some great examples here, thank you!

Here is the fix:

```diff
// twin.macro-issue-pseudo-classes/plugins/buttons.js 

module.exports = () => {
  return plugin(({ addComponents, theme }) => {
    // ...

    addComponents({
-      'button-primary': {
+      '.button-primary': {
        // ...
      }
    })
  })
}

```

The code that creates classes from plugins was updated to follow the tailwindcss class declaration syntax a little more closely so the dot to indicate a class is now required.

**Comment by TimvdEijnden** [comment]
Ok great to know, then I can fix the issue myself in our internal project quickly.🤗
