### ISSUE TITLE
`css` and `tw` props on custom components aren't being applied 

### ISSUE THREAD

**Issue by judehunter** [ben-rogerson/twin.macro#358]
I've tried using the custom `css` and `tw` props on custom components (instead of HTML elements), and it appears they are stripped.
Example usage:
```tsx
import tw, {css} from 'twin.macro';
const Example = () => (
  <h1>Test</h1>
)
const App = () => (
  <Example tw="text-pink-500" css={css`opacity: 0;`} />
  // surprisingly, the text is not pink and is visible
)
```
The rendered HTML is exactly `<h1>Test</h1>` with no `data-tw` and no classes attached to it.

I'm using `twin.macro: 2.3.0` with `@emotion/react: 11.1.5`. I'm also using TypeScript, and as far as I can tell, it does transpile the props correctly, as I can find `data-tw` and `css` fields in the component's props (in the definition of `App`).

I would like to provide a working demo, but all of the provided codesandbox links seem to be broken?..

Is this not supported by `twin.macro`, or is it a bug?

**Comment by lightyen** [comment]
you forget the `props`:
```tsx
function Example(props: Omit<React.HTMLAttributes<HTMLHeadingElement>, "children">) {
	return <h1 {...props}>Text</h1>
}
```

**Comment by fvanwijk** [comment]
I also wonder whether the `tw` import is required. It is not used.

**Comment by ben-rogerson** [comment]
Yup, it's not required here, it can be shortened to:

```js
import { css } from 'twin.macro';
```

**Comment by judehunter** [comment]
sorry for the late reply.
Of course, passing in a rest props param will work, usually regardless of the styling library.
However, I was under the impression that since twin.macro has its own JSX createElement function, that it would support simply styling a custom component, just like you can put classes on a component in Vue. But I suppose it's not always what you want to achieve... And maybe it's not the React way of doing things.

**Comment by ben-rogerson** [comment]
> However, I was under the impression that since twin.macro has its own JSX createElement function, that it would support simply styling a custom component, just like you can put classes on a component in Vue. 

Twin doesn’t have a createElement function, but the css-in-js library underneath does.
Perhaps try styled components - that doesn’t require you to pass props back onto JSX elements:

```js
import tw, {css} from 'twin.macro';

const Example = tw.h1([tw`text-pink-500`, css`opacity: 0;`])

const App = () => (
  <Example />
)
```
