### ISSUE TITLE
space-x-reverse does not generate the correct variable value

### ISSUE THREAD

**Issue by michelegera** [ben-rogerson/twin.macro#359]
Hello and thanks for this fantastic library!

I noticed a buggy behavior when applying `space-x-reverse` conditionally to a flex container with two children.

In that case, the `--tw-space-x-reverse` variable gets assigned a `1px` value rather than the expected `1` and the (second, since we are in a `flex-direction: row-reverse` scenario) child element right margin does not get the expected value.

I’m using the library in a Next.js app with styled-components, [here’s a demo of the issue](https://codesandbox.io/s/keen-dew-nblsl).

**Comment by ben-rogerson** [comment]
Thank you :)

This is super strange - so what I've found is that [twin adds the right value](https://github.com/ben-rogerson/twin.macro/blob/6c1da36fda3a76b4c514a996ab843999df26f441/src/config/staticStyles.js#L111) for the css variable and somewhere afterwards it’s changed from `1` to `'1px'`.

These are the styles after babel has finished:

![image](https://user-images.githubusercontent.com/21288568/111900146-b90cc180-8a80-11eb-99d9-ef8597cdf111.png)

And this is previewing the component in dev tools:

![image](https://user-images.githubusercontent.com/21288568/111900097-629f8300-8a80-11eb-8695-b87841c2001d.png)

I hope it’s not a stylus bug 🤞 
This one needs to be looked into a little further 🤯

**Comment by ben-rogerson** [comment]
Okay, looks like I've found a fix for this - patch coming soon.
