### ISSUE TITLE
grid-flow-col-dense has wrong css prop attached to it

### ISSUE THREAD

**Issue by adamgen** [ben-rogerson/twin.macro#361]
# Expected:

Adding `.grid-flow-col-dense` results in adding a css prop `grid-auto-flow: column dense`.

# Actual:

The added prop has an invalid  `col dense` instead of `column dense`. 

![image](https://user-images.githubusercontent.com/7424209/111599676-37473a80-87d9-11eb-813d-77d51dd6456e.png)

# code references

The buggy line on twin macro:

https://github.com/ben-rogerson/twin.macro/blob/34cd332ab81b9d98e84e0e57badcacccbda1f0f9/src/config/staticStyles.js#L268

The original (correct) line on twilwindcss:

https://github.com/tailwindlabs/tailwindcss/blob/e3ed12782f85f2985b3ba4d3e62451b720a93230/src/plugins/gridAutoFlow.js#L8

Should I open a PR?

**Comment by ben-rogerson** [comment]
Great pickup, yes please add that pr 👍
