### ISSUE TITLE
Elements displaying outdated font when Tailwind config is updated

### ISSUE THREAD

**Issue by kibebr** [ben-rogerson/twin.macro#362]
Hi, how are you doing?

I noticed that when updating fonts in my Tailwind config, twin.macro doesn't automatically update them. What's weirder is that some elements have their fonts updated, but some elements don't.

I'll try to explain what I did step by step:

This is the config I had inside my `tailwind.config.js`:
```
  theme: {
    extend: {
      fontFamily: {
        serif: ['Domine', ...fontFamily.serif],
        caps: 'Oswaldo'
      }
```

Everything was fine, but later I changed these fonts to:
```
  theme: {
    extend: {
      fontFamily: {
        serif: ['Amerigo BT', ...fontFamily.serif],
        caps: 'Barlow Condensed'
      }
```

I refreshed my webapp and noticed that some elements with `font-caps` still displayed `Oswald` instead of `Barlow Condensed`.

Here's an example of an element that still displays `Oswald` instead of `Barlow Condensed`:

![2021-03-20-162400_1366x768_scrot](https://user-images.githubusercontent.com/47016873/111877068-6b695980-8999-11eb-935d-5131cf7ff1aa.png)

And here's another element, with the same `font-caps`, but showing the updated font correctly:

![working](https://user-images.githubusercontent.com/47016873/111877099-9489ea00-8999-11eb-812e-e314cb5a0f93.png)

The same is true with `font-serif`, some elements display the old `Domine`, while others display the updated `Amerigo BT`.

I don't know if this is a twin.macro or styled components issue

Using `className` instead of `tw`  "solves" it.

If there's anything else I can do to help you solve it, please let me know!

I'm using twin.macro with styled components, Next.js

**Comment by kibebr** [comment]
After some digging around in here it seems like this is a common caching issue with `babel-plugin-macros` and not related to twin.macro. No big deal but how can I force it to recompile? There's no `node_modules/.cache` :/

**Comment by ben-rogerson** [comment]
Yes, you're right - it's a common issue but I've been looking into a workaround and I'm aiming to improve the DX soon.

To force a cache bust in Next.js after changing your tailwind.config.js:

- Delete the `.next` folder
- Restart your dev server
- Make a change in a file to force a babel re-compile

**Comment by kibebr** [comment]
@ben-rogerson awesome, thank you!
