### ISSUE TITLE
`ring-opacity-x` shouldn't need to be specified after ring color classes

### ISSUE THREAD

**Issue by ndom91** [ben-rogerson/twin.macro#374]
When adding a `hocus` group variant, for example `hocus:(ring-4 ring-green-500 ring-opacity-20)`, the opacity is not applied. If you take the opacity out of the group, for example `hocus:(ring-4 ring-green-500) hocus:ring-opacity-20` it works all of a sudden.

i.e. 
This doesn't work:
```jsx
<button
  tw="text-sm py-2.5 px-5 rounded-md border border-green-600 flex items-center hocus:(outline-none ring-4 ring-opacity-20 ring-green-500)"
>
```

And this works:
```jsx
<button
  tw="text-sm py-2.5 px-5 rounded-md border border-green-600 flex items-center hocus:(outline-none ring-4 ring-green-500) hocus:ring-opacity-20"
>
```

Made a codesandbox for you guys: https://codesandbox.io/s/wonderful-johnson-hc4g3

**Comment by ben-rogerson** [comment]
Thanks for the great bug report.

This looks like an ordering issue - is we swap the order of `ring-opacity-20` and `ring-green-500` so the opacity is last then the result should be correct.

Not too long ago I forced a [reorder on a bunch of classes](https://github.com/ben-rogerson/twin.macro/commit/aebf6da061ec49d55628c19c203fabd57d2d0d06) and looks like this might need the same fix.

**Comment by ndom91** [comment]
Is there a way to get twin.macro or the eslint plugin to order the classes for you? My OCD brain doesn't like having them in the random order I typed them in and would rather have them automatically ordered in a consistent manner haha.

I know theres somes prettier plugins that'll do it for "native" tailwind classes.

**Comment by tirthGajjar** [comment]
same issue with the background opacity
