### ISSUE TITLE
Using `bg-clip-text` throws a kebab-case error

### ISSUE THREAD

**Issue by yudyananda** [ben-rogerson/twin.macro#375]
I have component with `bg-clip-text` class and my console throw the following error `ERROR Using kebab-case for css properties in objects is not supported. Did you mean WebkitBackgroundClip?`

```js
const Title = tw.h1`bg-clip-text`
```
 
Not sure if the error is false or true. The component generates style as i expected but i found that it have duplicate `-webkit-background-clip: text;`

I'm using gatsby and emotion

**Comment by ben-rogerson** [comment]
Good pickup - yes this is an error.
Twin is generating `-webkitBackgroundClip` instead of `WebkitBackgroundClip`.

You can use this as a workaround until I push a patch: 

```js
tw.h1`-webkit-background-clip[text] background-clip[text]`;
```

**Comment by yudyananda** [comment]
Line [457 to 475]( https://github.com/ben-rogerson/twin.macro/blob/16911c0dc75999e7f33edf12039f042fdab50b94/src/config/staticStyles.js#L457),   is this it? 

test in my local, the warning is gone after change it with `WebkitBackgroundClip`

**Comment by ben-rogerson** [comment]
That's it, all those values need the same updates 👍

**Comment by yudyananda** [comment]
test on my local change it with `WebkitBackgroundClip` and the error is gone. I'll send you PR if its good enough...

**Comment by ben-rogerson** [comment]
Sounds good to me.
If you could also update the fixture tests (`npx jest --u`), that would be sweet.
