### ISSUE TITLE
Support Tailwind CSS v2.1.0

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#381]
Time to bring twin up-to-date with [tailwindcss 2.1.0](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.1.0)!

Update: I've finished adding all the classes, just gotta add a couple of patches to the list and I'll push all of this out in the next twin release.

### New blending mode utilities ([3920](https://github.com/tailwindlabs/tailwindcss/pull/3920))

```js
".bg-blend-normal": { "background-blend-mode": "normal" },
".bg-blend-multiply": { "background-blend-mode": "multiply" },
".bg-blend-screen": { "background-blend-mode": "screen" },
".bg-blend-overlay": { "background-blend-mode": "overlay" },
".bg-blend-darken": { "background-blend-mode": "darken" },
".bg-blend-lighten": { "background-blend-mode": "lighten" },
".bg-blend-color-dodge": { "background-blend-mode": "color-dodge" },
".bg-blend-color-burn": { "background-blend-mode": "color-burn" },
".bg-blend-hard-light": { "background-blend-mode": "hard-light" },
".bg-blend-soft-light": { "background-blend-mode": "soft-light" },
".bg-blend-difference": { "background-blend-mode": "difference" },
".bg-blend-exclusion": { "background-blend-mode": "exclusion" },
".bg-blend-hue": { "background-blend-mode": "hue" },
".bg-blend-saturation": { "background-blend-mode": "saturation" },
".bg-blend-color": { "background-blend-mode": "color" },
".bg-blend-luminosity": { "background-blend-mode": "luminosity" },
```

### New isolation utilities ([3914](https://github.com/tailwindlabs/tailwindcss/pull/3914))

```js
'.isolate': { isolation: 'isolate' },
'.isolation-auto': { isolation: 'auto' },
```

### New box-decoration-break utilities ([3911](https://github.com/tailwindlabs/tailwindcss/pull/3911))

```js
'.decoration-slice': { 'box-decoration-break': 'slice' },
'.decoration-clone': { 'box-decoration-break': 'clone' },
```

### New inline-table and list-item display utilities ([3563](https://github.com/tailwindlabs/tailwindcss/pull/3563), [3929](https://github.com/tailwindlabs/tailwindcss/pull/3929))

```js
'.inline-table': { display: 'inline-table'},
'.list-item': { display: 'list-item' }
```

### New filter and backdrop-filter utilities ([3923](https://github.com/tailwindlabs/tailwindcss/pull/3923))

```js
<div className="filter blur-md grayscale invert ..." />
// and 
<div className="backdrop-filter backdrop-blur backdrop-brightness-50 ..." />
```

---

### Arbitrary value support
There is no current support for custom tailwind class values - but it will be added to twin:

```js
<button tw="bg-[#1da1f1]" /> // support coming soon
```

For now, use twin's short css feature that allows _any_ css properties to be added: 

```js
<div tw="background-color[#1da1f1]" />
```

### Built-in important modifier

Twin already supports a`!` added at the _end_ of the class.
I'm going to add support for the same syntax tailwind uses (`!` at the front):

```js
<div tw="font-bold !font-medium" /> // support coming soon
```

**Comment by luknl** [comment]
Hey, thank you for being so quick on that!

I was wondering how twin was going to manage the new JIT feature.
You say that it's not required because there is already short css, right?

But maybe allowing the 2 ways would be nice? 
It would also produce a smaller code, and more clear in some cases:
`tw="mt-16 lg:mt-[240px]"` might be more clear that it's the same property being changed then `tw="mt-16 lg:margin-top-[240px]"` ?

**Comment by ben-rogerson** [comment]
Check out [this discussion](https://github.com/ben-rogerson/twin.macro/discussions/360) for more info on the new JIT features in twin.

**Comment by smetzdev** [comment]
Hey @ben-rogerson, what would you think about the idea about a "polyfill" tailwind-plugin for new tailwind-features for the time between new tailwind-releases and the next twin.macro version containing these features?

**Comment by ben-rogerson** [comment]
> Hey @ben-rogerson, what would you think about the idea about a "polyfill" tailwind-plugin for new tailwind-features for the time between new tailwind-releases and the next twin.macro version containing these features?

I'm certain this wouldn't be possible for every feature but [I'm interested in hearing any ideas](https://github.com/ben-rogerson/twin.macro/discussions/new).

**Comment by ben-rogerson** [comment]
Update to [twin.macro@2.4.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.4.0) to use the new classes above 🎉
