### ISSUE TITLE
tw not working with Goober/Gatsby

### ISSUE THREAD

**Issue by wildpow** [ben-rogerson/twin.macro#383]
Styles are showing up as `object` when using `tw` inside of a component. Reproduction [here](https://github.com/wildpow/goober-twin-test) 

```js
import tw,{ styled } from 'twin.macro';

const Button = styled('button')`
/* background-color: green; */
font-size: 10em;
${tw`bg-green-900`};
`

```
![Screen Shot 2021-04-08 at 4 53 09 PM](https://user-images.githubusercontent.com/17464319/114109836-f1870a80-988a-11eb-93c7-88bbca5f55e9.png)

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU
 @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-plugin-goober: ^2.4.0 => 2.4.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by kelvindecosta** [comment]
Hello!

I have also faced the same issue (see #327).

Ben suggests customizing `.babelrc` (see https://github.com/ben-rogerson/twin.macro/issues/327#issuecomment-776460552).

Hope this helps you out!

**Comment by wildpow** [comment]
I tried using the exact `.babelrc` from that comment you referenced and a combination of Twin's Preact/Goober example but no dice. Unfortunately, this is a bit over my head due to never having to mess with Gatsby's babel config before.

**Comment by ben-rogerson** [comment]
Looks like interpolation of css object aren't supported in the Goober backticks.

Instead, you can add your classes to an array or within an object:

```js
import React from "react"
import tw, { styled } from "twin.macro"

// ===

// Option a: Array
const Button = styled("button")([
  { backgroundColor: "green", fontSize: "10em" },
  tw`bg-red-900`,
])

// Option b: Object
const Button = styled("button")({
  backgroundColor: "green",
  fontSize: "10em",
  ...tw`bg-red-900`
})

// ===

export default function Home() {
  return (
    <div>
      <Button>Does work</Button>Hello world!
    </div>
  )
}
```

**Comment by wildpow** [comment]
So `theme` must use a different process because that works fine.

**Comment by wildpow** [comment]
I wanted to see how the [twin/goober/preact](https://github.com/ben-rogerson/twin.examples/tree/master/preact-goober) worked with `tw` but, it seems to be in the same boat. 
<img width="563" alt="Screen Shot 2021-04-13 at 4 29 54 PM" src="https://user-images.githubusercontent.com/17464319/114633743-f9252580-9c75-11eb-9b81-2f0ab425ea8c.png">

Should there even be a goober preset?

**Comment by ben-rogerson** [comment]
Yeah, the theme values don't get replaced with an object, that's the difference between it and the tailwind classes.

I think it's well worth supporting Goober through a preset, although you currently can't interpolate tailwind styles into template literals, there are two workarounds above that make it very usable.

**Comment by ben-rogerson** [comment]
Closing for now as this issue is due to lack of interpolation support in Goober.

Feel free to reopen if you think twin should have this as a polyfill feature.

**Comment by orsi** [comment]
This is still an issue for Gatsby as well:

<img width="764" alt="Screen Shot 2021-07-13 at 11 49 22 AM" src="https://user-images.githubusercontent.com/7156655/125483894-5020bb90-5a5a-4581-bf46-d7950732db05.png">

**Comment by dharmveer97** [comment]
Hey @orsi can you please help me?

I'm using gatsby with twin macros and tailwind CSS. 

I have an issue with the CSS render. I create pages in gastby.node.js   so if I click on links CSS does not load. then I reload the page the all CSS renders perfectly. 

I add full layout in gastby.browser.js

plz help

**Comment by orsi** [comment]
@dharmveer97 

I never got it working, so I didn't solve the issue :P

**Comment by ben-rogerson** [comment]
> I have an issue with the CSS render. I create pages in gastby.node.js so if I click on links CSS does not load. then I reload the page the all CSS renders perfectly.

Probably best to ask about this in Goober issues - Twin just does the tailwind > css object conversions.
Make sure you're using their [gatsby plugin](https://goober.js.org/integrations/gatsby/) too, and posting an example repository demonstrating the issue may help.
