### ISSUE TITLE
Using props to add tailwind classes

### ISSUE THREAD

**Issue by chrish-d** [ben-rogerson/twin.macro#39]
I'm trying to use props to add in some tailwind classes so that a component can pass down a particular colour and it gets picked up by tailwind and applied.

So I'm doing something like this `<MyComponent customColor="red" />` and then, using Emotion, I have something like this

```
const MyComponent = styled.div([
     ({ customColor }) => tw`bg-${customColor}-500`,
     tw`border`,
     css`...`,
])
```

But I get an error

> ✕ Class “bg-” shouldn’t have a trailing dash.

Any ideas what I'm doing wrong?

**Comment by rbutera** [comment]
Unfortunately, you cannot use string interpolation inside a `tw` tagged template literal

Please see #17 and the workarounds talked about in that issue
