### ISSUE TITLE
Missing peer-dependency from tailwindcss

### ISSUE THREAD

**Issue by larrifax** [ben-rogerson/twin.macro#392]
I'm using Yarn 2, and when I run `yarn install` I get the following warning:
```
➤ YN0002: │ twin.macro@npm:2.3.3 doesn't provide autoprefixer (pdfcb1), requested by tailwindcss
```

Running `yarn explain peer-requirements pdfcb1` produces the following output:
```
❯ yarn explain peer-requirements pdfcb1
➤ YN0000: twin.macro@npm:2.3.3 doesn't provide autoprefixer, breaking the following requirements:

➤ YN0000: tailwindcss@npm:2.1.1 [9de1f] → ^10.0.2 ✘
```

I believe the solution would be to either:
1. add `tailwindcss` as a peerDependency to this package
1. or to add `autoprefixer` as a dependency

If you're doing _1._, you could additionally mark the peerDependency as optional by adding the following to `package.json`:
```
  "peerDependenciesMeta": {
    "tailwindcss": {
      "optional": true
    },
  },
```

**Comment by ben-rogerson** [comment]
Cheers for bringing up this issue and for providing some solutions.

I've chosen the `autoprefixer` as a dependency option which I'll add to the next release.

**Comment by larrifax** [comment]
Thanks! 👍
