### ISSUE TITLE
tw - This expression is not callable.

### ISSUE THREAD

**Issue by dredshep** [ben-rogerson/twin.macro#399]
![image](https://user-images.githubusercontent.com/78047001/115470251-04db9380-a204-11eb-8d20-905f30556d3c.png)

![image](https://user-images.githubusercontent.com/78047001/115470296-158c0980-a204-11eb-940e-cb037d8e6b46.png)

![image](https://user-images.githubusercontent.com/78047001/115470317-1b81ea80-a204-11eb-8dfd-5c2c1ff0ca72.png)

node 14.16.1
react 17.0.2
typescript 4.2.2
twin.macro 2.3.3
nextjs 10.0.7

I can't use the package.

**Comment by dredshep** [comment]
forgot to include this one:

![image](https://user-images.githubusercontent.com/78047001/115470632-a1059a80-a204-11eb-9f89-b52695bb84b1.png)

**Comment by ben-rogerson** [comment]
The tw blocks get converted to an object so try this instead:

```js
<div css={{ ...tw`bg-black` }} />
// or
<div css={tw`bg-black`} />
```

**Comment by ben-rogerson** [comment]
Feel free to reopen if you think there's a bug here.
