### ISSUE TITLE
"inset" config option overwrites default classes

### ISSUE THREAD

**Issue by designbyadrian** [ben-rogerson/twin.macro#4]
With empty config, I can write:

```javascript
tw.div`absolute right-0`
```

But adding

```json
inset: {
      "0": 0,
      "auto": "auto"
}
```

To the config, which is the default Tailwind config, right-0 doesn't resolve to a class.

**Comment by ben-rogerson** [comment]
I have this converting well in my tests: 

```js
// In
import tw from "twin.macro";
tw.div`absolute right-0`;
```

```js
// Out
import _styled from "@emotion/styled";
_styled.div({
  "position": "absolute",
  "right": "0"
});
```
and my `./tailwind.config.js` in my root directory is:
```
module.exports = {
  theme: {
    inset: {
      "0": 0,
      auto: "auto",
      "1/2": "50%"
    }
  }
};
```

**Comment by ben-rogerson** [comment]
At the moment, you'll need to restart your dev server to pick up changes in your tailwind.config.js. 
But that shouldn't be required once I've finished dev mode.
