### ISSUE TITLE
Typescript: no exported member 'styled'.

### ISSUE THREAD

**Issue by dmwyatt** [ben-rogerson/twin.macro#406]
```
Module '"twin.macro"' has no exported member 'styled'. Did you mean to use 'import styled from "twin.macro"' instead?  TS2614

    1 | import PropTypes from "prop-types";
    2 | import React, { ChangeEvent } from "react";
  > 3 | import tw, { styled } from "twin.macro";
      |              ^
```

Using:

1. typescript 4.2.4
2. twin.macro 2.3.3

I notice that twin.macro's `index.d.ts` does not have an exported `styled`. The code actually works fine if I use @ts-ignore or if I'm using a plain JS file.

It's difficult to make a reproducible test case since it's a real hassle to get tailwind to work with CRA to work with twin.macro.  I'll work on it some more if no on knows what's going on here.

**Comment by ben-rogerson** [comment]
Twin only ships with types for the imports it provides, so you'll need to finish off the typescript installation.

There are typescript setup instructions in most of the examples, but here they are:

### Install react types

```shell
npm install -D @types/react
```

### Install types for styled-components

```js
// twin.d.ts
import 'twin.macro'
import styledImport, { CSSProp, css as cssImport } from 'styled-components'

declare module 'twin.macro' {
  // The styled and css imports
  const styled: typeof styledImport
  const css: typeof cssImport
}

declare module 'react' {
  // The css prop
  interface HTMLAttributes<T> extends DOMAttributes<T> {
    css?: CSSProp
  }
  // The inline svg css prop
  interface SVGProps<T> extends SVGProps<SVGSVGElement> {
    css?: CSSProp
  }
}

// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string | Element
    }
  }
}
```

Then add the following in your typescript config:

```js
// tsconfig.json
{
  "files": ["twin.d.ts"],
  // or "include": ["twin.d.ts"],
}
```

### Install types for Emotion

```js
// twin.d.ts
import 'twin.macro'
import styledImport from '@emotion/styled'
import { css as cssImport } from '@emotion/react'

declare module 'twin.macro' {
  // The styled and css imports
  const styled: typeof styledImport
  const css: typeof cssImport
}
```

Then add the following to your typescript config:

```js
// tsconfig.json
{
  "compilerOptions": {
    "jsxImportSource": "@emotion/react" // for the css prop
  },
  "files": ["twin.d.ts"],
  // or "include": ["twin.d.ts"],
}
```

**Comment by dmwyatt** [comment]
I've been using twin for months on non-TS projects and haven't had any
reason to look at anything other than README.md so I haven't seen any of
the examples before now.  Thanks!
