### ISSUE TITLE
class not found after upgrading to twin.macro 2.4.0

### ISSUE THREAD

**Issue by anark** [ben-rogerson/twin.macro#414]
Hi there,
After upgrading to twin.macro 2.4.0 I am seeing a lot of class not found errors for classes that exist in my tailwind config anywhere I try to use the `dark:` variant.
```
✕ bg-blue-gray-200 was not found

Try one of these classes:
bg-blue-gray-200 ["#e2e8f0"] / bg-blue-gray-100 ["#f1f5f9"] / bg-blue-gray-300 ["#cbd5e1"]
bg-blue-gray-400 ["#94a3b8"] / bg-blue-gray-500 ["#64748b"] / bg-blue-gray-600 ["#475569"]
bg-blue-gray-700 ["#334155"] / bg-blue-gray-800 ["#1e293b"] / bg-blue-gray-900 ["#0f172a"]
bg-blue-gray-50 ["#f8fafc"] / bg-blue-200 ["#bfdbfe"] / bg-gray-700 ["#374151"]
bg-gray-800 ["#1f2937"] / bg-gray-900 ["#111827"] / bg-blue-100 ["#dbeafe"] / bg-blue-300 ["#93c5fd"]
bg-blue-400 ["#60a5fa"] / bg-blue-500 ["#3b82f6"] / bg-blue-600 ["#2563eb"] / bg-blue-700 ["#1d4ed8"]
bg-blue-800 ["#1e40af"] / bg-blue-900 ["#1e3a8a"]
```
This shows up when using the following syntax
```
<div css={tw`dark:bg-blue-gray-200`}></div>
```

The exact same code worked fine using tailwind twin.macro 2.3.3

**Comment by ben-rogerson** [comment]
Hey there anark

I've tested dark mode classes in 2.4.0 but didn't stumble across any issues. 

Here's the tests, anything you're doing differently?

```js
// tailwind.config.js
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        blue: {
          gray: {
            200: "test",
          },
        },
      },
    },
  },
};
```

```js
import tw, { theme } from "twin.macro";

tw`dark:bg-blue-gray-200`;

// ↓ ↓ ↓ ↓ ↓ ↓

({
  ".dark &": {
    "backgroundColor": "test"
  }
});
```

**Comment by anark** [comment]
Very strange.  I'll do some debugging and see if I can narrow down what is causing this and make a reproducible example.

**Comment by anark** [comment]
This is quite strange.  I had the following in my tailwind config which used to work
```
module.exports = {
  purge: [],
  darkMode: 'class', // or 'media' or 'class' or false
  theme: {
    extend: {
      colors: {
        'blue-gray': colors.blueGray,
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
```

Changing `colors: { 'blue-gray': colors.blueGray }` to `colors: { blue: { gray: colors.blueGray }}` seems to fix this in the new version.  Not sure why that changed, but thanks for the help.

**Comment by ben-rogerson** [comment]
I'll take a look into that config, perhaps there's a bug there.

**Comment by ben-rogerson** [comment]
Yeah looks like there's an issue with the dashed key, I'll get a patch out asap.
