### ISSUE TITLE
Is there a way to compose tailwind.config.js file?

### ISSUE THREAD

**Issue by progexplorer24** [ben-rogerson/twin.macro#42]
Hey, 
First of all thank you very much work the great work you're doing with this plugin! 

I just wanted to ask if there is a way to compose tailwind.config.js file from partials.

Let's say I have 3 partial configuration files
```ts
const screens = {
  sm: "640px",
  md: "768px",
  lg: "1024px",
  xl: "1280px",
} as const

export default screens
````

```ts
const borderRadius = {
  none: "0",
  sm: "0.125rem",
  default: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  full: "9999px",
} as const

export default borderRadius
````

```ts
const fontSize = {
  xs: "0.75rem",
  sm: "0.875rem",
  base: "1rem",
  lg: "1.125rem",
  xl: "1.25rem",
  "2xl": "1.5rem",
  "3xl": "1.875rem",
  "4xl": "2.25rem",
  "5xl": "3rem",
  "6xl": "4rem",
  "7xl": "5rem",
} as const

export default fontSize
````

And I would like to be able to compose final configuartion file using something like this inside my tailwind.config.js

```js
const fontSize = require("./src/utils/tailwind-theme")

module.exports = {
  theme: {

    fontSize,

    extend: {
    },
  },
  plugins: [require("tailwindcss-elevation")(["responsive"])],
}

```

Unfortunately every time I try to require a file I get the following error.

![Screenshot from 2020-04-20 18-47-03](https://user-images.githubusercontent.com/38068033/79777583-c2088680-8337-11ea-8580-bf79d8407b2d.png)

Is there a way to solve this issue?

**Comment by rbutera** [comment]
Can you create a reproduction repository as without one this is hard to test.

As far as I am aware, there should be no issues with doing this but I may be wrong (@ben-rogerson?)

**Comment by progexplorer24** [comment]
Thanks for the quick response:

Sure, here's a reproduction repository: [Tailwind conig issue](https://github.com/explorer-boilerplates/twin-macro-issue)

**Comment by ben-rogerson** [comment]
I was able to get this working by specifying the filetype on those requires in your `tailwind.config.js`:

```js
const fontSize = require("./partials/font-size.ts")
const borderRadius = require("./partials/border-radius.ts")
const screens = require("./partials/screens.ts")
```

But there are some other errors in that TypeScript repo after that. 

When trying to use

```js
<div
      css={css`
        ${tw`text-red-500 bg-red-200 elevation-13`}
      `}
    >
```

I'm getting:

```bash
twin.macro: Unexpected identifier
```

Is that something to do with TypeScript?
It's working fine in my non-typescript Gatsby tests.

**Comment by progexplorer24** [comment]
As a workaround I was able to get it to work by dropping the esmodule import/export syntax inside my partial files and use `.js` files instead of `.ts`. 

 When I use `module.exports` to import objects containing configuration everything is working as expected.

Thanks again for your help.

I'm closing the issue because I found the alternative solution that satisfies my use case.
