### ISSUE TITLE
Extend with same firstname color declared but, Twin's said not found.

### ISSUE THREAD

**Issue by naufaldi** [ben-rogerson/twin.macro#424]
So, i am trying to extends some color, name it 'green-light'. But, strangely said its not found but advice from Twin's can recognize it.
Here my error.
<img width="959" alt="Screen Shot 2021-05-03 at 10 31 37" src="https://user-images.githubusercontent.com/13159420/116839004-c4641880-abfa-11eb-97d6-dd059bee59ac.png">

` bg-green-light-300 was not found

Try one of these classes:
bg-green-light-300 ["hsla(107, 96%, 79%, 1)"] / bg-green-light-100 ["hsla(106, 100%, 96%, 1)"]
bg-green-light-200 ["hsla(106, 94%, 94%, 1)"] / bg-green-light-50 ["hsla(104, 100%, 98%, 1)"]
bg-green-300 ["hsla(154, 69%, 55%, 1)"] / bg-green-dark-300 ["hsla(162, 71%, 43%, 1)"]
bg-green-100 ["hsla(154, 70%, 91%, 1)"] / bg-green-200 ["hsla(154, 71%, 87%, 1)"]
bg-green-400 ["#34d399"] / bg-green-500 ["#10b981"] / bg-green-600 ["#059669"]
bg-green-700 ["#047857"] / bg-green-800 ["#065f46"] / bg-green-900 ["#064e3b"]
    at Array.reduce (<anonymous>)
    at Array.forEach (<anonymous>)
                                                                             `
my Tailwind Config.
<img width="678" alt="Screen Shot 2021-05-03 at 10 29 30" src="https://user-images.githubusercontent.com/13159420/116838936-80711380-abfa-11eb-942f-067d4de5979f.png">

The problem is not just extends `green-light`, but `green-dark` too.But, its work if just `green` Its look like if we has same colors extends filename, its become not found. 

problem can be solve if place colors, in `Theme` , not in `extend`.
update: 
i cant use `green-dark` if place colors in `Theme` but can use `green-light` and `green`
Thanks you

**Comment by ben-rogerson** [comment]
Twin has had some improvements in this area recently, so you'll want to be on the latest version (`twin.macro@2.4.1`).

I've tested the following config and didn't find any issues:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        "green-light": { 200: "hsla(106, 94%, 94%, 1)" },
      },
    },
  },
};
```

```js
// app.js

import tw from "twin.macro";

tw`bg-green-light-200`;

// ↓ ↓ ↓ ↓ ↓ ↓

({
  "backgroundColor": "hsla(106, 94%, 94%, 1)"
});
```

Closing this for now, feel free to reopen if you're seeing issues here on the latest version.
