### ISSUE TITLE
Twin + @compiled/css-in-js support

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#43]
There's a newer CSS in JS library, [compiled-css-in-js](https://github.com/atlassian-labs/compiled-css-in-js) released by Atlassian that's jumped up in popularity recently.

Is anyone interested in seeing how it can be used with Twin?

**Comment by cmonteiro128** [comment]
I would like to see this

**Comment by ben-rogerson** [comment]
I agree there - I've got plans to add TypeScript versions of all the starters

**Comment by zaguiini** [comment]
I'm very interested in this. I'm actually even more interested on how to use the `tw` prop with `compiled-css-in-js`.

**Comment by ben-rogerson** [comment]
Update: After hitting some compat issues [I've opened an issue with compiled-css-in-js](https://github.com/atlassian-labs/compiled-css-in-js/issues/222).
