### ISSUE TITLE
Styles declared with "can-hover" are always visible instead of becoming visible on hover

### ISSUE THREAD

**Issue by wittenbrock** [ben-rogerson/twin.macro#430]
Hey there,

Thanks for making this awesome package! Twin.macro is definitely my preferred way to manage and use Tailwind CSS.

### Bug

I've run across a small bug using the variant `can-hover`. When I declare styles with `can-hover` they are always visible. The correct behavior would for the hover styles to become visible only when I hover over an element.

### Example
If I create a button like this:

```html
<button tw="bg-blue-600 can-hover:bg-blue-700">Click me!</button>
```

**Expected behavior:**
In its default state, the button should have a background color of `blue-600`. When I hover it, the background color should become `blue-700`.

**Current behavior:**
The button always has a background color of `blue-700`, overriding the default state.

### Dependencies
Node: 16.0.0
NPM: 7.10.0

@emotion/react: 11.1.5
@emotion/styled: 11.3.0
react: 16.14.0
tailwindcss: 2.1.2
twin.macro: 2.4.0

**Comment by ben-rogerson** [comment]
Thanks for the great bug report.

> Thanks for making this awesome package! Twin.macro is definitely my preferred way to manage and use Tailwind CSS.

Glad you're enjoying it 👍 

> In its default state, the button should have a background color of blue-600. When I hover it, the background color should become blue-700.

The `can-hover:` variant is for "sniffing" whether the users main input supports :hover ([source](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover)).

If that's what you're after, then change to `can-hover:hover:bg-blue-700`.
Otherwise, if it's just a hover you want then use `hover:bg-blue-700`.

**Comment by wittenbrock** [comment]
Ohhh, I see. `can-hover:` is a media query, not a selector.

Thanks for clarifying!
