### ISSUE TITLE
Theme template literals don't smoothly handle DEFAULT values from the Tailwind config

### ISSUE THREAD

**Issue by j0hnm4r5** [ben-rogerson/twin.macro#431]
This is more of a QOL thing than anything else, but when using the `theme` template literals (to reference a color from the Tailwind config, for example), you need to explicitly reference `DEFAULT` if trying to use the default value.

For example, my config looks like this (following the customization rules [here](https://tailwindcss.com/docs/customizing-colors#color-object-syntax)):

```js
module.exports = {
    theme: {
        colors: {
            primary: {
                DEFAULT: `var(--color-primary)`,
                dark: `var(--color-primary-dark)`,
                bright: `var(--color-primary-bright)`,
                screen: `var(--color-primary-screen)`,
            },
        },
    },
};
```

If I want to access the `DEFAULT` primary color in my code (`var(--color-primary)`), I would expect to be able to do:

```js
import { theme } from "twin.macro";
const color = theme`colors.primary`;
```

But in reality, I have to do:

```js
import { theme } from "twin.macro";
const color = theme`colors.primary.DEFAULT`;
```

**Comment by ben-rogerson** [comment]
I agree that DEFAULT shouldn't need to be added with the theme import.

I'll add this to a future release 👍

**Comment by ben-rogerson** [comment]
Fixed in twin.macro@2.6.1 🎉
