### ISSUE TITLE
Dynamic change of class for dark mode failed

### ISSUE THREAD

**Issue by pandanoir** [ben-rogerson/twin.macro#441]
# Demo
https://github.com/pandanoir/twin.examples

# Environment
- react: 17.0.2
- postcss: 7.0.35
- styled-components: 5.3.0
- tailwindcss: npm:@tailwindcss/postcss7-compat@2.0.2
- twin.macro: 2.4.1

# Overview

In this environment, I wrote the component like below.

```typescript
const ColoredText = styled.div<{ state: 'danger' | 'safe' | 'other' }>`
  ${({ state }) =>
    state === 'safe'
      ? tw`dark:text-green-600`
      : state === 'danger'
      ? tw`dark:text-red-700`
      : tw`dark:text-blue-600`}
`;
```

This component uses the color depending on the state. However, this component doesn't works correctly.

**Comment by ben-rogerson** [comment]
Thanks for the great bug report.

Does changing this to a function returning the template literal work for you?

```js
const ColoredText = styled.div<{ state: number }>(
  ({ state }) => `
  ${tw`font-bold`}
  ${
    state === 0
      ? tw`dark:text-green-600`
      : state === 1
      ? tw`dark:text-red-700`
      : tw`dark:text-blue-600`
  }
`
);
```

**Comment by pandanoir** [comment]
@ben-rogerson 
Yes, the below code has the same problem.

```typescript
const ColoredText = styled.div<{ state: number }>(({ state }) => [
  tw`font-bold`,
  state === 0
    ? tw`dark:text-green-600`
    : state === 1
    ? tw`dark:text-red-700`
    : tw`dark:text-blue-600`,
])
```

DevTool shows that same classes are generated and applied to ColoredText.

![スクリーンショット (21)](https://user-images.githubusercontent.com/2884499/119838726-97c3c800-bf3e-11eb-8094-943378aa6f20.png)

**Comment by ben-rogerson** [comment]
I'm afraid this is a known issue with styled components.
I wouldn't expect it'll be fixed any time soon as they're working on a re-write.

Duplicate #310
