### ISSUE TITLE
tw is compiled at runtime in SSR

### ISSUE THREAD

**Issue by zbeyens** [ben-rogerson/twin.macro#446]
I'm using twin.macro in a Next.js app built with docusaurus (v2.0.0-beta.0)

The problem is that when refreshing the page, we first see the page without the styles for a few ms, then it gets properly compiled.

See it in action: https://slate-plugins.udecode.io/

- styled-components
- babel config:
```
module.exports = {
  plugins: [
    'babel-plugin-twin',
    'babel-plugin-macros',
    ['styled-components', { ssr: true }],
    '@babel/plugin-transform-modules-commonjs'
  ],
  presets: [
    require.resolve('@docusaurus/core/lib/babel/preset'),
    ['@babel/preset-react', { runtime: 'automatic' }],
    '@babel/preset-typescript',
  ],
};
```

**Comment by ben-rogerson** [comment]
hey there, I've fixed the "flash of unstyled content" issue in Next.js with [a custom _document.js](https://github.com/ben-rogerson/twin.examples/blob/master/next-styled-components/pages/_document.js) - the fix for this issue sounds like it would be a similar technique.

**Comment by ben-rogerson** [comment]
I'll close this for now, but if you have some code for docusaurus, please add it here for others 👍

**Comment by zbeyens** [comment]
Thanks for the answer, I opened a docusaurus discussion to know whether there is a way to customize the document https://github.com/facebook/docusaurus/discussions/4955

**Comment by ben-rogerson** [comment]
Here's a trail I found on [the docusaurus "flash of unstyled content" issue](https://github.com/facebook/docusaurus/issues/3236#issuecomment-762398321). It looks like there may only be some hacky workarounds.

**Comment by zbeyens** [comment]
Thanks for the link, I could fix it with this [hacky way](https://github.com/facebook/docusaurus/issues/3236#issuecomment-788953743).
