### ISSUE TITLE
Support Tailwind v1.4.0

### ISSUE THREAD

**Issue by denvash** [ben-rogerson/twin.macro#45]
Tailwind had [a minor version update](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.4.0).

I can handle it, tell me if you want help with a PR.

**Comment by ben-rogerson** [comment]
That was super speedy Dennis!
Some help with the updates would be great.

Here's the new feature list - I'll keep it updated as the features roll out:

- [ ] [New `space` and `divide` layout utilities](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#new-space-and-divide-layout-utilities)<br>Accepting help
- [ ] [New `transition-delay` utilities](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#new-transition-delay-utilities)<br>Accepting help
- [x] ~~[New `group-focus` variant](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#new-group-focus-variant)~~<br>Twin had this
- [ ] [Support for specifying a default line-height for each font-size utility](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#support-for-specifying-a-default-line-height-for-each-font-size-utility)<br>Ben's on this
- [ ] [Support for breakpoint-specific padding for `container` class](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#support-for-breakpoint-specific-padding-for-container-class)<br>Ben's on this
- [ ] [Added `current` to the default color palette](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#added-current-to-the-default-color-palette)<br>Accepting help
- [ ] [New `inline-grid` utility](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#new-inline-grid-utility)<br>Accepting help
- [ ] [New `flow-root` display utility](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#new-flow-root-display-utility)<br>Accepting help
- [ ] [New `clear-none` utility](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0#new-clear-none-utility)<br>Accepting help

**Comment by denvash** [comment]
Cool, for starters I'll take "New space and divide layout utilities".

**Comment by ben-rogerson** [comment]
Only three more features left :)

**Comment by rbutera** [comment]
Crazy fast turnaround time on this issue

**Comment by ben-rogerson** [comment]
Adding support for these last three new features has been a challenge!

I've needed to add support for custom core plugins just like Tailwind.
This will make it easier to keep up with new Tailwind features in the future.

It shouldn't be too far away. I'm expecting 3-4 days.

**Comment by ben-rogerson** [comment]
Heck yeah, full support is now in v1.0.0
