### ISSUE TITLE
missing types 'styled' and 'css' export for typescript

### ISSUE THREAD

**Issue by Hengry** [ben-rogerson/twin.macro#452]
version:  `"twin.macro": "^2.5.0"`

Import `styled` and `css` works properly but typescript cannot find the type:
```js
import tw, { styled, css } from 'twin.macro';
```
return
```
Module '"twin.macro"' has no exported member 'styled'. Did you mean to use 'import styled from "twin.macro"' instead?
```

Maybe `css` and `styled` are missing in `index.d.ts`?

**Comment by ben-rogerson** [comment]
Twin passes those imports through from the css-in-js library. 
Check out these resources for the ts setup: [emotion](https://github.com/ben-rogerson/twin.examples/tree/master/vite-emotion-typescript#add-typescript-types) / [styled-components](https://github.com/ben-rogerson/twin.examples/tree/master/vite-styled-components-typescript#add-typescript-types)

**Comment by rostgoat** [comment]
@ben-rogerson I believe this is still an issue with NX. I followed your suggestion above but I am still facing the same issue.

Take a look at the [stackblitz](https://stackblitz.com/edit/github-yzwzpi-uhwrjn?file=libs/app/steps/ui/src/lib/steps.tsx).

if you run `npm start` you will see that in `libs/app/steps/ui/src/lib/steps/steps.styled.ts`, I am seeing this error. Do you know why?

🙏
