### ISSUE TITLE
Tailwind defaults are missing

### ISSUE THREAD

**Issue by mosesoak** [ben-rogerson/twin.macro#461]
Hi again @ben-rogerson in setting up Twin, I'm not seeing some important TW default styles: namely the opacity variables:
```css
  --tw-bg-opacity: 1;
  --tw-text-opacity: 1;
```

These are needed for theming with custom colors. See https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo/issues/1#issuecomment-770595786 for more detail on that.

So, your docs don't say what the correct way to import defaults are, as far as I can see? I've tried a number of things. I'm using Gatsby and their tailwind setup docs say to add this import to the top-level file (gatsby-browser.js):
```js
import 'tailwindcss/dist/base.min.css';
```

This unfortunately didn't add the opacity resets. I also notice you omit the `@tailwind` directives css file that Tailwind recommends, often called `tailwind.css` or just added to `global.css` in some examples:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Since you omit the latter in your Code Sandbox example I figure we don't need it, but I think we do need some sort of global base css import to get things to work right. If I manually add the two opacity variables to my global css things work correctly, but I imagine there are a lot of other defaults I don't know about yet as well.

Solution? Thanks!

**Comment by mosesoak** [comment]
@ben-rogerson From the info in your twin.examples repo Gatsby example I see that twin does import the TW base stylesheet, and then when I click through to it, it doesn't include those vars. So maybe this is just a TW issue. I'll close this here since it's probably not Twin's issue.

**Comment by ben-rogerson** [comment]
The `GlobalStyles` import adds all the necessary resets and tailwind preflight styles for you.

Check out the usage in the [example](https://codesandbox.io/embed/github/ben-rogerson/twin.examples/tree/master/react-emotion?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.js&theme=dark).
Check out [the example repo](https://github.com/ben-rogerson/twin.examples) for more info on specific framework implementations.

But I'm thinking twin should always merge the css opacity variable with the result of the custom color functions exposed in tailwind.config.js. Will need to look into this.

**Comment by mosesoak** [comment]
I'm having trouble figuring out where Tailwind initially supplies any top level default for that variable.

**Comment by mosesoak** [comment]
Thanks for the Gatsby example. 

There are a couple things there that are slightly confusing, not in the readme but in the example code:
- I like that you show an example of doing global styles fully in JS [here](https://github.com/ben-rogerson/twin.examples/blob/master/gatsby-emotion/src/styles/GlobalStyles.js), but wanted to point out that you don't use that in the Layout import.
- Your package.json includes `@babel/plugin-proposal-decorators` and `@emotion/babel-plugin-jsx-pragmatic` but those aren't mentioned in the readme. (?)

**Comment by ben-rogerson** [comment]
Cheers for the feedback, much appreciated :)

>I like that you show an example of doing global styles fully in JS here, but wanted to point out that you don't use that in the Layout import.

Ah damn, my example is incorrect. That Layout.js file in Gatsby should use the component from `styles/GlobalImport.js`:

```js
import React from 'react'
import GlobalStyles from './../styles/GlobalStyles'

const Layout = ({ children, ...rest }) => (
  <div {...rest}>
    <GlobalStyles />
    {children}
  </div>
)

export default Layout
```

>Your package.json includes @babel/plugin-proposal-decorators and @emotion/babel-plugin-jsx-pragmatic but those aren't mentioned in the readme. (?)

- `@babel/plugin-proposal-decorators`: I think this is a legacy package that needs to be removed from the example.
- `@emotion/babel-plugin-jsx-pragmatic`: This looks like legacy too - the `gatsby-plugin-emotion` plugin takes care of adding the css prop via [`@emotion/babel-preset-css-prop`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/src/gatsby-node.js#L3)

**Comment by ben-rogerson** [comment]
>I'm having trouble figuring out where Tailwind initially supplies any top level default for that variable. 

I don't think they do, it's added with the bg-xx/text-xx classes instead. Then when you add an opacity, it overwrites it. But with color functions in your tailwind.config.js, I think twin may need to merge it in so you don't need to add it yourself. I'll have to see if this is how tailwind is doing it.

**Comment by mosesoak** [comment]
@ben-rogerson This is a minor footnote while you're looking at precedence stuff: I'm not able to use a css var for font family in the tailwind config. I'd like to declare this in a `:root` style:
```css
  --font-primary: 'Montserrat', Sans-Serif;
```
Then in tailwind.config.js do
```js
fontFamily: {  primary: `--font-primary` }
```
And then use it in the twin-enabled GlobalStyles.tsx like,
```
body {
    font-family: ${theme`fontFamily.primary`};
}

h1 {
  ${tw`text-5xl my-2 font-secondary`}
}
```

That system works for colors but not for custom font families. 

After a lot of experiments the only thing that's currently stable is the following tailwind config, plus the body font setting in GlobalStyles (above).

```js
  theme: {
    extend: {
      fontFamily: {
        /* Set up fonts in gatsby-config.js.
           
           Quirks:
           - Global body font & hot-reload work better by setting here vs. using css vars.
           - Hot-reload works better if you don't override `sans` and `serif` fields.
        */
        //  custom fields, e.g. `tw="font-primary"` or theme`fontFamily.primary`
        primary: `'Montserrat', Sans-Serif`,
      },
```

Adding override fields like `sans: (theme) => theme('fontFamily.primary')` made fonts without specific styling revert to serif during gatsby hot-reload. But that's another side issue, the main problem was not being able to use css vars for font families, and I don't know how many of these issues are twin vs. tailwind since this is my first go-round with both.

**Comment by ben-rogerson** [comment]
This should work:


```js
// global styles
`	
	:root: { 
		${tw`--font-primary['Montserrat', Sans-Serif]`}
	}
`
```

```js
// tailwind.config.js
fontFamily: { primary: 'var(--font-primary)' }
```

```js
// usage
import tw from 'twin.macro'

tw`font-primary`
```

**Comment by mosesoak** [comment]
@ben-rogerson Interesting, that's using the "short css" syntax property[value] to declare a custom variable, I guess? Pretty weird..

Any idea why simply declaring the variable outright wouldn't work as in my example?

**Comment by ben-rogerson** [comment]
You can do it that way, thinking again on this, I'd use Vanilla CSS as the preferred usage in that root variable.

**Comment by mosesoak** [comment]
Cool, so today I'm not seeing the hot reloading glitches when setting fonts using css vars. My computer must've needed a nice long weekend: ;-) 

Thanks again for your fast replies Ben. Enjoying Twin so far!

**Comment by mosesoak** [comment]
Hey @ben-rogerson -- returning to my initial post at very top, I do think this is probably an issue that Twin should solve as you suggested. I also wanted to note that there's a border default as well. This is the patch I'm currently using:

```css
  /* Twin patch for text/border/bg colors - may be fixed in a future version */
  --tw-bg-opacity: 1;
  --tw-border-opacity: 1;
  --tw-text-opacity: 1;
```

**Comment by ben-rogerson** [comment]
Thanks for bringing this up again.

Here's the list of global variables in the latest tailwindcss:

```css
--tw-shadow: 0 0 #0000;
--tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
--tw-ring-offset-width: 0px;
--tw-ring-offset-color: #fff;
--tw-ring-color: rgba(59, 130, 246, 0.5);
--tw-ring-offset-shadow: 0 0 #0000;
--tw-ring-shadow: 0 0 #0000;
//
--tw-translate-x: 0;
--tw-translate-y: 0;
--tw-rotate: 0;
--tw-skew-x: 0;
--tw-skew-y: 0;
--tw-scale-x: 1;
--tw-scale-y: 1;
--tw-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
--tw-border-opacity: 1;
border-color: rgba(229, 231, 235, var(--tw-border-opacity));
--tw-blur: var(--tw-empty,/*!*/ /*!*/);
--tw-brightness: var(--tw-empty,/*!*/ /*!*/);
--tw-contrast: var(--tw-empty,/*!*/ /*!*/);
--tw-grayscale: var(--tw-empty,/*!*/ /*!*/);
--tw-hue-rotate: var(--tw-empty,/*!*/ /*!*/);
--tw-invert: var(--tw-empty,/*!*/ /*!*/);
--tw-saturate: var(--tw-empty,/*!*/ /*!*/);
--tw-sepia: var(--tw-empty,/*!*/ /*!*/);
--tw-drop-shadow: var(--tw-empty,/*!*/ /*!*/);
--tw-filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
--tw-backdrop-blur: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-brightness: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-contrast: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-grayscale: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-hue-rotate: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-invert: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-opacity: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-saturate: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-sepia: var(--tw-empty,/*!*/ /*!*/);
--tw-backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia);
```

and here's the current global vars in twin:

```css
--tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
--tw-ring-offset-width: 0px;
--tw-ring-offset-color: #fff;
--tw-ring-color: rgba(59, 130, 246, 0.5);
--tw-ring-offset-shadow: 0 0 #0000;
--tw-ring-shadow: 0 0 #0000;
--tw-shadow: 0 0 #0000;
```

As you can see, there are a few missing - most were added in the latest twin release which twin is going to catch up with soon. I'll make sure there's a full review of this during that project 👍

**Comment by mosesoak** [comment]
Well at least in the version I'm using those two aren't added which leads to visual bugs.

**Comment by ben-rogerson** [comment]
Could you perhaps share some example code and the twin version so I can look into this?

**Comment by rossthedevigner** [comment]
I think I'm also running into some defaults missing as discussed here: https://github.com/ben-rogerson/twin.macro/discussions/512

**Comment by ben-rogerson** [comment]
Hey check out the latest version of [twin.macro@2.7.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.7.0) - there's some missing variables added that should fix this.

**Comment by rUwminu** [comment]
Hi, I find some issues with tailwind new color palette for example amber color. I using twin.macro with styled-components. I try apply amber color, it give error of not found, but it works find apply on className.

**Comment by ben-rogerson** [comment]
@rUwminu You'll just need to import the fancy new colors from tailwind to use them:

```js
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  content: [],
  theme: {
    colors,
  }
  // ...
```

**Comment by johngilesyoder** [comment]
If I import the fancy new colors from tailwind to use them like this example, it does include all of the new colors but converts all usable color utilities to
`bg-colors-sky-500` `text-colors-white` etc.

Adding '-colors-' to each color utility. This is odd and very undesirable. Please help me understand how to include and use all of the v3 TW colors that are now included by default without having to do this workaround and change the classnames from the official documentation. Thanks!

**Comment by nathan-pham** [comment]
@johngilesyoder In some cases it seems like those color utilities don't work at all, like using `outline-colors-blue-500` or `outline-blue-500`. I don't know how I'd be able to extend these without retaining the original Tailwind syntax...

**Comment by dmoxyeze** [comment]
> If I import the fancy new colors from tailwind to use them like this example, it does include all of the new colors but converts all usable color utilities to `bg-colors-sky-500` `text-colors-white` etc.
> 
> Adding '-colors-' to each color utility. This is odd and very undesirable. Please help me understand how to include and use all of the v3 TW colors that are now included by default without having to do this workaround and change the classnames from the official documentation. Thanks!

Try this:
```
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  content: [],
  theme: {
        extend: {
           colors: {...colors}
    }
  }
```
