### ISSUE TITLE
Extra space breaking hover,focus, etc variants with Stitches

### ISSUE THREAD

**Issue by alanontheweb** [ben-rogerson/twin.macro#464]
Hello @ben-rogerson ,

When using the latest Stitches version (@stitches/react": "^0.2.0), I am experiencing this bug with utilities like `hover:` where the selector has an extra space between the class and the state. In the example below, I show the expected output from a Twin+emotion demo, and the actual output from my Stitches setup. The extra space makes it so that instead of the element getting that hover:opacity-0 change, it is actually being applied to the children of the div. This one is kind of a blocker. Hopefully you can replicate it.

**Expected output (from twin codesandbox demo)** 

```tw`hover:opacity-0`,```

![image](https://user-images.githubusercontent.com/302498/122512032-1a2f2d00-cfbd-11eb-9976-cfff7b3ea727.png)

-----

**Actual output:**
 ```tw`hover:opacity-0`,```

![image](https://user-images.githubusercontent.com/302498/122512200-5ebac880-cfbd-11eb-90b9-d72e5f0b3922.png)

**Comment by ben-rogerson** [comment]
Hey, just wondering - are you using the sassy pseudo in your twin config [like the example](https://github.com/ben-rogerson/twin.examples/blob/master/next-stitches-typescript/package.json#L4) uses?

**Comment by alanontheweb** [comment]
Ahhh, I wasn't. I had added it before but it was removed when I made some changes. Sorry about and thank you! Works as expected now :)
