### ISSUE TITLE
Support tailwindcss 2.2.2

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#465]
Time to update twin with the latest features introduced in tailwindcss@2.2.0-2.2.4.

- [x] Simple variants: `only` (only-child), ~`first-of-type`~, ~`last-of-type`~, ~`only-of-type`~, ~`target`~, ~`default`~, ~`indeterminate`~, ~`placeholder-shown`~, `autofill`, ~`required`~, ~`valid`~, ~`invalid`~, `in-range`, `out-of-range` ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4482))  ([PR](https://github.com/ben-rogerson/twin.macro/pull/477))
- [x] `first-letter` and `first-line` pseudo-elements ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4482)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/477))
- [x] `selection` variant ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4482)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/477))
- [x] Automatically add `content: ''` whenever a before or after variant is used ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4461)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/479))
- [x] `marker` variant for styling lists ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4482)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/477))
- [x] `peer-*` variants for styling sibling elements ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4556)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/480))
- [x] Shorthand color opacity syntax ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4348)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/485))
- [x] Extended arbitrary value support ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4263)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/500))
- [x] Simplified transform and filter composition ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4604)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/500))
- [x] Background origin utilities ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4117)) (Thanks to @theonesean [PR](https://github.com/ben-rogerson/twin.macro/pull/502))
- [x] Per-side border color utilities ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4404))  ([PR](https://github.com/ben-rogerson/twin.macro/pull/505))
- [x] Caret color utilities ([Ref](https://github.com/tailwindlabs/tailwindcss/pull/4499)) ([PR](https://github.com/ben-rogerson/twin.macro/pull/506))
- [x] Various smaller fixes and improvements

I'll be working my way through this list and I'll keep it up to date as the PRs go up.

**Comment by theonesean** [comment]
Hey, @ben-rogerson, I would like to try and knock out the border site color utilities this weekend. Any guidance you could provide would be appreciated!

**Comment by ben-rogerson** [comment]
@theonesean Hey sean, thanks for the offer 👍 

I just took a look at that item and can see it'll require a bit of reworking so I'll probably do that one myself.

The background origin utilities will be straightforward so jump on that one if you're keen. As they're static classes, you should only need to add them to [the staticStyles list](https://github.com/ben-rogerson/twin.macro/blob/master/src/config/staticStyles.js) + add some fixture tests.

**Comment by theonesean** [comment]
Sounds good! I can snag that!

**Comment by ben-rogerson** [comment]
The next release is coming soon, just a tad more testing first 👍

**Comment by ben-rogerson** [comment]
I've just released [twin.macro@2.7.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.7.0) which includes all the JIT features listed above 🎉
