### ISSUE TITLE
`TwComponentWrapper` not exported

### ISSUE THREAD

**Issue by faustbrian** [ben-rogerson/twin.macro#466]
I was going to type hint some functions like `const getSize = (type?: string, size?: string): TwFn & TwComponentMap & TwComponentWrapper => {` but it looks like `TwComponentWrapper` isn't an exported type. Is there any specific reason for it since all other types are exported or is there any other way to hint the type of `return tw`h-4`;`?

**Comment by ben-rogerson** [comment]
Try this:

```js
import tw, { TwStyle } from "twin.macro";

interface Map {
  [key: string]: TwStyle;
}

const sizes: Map = {
  large: tw`text-lg`,
  default: tw`text-sm`,
};

export const getSize = (type: string) => sizes[type] || sizes.default;
```

**Comment by faustbrian** [comment]
That works, thanks.
