### ISSUE TITLE
Support @emotion/css for global styles

### ISSUE THREAD

**Issue by Acidic9** [ben-rogerson/twin.macro#469]
I am using twin.macro in a Solid JS project. All has been well so far, but unfortunately the `GlobalStyles` component breaks my project as it adds imports from `@emotion/react`.

twin.macro injects two imports from `@emotion/react`: `css` and `Global`.

Perhaps you could add a new util called `injectGlobal` which uses `@emotion/css` instead.
https://emotion.sh/docs/@emotion/css#global-styles

This would allow non-react projects to still use the global styles without having `React` or `@emotion/react` as a dependency.

**Comment by ben-rogerson** [comment]
hey there Ari 👋 

I saw your solid-js project - looks great! Twin also has an open PR for "[solid-js + goober](https://github.com/ben-rogerson/twin.macro/pull/398)" I'm hoping to roll in soon.

As you already found, twin only offers the `GlobalStyles` import which enforces its use as a JSX element.

The good news is: In the next release, twin brings a new `globalStyles` import.
This import is a css object containing all the global styles - it's much more adaptable to different projects that don't require insertion into JSX + it'll allow you to manipulate the styles yourself as needed.

In `@emotion/css`, you'll be able to use `globalStyles` like this:

```js
import { injectGlobal } from '@emotion/css'
import { globalStyles } from 'twin.macro'

injectGlobal(globalStyles)
```

With `@emotion/react`:

```js
import { Global, css } from '@emotion/react'
import { globalStyles } from 'twin.macro'

;<Global styles={css(globalStyles)} />
```

With `styled-components`:

```js
import { createGlobalStyle } from 'styled-components'
import { globalStyles } from 'twin.macro'

const Styles = createGlobalStyle(globalStyles)

;<Styles />
```

With `stitches`:

```js
import { global } from '../stitches.config'
import { globalStyles } from 'twin.macro'

const styles = global(globalStyles)

styles()
```

With `goober`:

```js
import { createGlobalStyles } from 'goober/global';
import { globalStyles } from 'twin.macro'

const Styles = createGlobalStyles(globalStyles)

;<Styles />
```

**Comment by Acidic9** [comment]
Hi Ben, I noticed the star you gave my project, thank you for checking it out! : )

Seems like the next release resolves my issue entirely. If you are happy to close the issue now, that's fine.
I look forward to the new release!

*I'm sure you get this a lot, but thank you for doing such amazing work. Twin is such an awesome project. 🎈*

**Comment by ben-rogerson** [comment]
Thanks heaps Ari, so good to hear you're enjoying twin 👍 

I've just pushed a new version with the new `globalStyles` import.

I've tested the new import with `styled-components` / `@emotion/react` / `stitches` / `goober` but haven't tested with `@emotion/css`.

It should be okay as it's just an object that's output, but please let me know if there are any issues!

Usage:

```js
import { injectGlobal } from '@emotion/css'
import { globalStyles } from 'twin.macro'

injectGlobal(globalStyles)
```

PS: I'm guessing you're keen for a `solid-emotion` preset + an example or two at some stage?
Let me know whenever you're ready - I'm available in [the twin Discord channel](https://discord.gg/Xj6x9z7) anytime.

Cheers ✌️

**Comment by axe312ger** [comment]
@ben-rogerson your comment helped me out, I got confused so much why my base styles didn't get applied.

Can we move [your comment](https://github.com/ben-rogerson/twin.macro/issues/469#issuecomment-871746308) to the docs or the readme? :)
