### ISSUE TITLE
Add Typescript definitions

### ISSUE THREAD

**Issue by lukasluecke** [ben-rogerson/twin.macro#5]
Would be awesome to have both for discoverability / auto-completion, and also checking for mistakes and errors.

`@emotion/styled` has this for css properties, so we could have it for the tailwind classes 🙂 

Maybe take inspiration from https://github.com/christianalfoni/tailwindcss-classnames or https://github.com/dvkndn/typed.tw.

**Comment by ben-rogerson** [comment]
Great idea - I can see the value on the autocompletion feature. I'll put it on the cards 👍

**Comment by rbutera** [comment]
I'm down to help contribute to this, as I think that types here would be quite simple!

Can anyone find an example of typescript definitions for babel macros?

**Comment by kingdaro** [comment]
Is there any work being done on this? If not, I have some minimal incomplete typings that I wouldn't mind fixing up and making a PR for

> Can anyone find an example of typescript definitions for babel macros?

The macro part isn't important, what is:

- Typing a tagged template function
- Typing all of the `tw.xyz` styled functions
- Typing the `tw` prop

**Comment by rbutera** [comment]
Could you push these? I would love to learn from this and help you compete them

Sent via Superhuman iOS ( https://sprh.mn/?vip=rai@rbutera.com )

**Comment by kingdaro** [comment]
@rbutera Pushed! #21 The types are already mostly complete, but comments/tweaks/improvements are always welcome 🙂

**Comment by ben-rogerson** [comment]
Types are now up and running in 1.0.0-alpha.8 🎉
Thanks @kingdaro !
