### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by olegafx** [ben-rogerson/twin.macro#50]
It's not that easy to see what was changed between different releases.
I think that CHANGELOG.md would be a great addition to this project.

Thanks for your work!

**Comment by ben-rogerson** [comment]
No worries Oleg, you make a very valid point.
This has been on my todo list for a while.
I hit the pause on it because of the text duplication with my Github release notes.

**Comment by ben-rogerson** [comment]
I've decided to stick with Github releases for now, you'll see what changed between releases there.
