### ISSUE TITLE
tw and css props fully override styled(...) definition

### ISSUE THREAD

**Issue by finkef** [ben-rogerson/twin.macro#508]
I'm using twin.macro with stitches (totally love it 🎉 ) and encountering an issue when trying to add additional styles via the `tw` or `css` props:

```tsx
function Test() {
  return (
    <div>
      {/* adding the tw prop overrides all previous styles */}
      <Button tw="mx-2">I'm a button</Button>

      {/* properly styled */}
      <Button>I'm a button</Button>
      <Button variant="secondary">I'm a button</Button>
    </div>
  )
}

const Button = styled.button({
  ...tw`rounded-lg text-sm px-4 py-2 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500`,

  variants: {
    variant: {
      primary: tw`bg-blue-500`,
      secondary: tw`bg-blue-200 text-blue-800 focus:ring-blue-200`,
      outlined: tw`text-blue-500 border border-blue-500 focus:ring-offset-0`,
    },
  },
  defaultVariants: { variant: "primary" },
})
```

Not sure if this a known limitation or a bug, couldn't find anything in the docs or previous issues. I would be expecting the passed styles via `tw` or `css` to be applied *after* instead of fully overriding the styled component.

Note: For the sake of completeness, what does work is creating new styled components from the original one, but to create a new intermediary component for each time a contextual style like margin is applied, seems like the wrong solution to me.

```tsx
const ButtonWithMargin = styled(Button, {
  ...tw`mx-2`
})
```

**Comment by wmcb91** [comment]
Hi @finkef, I'm not very familiar with Stitches, but you may have a config issue interfering with twin's magic. It's tough to say without knowing what environment you're developing in, but I think `styled.button({...})` would throw an error if you were _only_ using Stitches. As they are still in Beta [the API](https://stitches.dev/docs/api) may have changed a bit, but I think you'd have to use `styled('button', {...})` to make it a Stitches component. If you have styled-components configured in your project as well (which might explain why you didn't get an error), twin could be having a tough time differentiating between Stiches and styled-components logic.

I just ran [the next-stitches-typescript example](https://github.com/ben-rogerson/twin.examples/tree/master/next-stitches-typescript) and  the example you provided ran as expected with `tw="mx-2"` adding the horizontal margin to your button but keeping the other styles.

<img width="387" alt="Screen Shot 2021-08-24 at 7 32 53 PM" src="https://user-images.githubusercontent.com/7145229/130711622-2e268274-b359-4a05-aaf2-a51af1d6726b.png">

@ben-rogerson Could probably shed more light than I can, but I'd recommend changing `styled.button({...})`  to `styled('button', {...})` and seeing how that works for you.

**Comment by pckilgore** [comment]
I'm running into the same issue without stitches.  Same reproduction as @finkef.  We have a styled heading, but when applying the `tw` prop to the styled heading, all the styles are overridden.  This is [somewhat implied as intentional by the docs here](https://github.com/ben-rogerson/twin.macro/blob/master/docs/styled-component-guide.md#overriding-styles), but I expected it to override, say, JUST the text color, not all of the styles applied to the styled component.

If that's working as intentional, is there a strategy for using the `tw` prop to extend, rather than override the style?

**Comment by s-kobets** [comment]
Hi @pckilgore I created small kit library with components used twin.macro and got this problem. For resolve this problem I used it:
`const Button = styled.button({...tw`...`})

<Button css={tw`...`}>
`
css - add priority for your styles and you get new style.

**Comment by ben-rogerson** [comment]
Looks like a good workaround, use the css prop with a nested tw block to override in stitches.
