### ISSUE TITLE
border-style causes issue pasting into Word or Outlook

### ISSUE THREAD

**Issue by PaddyMann** [ben-rogerson/twin.macro#513]
Steps to replicate:

1. Create a page with twin and add in the `GlobalStyles`
2. Select any element. Note that that the following styles are applied:
```
border-style: solid;
border-width: 0;
```
3. Copy and paste the element into MS Word or Outlook. Note that every paragraph has a border:
![image](https://user-images.githubusercontent.com/362711/130224463-cb34bdc4-2eb0-471c-b70b-45e3045cf5ca.png)

The issue can be fixed on individual elements by setting `border-style: none`.

This isn't great — is it possible to change the behavior so `border-style: solid` is only added when it's actually needed?

**Comment by ben-rogerson** [comment]
Hey there

Twin follows the same bordering techniques as tailwind with these styles, which are applied to every element.

Interestingly, I tested in MS Word 365 and the MS Word for Mac app and didn't see any borders copy across.

![image](https://user-images.githubusercontent.com/21288568/130353707-53277f2b-7e25-4ffc-86ee-5370f185d1d1.png)

As a workaround, you should be able to specify some custom css to override the behaviour by doing something like this:

```js
// In twin.macro@2.7.0
;<div css={{ '*': tw`border-[0px]` }}>...</div>

// Prior
;<div css{{ '*': tw`border-width[0px]`>...</div>
```

Word may have trouble with setting values, so you could even try a value of `none` as an alternative?

**Comment by PaddyMann** [comment]
Hi Ben,

Thanks for the review.

It is indeed a tailwind issue rather than twin — here's a video showing it in action on their own website: https://www.loom.com/share/165d1aee8ca14c2489bd554bdb0d4025

Sorry for bothering you! I'll raise it with the Tailwind team :)

Paddy

**Comment by PaddyMann** [comment]
Raised issue here: https://github.com/tailwindlabs/tailwindcss/issues/5274
