### ISSUE TITLE
Cannot use next's stitches template with  next-plugin-antd-less

### ISSUE THREAD

**Issue by thapecroth** [ben-rogerson/twin.macro#527]
I started with the template with stitches and follow the install instructions from https://github.com/SolidZORO/next-plugin-antd-less. Is there a way to use two packages at the same time?

Error massage:

> Critical dependency: the request of a dependency is an expression
> 
> ./node_modules/twin.macro/macro.js
> Critical dependency: the request of a dependency is an expression
> 
> ./node_modules/twin.macro/node_modules/babel-plugin-macros/dist/index.js
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

next.config.js

> const withAntdLess = require("next-plugin-antd-less");
> 
> module.exports = withAntdLess({
> webpack(config) {
> config.resolve.fallback = {
> fs: false,
> module: false,
> path: false,
> os: false,
> };
> return config;
> },
> });

babelrc.js

> module.exports = { presets: [["next/babel"]], plugins: [["import", { libraryName: "antd", style: true }]], };

**Comment by ben-rogerson** [comment]
It doesn't look like your `.babelrc` file is setup, you'll need to add `babel-plugin-macros`.

**Comment by ben-rogerson** [comment]
Closing this issue for now, feel free to reopen if the suggestion didn't work.
