### ISSUE TITLE
Cannot use numeric 'opacity' values for `keyframes` configuration

### ISSUE THREAD

**Issue by Nickersoft** [ben-rogerson/twin.macro#528]
Hey @ben-rogerson, 

Great job with this macro! One small issue I noticed of which I'm not sure of the cause (if it's this macro, emotion, or Tailwind)... I can't seem to use numeric opacity values in keyframes. If I do, they are stripped from the final CSS on the page.

**Example**:

`tailwind.config.js`
```
  keyframes: {
        "fade-up": {
          from: {
            transform: "translateY(0.5rem)",
            opacity: 0,
          },
          to: {
            transform: "translateY(0)",
            opacity: 1,
          },
        },
      },
      animation: {
        "fade-up": "fade-up 0.6s ease-in-out",
      },
```

produces:

```
@keyframes fade-up {
  0% {
      -webkit-transform: translateY(0.5rem);
      -moz-transform: translateY(0.5rem);
      -ms-transform: translateY(0.5rem);
      transform: translateY(0.5rem);
  }

  100% {
      -webkit-transform: translateY(1rem);
      -moz-transform: translateY(1rem);
      -ms-transform: translateY(1rem);
      transform: translateY(1rem);
  }
} 
```

yet using `opacity: '0'` and `opacity: '1'` causes these rules to appear in the above keyframe. I combed through the keyframe parsing code in the repo and couldn't find anything that would seemingly cause this... any ideas? I can post a repro if needed.

**Comment by ben-rogerson** [comment]
Hey thanks for sharing this issue.

I took a look too and can see you're right, the numeric values aren't being converted to strings.

It's either happening [here](https://github.com/ben-rogerson/twin.macro/blob/master/src/plugins/animation.js#L29) or even better, the [theme function should be patched](https://github.com/ben-rogerson/twin.macro/blob/master/src/plugins/animation.js#L25) to convert numeric values to strings.

```js
import { globalStyles } from "twin.macro";

globalStyles;

// ↓ ↓ ↓ ↓ ↓ ↓

({
  // ...
  "@keyframes fade-up": {
    "from": {
      "transform": "translateY(0.5rem)",
      "opacity": 0
    },
    "to": {
      "transform": "translateY(0)",
      "opacity": 1
    }
  }
});
```
