### ISSUE TITLE
Group variants don't respect the conditionals within styled components

### ISSUE THREAD

**Issue by xylophonehero** [ben-rogerson/twin.macro#536]
Using group variants within a condition of a styled component, makes any implementation of the styled component trigger on the group variant whether it satisfies the condition or not.

See this sandbox for a minimal replication. https://codesandbox.io/s/pedantic-driscoll-ux939?file=/src/App.js

I can see the reason for it happening is the group:hover selector is applied for the same class for both the boxes. Not sure if it's meant to be applied for the class cSHLIC instead of App__TestStyled-... as in the below. I don't know much about how styled components work so this might be a silly suggestion 😄

![image](https://user-images.githubusercontent.com/68996622/133054777-c69be392-470b-496b-a5b3-7309700034ee.png)

In a project I'm working on, we replicate container queries in a similar method - attaching a class of sm, md etc to a container depending on it's width and using custom selectors sm:, md: to style based on whether they are a descendant of an element with that class. Which means we can't use these responsive selectors within a condition of a styled component.

Thanks for your help and let me know if I can explain more or help fix the issue.

(Accidently posted in the twin.examples repo. Moving over here as it's more an issue twin.macro! 🙃 )

**Comment by ben-rogerson** [comment]
Hey Nick,
Thanks for the great bug reproduction.
I believe you've stumbled over the [styled-component bug mentioned in this issue](https://github.com/ben-rogerson/twin.macro/issues/310). 
The active fix is to either drop back to styled components 5.1.1 or switch to emotion (preferred)

Closing this as it's a duplicate, but feel free to reopen if there's still issues.

**Comment by xylophonehero** [comment]
Cheers Ben.
Wasn't sure if it was a bug in `twin.macro` or `styled-components` but thanks for pointing me to a couple of solutions!
