### ISSUE TITLE
Is it possible to use to render on node-ts?

### ISSUE THREAD

**Issue by outerlook** [ben-rogerson/twin.macro#55]
Hi! Rather than an issue, I'm raising a question.

I'm experimenting with different ways to build my emails that are sent from an express server. I was using only [nodemailer](https://nodemailer.com/about/), then I started to look for templating languages, then I thought on using react, as I already have some experience with it.

I managed to send emails with it [(using sort of this solution)](https://building.lang.ai/how-to-build-emails-with-react-fcf941b125d1), which is almost perfect, except to styling which is a mess to use inline styles.

I would really really love to use this with twin macro, inlining on "style" props with tailwind classes would be so awesome, perfect for email handling (the really only downside would be that I myself would care if some property isn't really compatible with mail).

I've spent my day trying to understand better babel/babel-macro/ts/node-ts stuff but I'm starting to think it isn't really compatible, and I'd like to know if anyone knows for sure it is or isn't...

or if you have some advice to get this workflow I'm trying to get.

* I am also using something similar to [this integration of nodemailer and react](https://github.com/mathieutu/nodemailer-react) to do this bridge.

Sending email from server is a known huge pain. It would be a breeze for people used to frontend developing to achive this workflow which is familiar, I guess.

thanks!

**Comment by rbutera** [comment]
Interesting question! I've been doing some research and it appears to me that `styled-components` in combination with `twin.macro` and using `juice` to inline CSS properties 
(https://github.com/Automattic/juice) will work for this use case.

**Comment by rbutera** [comment]
@outerlook [check out this spectrum thread](https://hyperion.alpha.spectrum.chat/react/general/how-do-you-write-emails~f60d85ff-3154-4248-86c0-cb3cae65543f)

**Comment by outerlook** [comment]
Thanks for your insight and research, @rbutera! 
With this things I can work with react with no problem.

Well, what I will write below is more on curiosity, I think this issue is closeable, as on normal setups it would definitely work.

The only thing our team's developer is struggling to do, is to convert to use babel (with typescript) instead of ts-node to be able to use twin-macro. (I'm our team's developer 😅).

I was trying to use this email service on the same node as my express api server, which was more easy to build with ts-node.

I think the solution will be deploy another node as a e-mail service only, which could use babel more easily. 

If you guess I'm a little bit lost with these compilers/transpilers stuff, you are right

Well, thanks anyway. I appreciate your help, @rbutera. :)
