### ISSUE TITLE
Stitches: jest test fail to run when there's more than two tw/css prop in a component

### ISSUE THREAD

**Issue by taneba** [ben-rogerson/twin.macro#565]
If you have more than two tw or css prop in a component, jest test (using testing-library) will fail with error `ReferenceError: _styled is not defined`

## Step to reproduce

(you can test it with my forked repo. Clone and run `yarn run test` in next-stitches-typescript folder : https://github.com/taneba/twin.examples/tree/repro-stitches-jest/next-stitches-typescript )

Let's say you have a component like:

```tsx
import 'twin.macro'

const IndexPage = () => (
  <div>
    <div tw="text-center">Hello</div>
    <div tw="text-left">Hi</div>
  </div>
)

export default IndexPage
```

And test code:

```tsx
import { render, screen } from '@testing-library/react'
import '@testing-library/jest-dom'
import IndexPage from './index'

it('renders buttons', () => {
  render(<IndexPage />)
  expect(screen.getByText('Hello')).toBeInTheDocument()
})
```

This test should be passed, but if you run test you'll get 

```
 FAIL  pages/index.test.tsx
  ● Test suite failed to run

    ReferenceError: _styled is not defined

      at Object.<anonymous> (pages/index.tsx:21:23)
      at Object.<anonymous> (pages/index.test.tsx:8:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:401:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

Interestingly, the test will be passed if you get rid of one of the `tw` prop:

```tsx
import 'twin.macro'

const IndexPage = () => (
  <div>
    <div tw="text-center">Hello</div>
    <div>Hi</div>
  </div>
)

export default IndexPage
```

**Comment by leolabs** [comment]
I've experienced this as well in a project using Next, Stitches, TypeScript, and Jest. Is there anything I could do to help fix this issue?

**Comment by wg-daniel** [comment]
Just posting this in case someone is in a similar situation. Encountered the exact same issue after doing upgrades, managed to solve it by downgrading `babel-plugin-styled-components`.

**Comment by taneba** [comment]
@wg-daniel 
Thank you for the information, but do we really need babel-plugin-styled-components with usage of stitches? cc: @ben-rogerson

**Comment by nibtime** [comment]
Hi @taneba , @leolabs, and @wg-daniel 

I just encountered this problem when setting up tests for a project. that uses twin with stitches I found a simple fix for this after some trial and error.

create a file `jest.setup.js` in your project dir and add the following
```js
import { styled } from '@stitches/react'
global._styled = styled
```

then add the following to your `jest.config.js`:

```js
 setupFilesAfterEnv: ['<rootDir>/jest.setup.js']
```

finally run `jest --clearCache`

I tested it in the reproduction of @taneba, it fixes it there as well.

**Comment by taneba** [comment]
@nibtime 
Thanks for tackling this and that seems to be a simple workaround 💯

**Comment by xylophonehero** [comment]
Also had this problem when using `twin.macro` in Storybook. Adding he following to `preview.js` seemed to fix it
```js
import { styled } from 'twin.macro'
global._styled = styled
```

**Comment by ben-rogerson** [comment]
Here's a related link to the [jest + react testing library example →](https://github.com/ben-rogerson/twin.examples/tree/master/jest-testing-typescript)
