### ISSUE TITLE
Resolve `tailwind.config.cjs` by default in ESM projects.

### ISSUE THREAD

**Issue by scott-lc** [ben-rogerson/twin.macro#567]
In an [ESM](https://nodejs.org/api/packages.html#type) project (that is `type='module'`), CommonJS/CJS like configuration files are typically written with a `CJS` extension:

```
tailwind.config.cjs
```

When using Twin in an ESM project, any existing `tailwind.config.cjs` configuration file is silently ignored as the code only attempts to resolve a `tailwind.config.js` file as seen [here](https://github.com/ben-rogerson/twin.macro/blob/ebc25b3fbe519fad276571ec522421c131b30d54/src/configHelpers.js#L26).

It would be nice if Twin was a little friendlier to ESM projects and attempted to load the a Tailwind config file with a CJS extension instead of silently ignoring it.  Tailwind added support for CJS configuration files [here](https://github.com/tailwindlabs/tailwindcss/pull/3181).

The workaround, of course, is to simply specify the path to the CJS configuration file in the macro configuration:

```
  "babelMacros": {
    "twin": {
      "config": "tailwind.config.cjs",
      "preset": "styled-components"
    }
  }
```

This works perfectly, but sadly took me a long time to debug.

**Comment by ben-rogerson** [comment]
Hey thanks for posting this request.
This sounds like a good feature to me - twin will just [need another check added here](https://github.com/ben-rogerson/twin.macro/blob/master/src/configHelpers.js#L28). 
Feel free to help out with a PR if you'd like!

**Comment by ben-rogerson** [comment]
This feature will be in the next release 🌮 🎉
