### ISSUE TITLE
tw classes within tw component not working

### ISSUE THREAD

**Issue by jahirfiquitiva** [ben-rogerson/twin.macro#575]
Hey, I'm trying to create some styled components like this...

```typescript
import tw from 'twin.macro';

const baseFieldStyles = tw`
  bg-transparent
  text-text-primary
  border
  border-divider
  rounded
  min-h-field
  px-8
  py-4
  flex-1

  hover:(border-accent-light)
  focus:(outline-accent border-accent)
  disabled:(opacity-50 pointer-events-none cursor-not-allowed)
`;

const Input = tw.input`
  ${baseFieldStyles}
`;

const TextArea = tw.textarea`
  ${baseFieldStyles}
  py-10
  resize-y
  h-full
  min-h-textarea
  max-h-textarea-max
`;
```

Is it possible to achieve something like this? because I'm currently getting this error: `Argument of type 'TwStyle' is not assignable to parameter of type 'string'.`

<img width="715" alt="Shot 2021-11-10 at 20-52-04@2x" src="https://user-images.githubusercontent.com/10360816/141222839-1ceefd22-b67b-4742-9b31-b5c2a41bd162.png">

**Comment by ben-rogerson** [comment]
Hey,

Almost, you'll need some help from the styled import though.
Here's how you'd create those Input and Textarea components:

```js
import tw, { styled } from 'twin.macro';

const baseFieldStyles = tw`...`;

const Input = styled.input(baseFieldStyles)

const TextArea = styled.textarea(() => [
	baseFieldStyles,
	tw`
		py-10
	    resize-y
	    h-full
	    min-h-textarea
	    max-h-textarea-max
	`
]
````

Check out my [styled component guide](https://github.com/ben-rogerson/twin.examples/tree/master/headlessui-typescript) for more info.

**Comment by ben-rogerson** [comment]
The `tw` import doesn't have interpolation capabilities, use `styled` or the css prop for this case 👍
