### ISSUE TITLE
styled-components: _cssPropImport is not defined

### ISSUE THREAD

**Issue by cosydney** [ben-rogerson/twin.macro#576]
Hey, 

1. I get this error in production only on vercel: _cssPropImport is not defined
2. Using styled components
3. Creating a test repo to show you how, in the meantime you can found the error on https://app.axolo.co

**Comment by TeaBough** [comment]
@cosydney see https://github.com/ben-rogerson/twin.examples/issues/77 if it helps

**Comment by TeaBough** [comment]
It's seems that it just because @ben-rogerson turned `autoCssProp` to false

**Comment by taneba** [comment]
I faced the same issue but in jest.
I solved by adding `useEsm: true` to jest.config.js:

```
  globals: {
    'ts-jest': {
      tsconfig: {
        jsx: 'react-jsx',
      },
      useEsm: true,
    },
  },
```

**Comment by cosydney** [comment]
The way I solved it thanks to @ben-rogerson was to  add addCssProp to false and to import `import 'styled-components/macro'`everywhere 

```
  "babelMacros": {
    "twin": {
      "preset": "styled-components",
      "autoCssProp": false,
      "styled": {
        "import": "default",
        "from": "styled-components"
      },
      "css": {
        "import": "css",
        "from": "styled-components"
      }
    }
  },
  ```

**Comment by TeaBough** [comment]
Thx @cosydney  but by importing `import 'styled-components/macro`, I can't do that anymore :
```
const test = (<div tw="bg-blue-500">FUFUFU</div>)
const App = () => (
  <div>
    {test}
  </div>
)
```
it get a nice `Uncaught Error: Element type is invalid: expected a string (for built-in components)...`
If I remove the import it works.

Do you have any idea why ? @cosydney @ben-rogerson  ?

**Comment by gabrielperales** [comment]
I'm facing the same issue, changing `"autoCssProp": false,` in the `babel-plugin-macros.config.js` doesn't work for me.

**Comment by RHartman99** [comment]
Also having the same issue with a new Gatsby + twin project. I have to set `autoCssProp` to false in `package.json` like  @cosydney  recommends and import `styled-components/macro` everywhere I use twin.

**Comment by ben-rogerson** [comment]
@TeaBough 
> ...by importing import 'styled-components/macro, I can't initialize an external component...

You'll need to import twin so it can run over your file, just import the package like this:  `import 'twin.macro'`

**Comment by ben-rogerson** [comment]
I'm working on identifying the cause of this issue.

Here's a few things I've found so far:

This bug only affects the combination of twin + `styled-components`.

1. A horrible temporary workaround is:
Twin config: `{ autoCssProp: false }`
Add an import to every file using twin: `import 'styled-components/macro'`

2. A better workaround:
Twin config: `{ autoCssProp: false }`
Add `babel-plugin-styled-components` as a plugin in your babel config:
```
plugins: ['babel-plugin-macros', 'babel-plugin-styled-components'],
```

Next I'll check if there's a package we can roll back to a specific version.
More soon.

**Comment by cosydney** [comment]
Hey sorry for not answering earlier, @ben-rogerson mentioned it but will make it more even more clear for future people that will land here: 

Make sure we install styled-components.macro
```
yarn add styled-components.macro
or 
npm i styled-components.macro
```

We import both those files in a components: 

```
import tw from 'twin.macro';
import 'styled-components/macro';
```
Set AutoCSSProp to false in tailwind settings, can be in a setting file or in package.json

```
"autoCssProp": false,
```

And then should work as usual !

**Comment by Wizyma** [comment]
Hello all !
I've been going crazy around this one for the last 3 days, it's a bit more tricky on my side, i do not have the issue on local, but when i'm running everything through docker on the CI that's where the issue comes in... ! 
Even worst, at some point i fixed it, runned the github actions locally with `act`, everything fine, pushed and tadaaaa issue is there ! 

And actually trying the fix of using `autoCssProps: false` and then adding the `import 'styled-components/macro';` breaks the styling (at least on my side) ! 

I am still looking for something more reliable to do but if anyone has another insight i'll gladly take it !

**Comment by vtrpldn** [comment]
@Wizyma none of the suggested fixed worked reliably for me. I ended up forcing a styled-components downgrade by adding a 

```json
  "resolutions": {
    "styled-components": "5.2.1"
  },```

to my package.json and running a fresh `yarn install`.

**Comment by Wizyma** [comment]
@vtrpldn The version downgrade of `styled-components` fixed everything, nice one ! 
Thanks !

**Comment by apuntovanini** [comment]
@ben-rogerson does this work with babel-plugin-styled-components > 2 as well?

**Comment by ben-rogerson** [comment]
Yes, tested working on babel-plugin-styled-components@2.0.2.
I'm just doing some final testing before the patch release.

**Comment by ben-rogerson** [comment]
I've added a patch for the `_cssPropImport is not defined` error in twin.macro@2.8.2
This may require you to add a plugin to bring back the css prop - [Check out my updated comment above for more details](https://github.com/ben-rogerson/twin.macro/issues/576#issuecomment-977218398).

**Comment by apuntovanini** [comment]
Thanks @ben-rogerson! Confirm it now works with very latest versions (on tailwind 3 as well)!
