### ISSUE TITLE
TW prop doesn't work after upgrade from v2.6.2 to v.2.7.0

### ISSUE THREAD

**Issue by KornelijusGlinskas** [ben-rogerson/twin.macro#586]
As the title refers to, I've been updating my packages to the latest versions and I've stumbled into tw prop issues while updating twin.macro from 2.6.2 to 2.7.0 version. Unfortunately, after the update tw prop (e.g `tw="flex"`) on the element results in HTML:
`css="[object Object]" data-tw="flex"` and styles doesn't apply. Browsing older issues, I've found that importing `import 'styled-components/macro';` fix the issue and it definitely does, but there should be another way instead of extra importing to every file as it's worked just fine while using 2.6.2 version? 

For the record, I'm already importing twin.macro package at the top:
`import tw, { css, theme } from 'twin.macro';`

I'm using gatsby with styled components (v5.3.0) and I've followed the repo setup example closely to be completely sure if I didn't miss any step.

Thanks, guys in advance for the assistance!

**Comment by ben-rogerson** [comment]
Hey there, here's some things you can try.

Update twin to latest:

```js
npm i -D twin.macro@2.8.2
```

Then add `babel-plugin-styled-components` to your babel config:

```js
{
    "plugins": [
        "babel-plugin-macros",
        "babel-plugin-styled-components"
    ],
    // ...
}
```

That plugin supplies the css prop and lets you avoid adding that macro import in every file.

**Comment by KornelijusGlinskas** [comment]
This did the trick! Thanks for the help and the really amazing project. It's only been a pleasure styling with twin.macro! Cheers :)

**Comment by ortonomy** [comment]
Also facing this problem. I think that there is a lack of a complete guide to get twin.macro workign with styled components. Seems to heavily favour emotion. and while they're very similar, I'm convinced I'm setting something up wrong. Also using gatsby.

**Comment by ortonomy** [comment]
OK, this worked: https://github.com/ben-rogerson/twin.macro/issues/586#issuecomment-991623742

Wish this was on the guide. I would never have know to do this.
