### ISSUE TITLE
Support For tailwind 3.0.X

### ISSUE THREAD

**Issue by RootAndroid58** [ben-rogerson/twin.macro#588]
tailwind 3.0.x many new features and color palette are added hope to see it in action soon 

Example Error :
`✕ bg-violet-500 was not found`
New color palette ( replaced purple to violet 😢 )

**Comment by ben-rogerson** [comment]
I've created [an issue for the v3 update](https://github.com/ben-rogerson/twin.macro/issues/589) which I'll keep updated thoughout the upgrade process.

The new colors can be used now with this config:

```js
const colors = require('tailwindcss/colors') // Be sure to upgrade `tailwindcss` to v3.

module.exports = {
  theme: {
    extend: {
      colors: {
        electric: "#db00ff",
        ribbon: "#0047ff",
        ...colors
      },
    },
  },
};
```
