### ISSUE TITLE
Tailwind v3 updates

### ISSUE THREAD

**Issue by ben-rogerson** [ben-rogerson/twin.macro#589]
We're currently testing the next major version of twin which syncs with [tailwindcss v3](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0)

Help test the next release:

```shell
npm install twin.macro@rc
```
🔥  [Bugs / Issue discussion →](https://github.com/ben-rogerson/twin.macro/discussions/679)

**Comment by prabhaw** [comment]
waiting for the update.

**Comment by gr-qft** [comment]
This is an awesome news! I'm using tailwind with stitches and can't wait for this. Thanks @ben-rogerson !

**Comment by aroc** [comment]
Just leaving a message to tell you Twin is *extremely great* and has made me love Tailwind even for larger projects, where Tailwind normally gets unwieldily. Thank you so much for your hard work on this, excited for Tailwind 3.0 support!

**Comment by RootAndroid58** [comment]
Thanks cant wait to add new features to my site :)

**Comment by MarioSerano** [comment]
Damn haha, excited for the integrations with the latest tailwindcss update! Y'all are amazing bunch 😄

**Comment by RangerCoder99** [comment]
Take all the time you need, and sorry about that crazy changelog, Thanks for all your hard work on this!

**Comment by lightyen** [comment]
Missing:

- [ ] https://github.com/tailwindlabs/tailwindcss/pull/4723

**Comment by crock** [comment]
Waiting on this update. Will it resolve this issue?
> ModuleBuildError: Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.
  js):
  TypeError: /Users/USER/Code/GitHub/SITE/src/layouts/Layout.tsx: twin.macro: Cannot read properties of undefined (reading '700') Learn more: https://www.npmjs.com/package/twin.macro

**Comment by crock** [comment]
> Waiting on this update. Will it resolve this issue?
> 
> > ModuleBuildError: Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.
> > js):
> > TypeError: /Users/USER/Code/GitHub/SITE/src/layouts/Layout.tsx: twin.macro: Cannot read properties of undefined (reading '700') Learn more: https://www.npmjs.com/package/twin.macro

Disregard this reply. It worked as normal as soon as I updated postcss and autoprefixer.

**Comment by bumi001** [comment]
> > Waiting on this update. Will it resolve this issue?
> > > ModuleBuildError: Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.
> > > js):
> > > TypeError: /Users/USER/Code/GitHub/SITE/src/layouts/Layout.tsx: twin.macro: Cannot read properties of undefined (reading '700') Learn more: https://www.npmjs.com/package/twin.macro
> 
> Disregard this reply. It worked as normal as soon as I updated postcss and autoprefixer.

I ran into the same issue with the latest versions of postcss (8.4.5), autoprefixer (10.4.1) and tailwindcss (2.2.19). What helped me fix the issue was to use the following presets section in babel.config.js:
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
    [
      "@babel/preset-react",
      { "runtime": "automatic", "importSource": "@emotion/react" }
    ],
  ],
    
See: https://emotion.sh/docs/css-prop##babel-preset

**Comment by ben-rogerson** [comment]
Hey all - just a quick update.
I've been laying some foundational features ahead of the list above. 
It has been a bit of a struggle - especially with the changes to the user plugin api - but I'm nearing the end and getting ready for tackling the list above.
Thanks for being patient 👍

**Comment by ajmalafif** [comment]
the least we can do is be patient and is there anything we can do to help @ben-rogerson? 

and also thank YOU for twin.macro!

**Comment by ben-rogerson** [comment]
@ajmalafif I'm going to update the list soon to show some of the "lower hanging" features. Once that's updated, I'll welcome any help on those.

**Comment by smugller** [comment]
Waiting for new version to!

**Comment by dbowling** [comment]
I’m new to the project, but I’d be happy to contribute a PR for border hidden utility as a first contribution. Not sure if this is where you want comments since I’m not seeing volunteers anywhere else and PRs are going through. Thanks!

**Comment by u3u** [comment]
🎉 The list seems all done! Will a new version be released in the near future? 😍

**Comment by ben-rogerson** [comment]
Yes, list is pretty much done woohoo!
Right now I'm going over the new features and testing for bugs.
If nothing pops up then its release time shortly after 👍

**Comment by ralphbrooks** [comment]
@ben-rogerson 

VERY exciting news, and it seems like a TON of work went into this. Would it be correct to assume that 2.8.2 tracks to Tailwind 2 but that the next release will have the tailwind 3 compatibility mentioned in this issue?

In the interim, is there a guide that shows how to take this repo and turn it into a npm repo to help with final testing?

**Comment by nibtime** [comment]
Thank you so much for all this work! I've been using twin.macro for ~1 year and it has been an absolute pleasure. Can't imagine using Tailwind without it anymore? 

I am really looking forward for v3 to be released ...

**Comment by ben-rogerson** [comment]
@ralphbrooks That's right, v3 Twin will track v3 Tailwindcss and contain all the features in the list above.

If you'd like to help out with testing the new features:

1. Clone twin.macro to your project folder
2. From the twin folder `npm install` and `npm run build`
3. Test from either within your own project or in the twin sandbox included in the repo:
  a) Own project: From with your own project, link the twin repo with your node_modules with:
  `npm link ../to/the/twin/folder`
  b) Twin sandbox: In the twin project, run `npm run dev` then test within `sandbox/in.js`. 
  The output is added to `sandbox/out.js`.

**Comment by raulfdm** [comment]
@ben-rogerson , what do you think about releasing a beta or a release candidate version for us testing? I think it'll be easier than cloning and linking the project locally.

To avoid pollute the `latest` tag, you can publish with `--tag rc`:

```bash
npm run publish --tag rc
```

So we people who's gonna install twin.macro by running `npm add twin.macro` will still get v2 stable version and we can run `npm add twin.macro@rc` will get v3 to test.

**Comment by ben-rogerson** [comment]
@raulfdm Sounds like a great idea.

Release candidate is up and ready for testing:

```bash
npm install twin.macro@rc
```

[Bugs / Issue discussion →](https://github.com/ben-rogerson/twin.macro/discussions/679)

**Comment by nilsborg** [comment]
@ben-rogerson thank you (and everyone involved) so much for this huge effort! We're very much looking forward for the release! ❤️

**Comment by mosesoak** [comment]
I'm seeing this error in the console when I include `<GlobalStyles />`:

```
You have illegal escape sequence in your template literal, most likely inside content's property value.
Because you write your CSS inside a JavaScript string you actually have to do double escaping, so for example "content: '\00d7';" should become "content: '\\00d7';".
```

**Comment by JPrisk** [comment]
wanted to test out the latest release but ran into a node version mismatch, this package requires `>=16.14.2` - in my case the current node version that Vercel supports is `16.14.0` [reference](https://vercel.com/changelog/node-js-16-lts-is-now-available)

I suspect many others will be wanting to deploy to Vercel once twin.macro v3 is merged and was wondering if there are language specific features that require the minor version or... if this 16.x could be supported. Obviously this is a bit of an aside, and with time Vercel will catch up...

**Comment by alexluong** [comment]
Hi there, I'm trying out `twin.macro@3.0.0-rc.2` and everything works very smoothly. However, I'm unable to deploy my project to Vercel as their Node version is 16.0 while the Twin requires `>=16.14.2`. I'm just wondering if there's a fix for this on my side or if there's anything to do to fix the issue.

Thanks a lot for your work on this package and I'd love to make it work with our project.

**Comment by wottpal** [comment]
@alexluong as a workaround you can also install dependencies with ignoring engines (needed that for vercel before)

**Comment by fini** [comment]
Just tried out RC-3 (to see if it has fixed some issues I am having with pseudo class :after in DaisyUI), and I noticed all fonts in daisyUI themes were now using Times, I then tried RC-2 and this does not happen here, fonts are loading and working fine.

**Comment by FranciscoKloganB** [comment]
Hello @ben-rogerson can you see my open [discussion](https://github.com/ben-rogerson/twin.macro/discussions/719) inside your repository?

To my understanding `GlobalStyles` provided by "twin.macro" should have the same preflight styling as the official `@tailwind base` preflight, however, when I use one versus the other, the output I get on my existing styles (styled using TailwindCSS v3 only), the rendered output is not the same on my input fields (search and newsletter subscription form). I installed your latest release candidate to ensure I am supporting TailwindCSS v3 classes (not entirely sure if I am using any tho).

Do you have any idea how I can fix or work around this issue? I am not a CSS nor Tailwind expert, hence I am kind of lost on this subject.

**Comment by ben-rogerson** [comment]
📢 I've left a new update in the description

**Comment by chriskjaer** [comment]
We just switched all of landfolk.com (3 different sites in a huge monorepo) to twin.macro@3.0.0-rc.3 a few weeks ago and everything is running smoothly. Looking forward to the final release 🎉

**Comment by IgnusG** [comment]
> 

This is actually a cool website in and of itself. Good job on the transition 👍

**Comment by snc** [comment]
I've just tried the latest twin.macro@rc together with https://github.com/tailwindlabs/tailwindcss-aspect-ratio. The aspect ratio plugin adds `aspect-w-*` and `aspect-h-*` classes, but twin.macro says that those classes do not exists and suggests the `aspect-*` classes instead. Maybe https://github.com/ben-rogerson/twin.macro/pull/626 has something to do with this case?

**Comment by ben-rogerson** [comment]
@snc I've just tested in the next `rc` (due out shortly) and those classes are confirmed working 🎉

**Comment by ben-rogerson** [comment]
`rc.4` is now out and I've updated the base post above.
🤞 hoping it's the last `rc` before the next major release

Found an issue? [Let me know in this discussion →](https://github.com/ben-rogerson/twin.macro/discussions/679)

Enjoy 🎉

**Comment by ben-rogerson** [comment]
**`twin.macro@3.0.0` has now been released! 🥳 🎉**

```shell
npm i twin.macro@latest
```

Thank you so so much to everyone who helped out with the bug testing 👋
