### ISSUE TITLE
--tw-transform is not defined

### ISSUE THREAD

**Issue by pandanoir** [ben-rogerson/twin.macro#590]
# Bug

I tried [Getting started with vite and styled-components](https://github.com/ben-rogerson/twin.examples/tree/master/vite-styled-components-typescript) and write some code, but it doesn't work well.

`<div tw="transform translate-x-10"></div>` doesn't move because `--tw-transform is not defined`.

![スクリーンショット (86)](https://user-images.githubusercontent.com/2884499/145716442-223654b9-77cb-46a2-8382-762665aa469d.png)

# Environment

- twin.macro
- React
- Vite
- styled-components

For more details, see the repository: https://github.com/pandanoir/report-bug-for-twin-macro

# How to reproduce a bug

1. clone git repo: https://github.com/pandanoir/report-bug-for-twin-macro
2. npm install
3. npm run dev

**Comment by dwhiteGUK** [comment]
Have you seen this thread https://gitmemory.cn/repo/ben-rogerson/twin.macro/issues/542 - I was having a similar issue with Next.js + Emotion and that fixed it for me

**Comment by pandanoir** [comment]
Awesome! I added `<GlobalStyles />` and then the problem is resolved. Thanks!
