### ISSUE TITLE
support custom breakpoints

### ISSUE THREAD

**Issue by bennettrogers** [ben-rogerson/twin.macro#6]
Thanks for making this module! I've been hoping to use the newer releases of Tailwind with Emotion.

I'm trying to use my custom `@screen` breakpoints with the macro, but can only seem to get the default breakpoints to work.

I'm using the approach mentioned by @llaski on [this thread](https://github.com/bradlc/babel-plugin-tailwind-components/issues/21), by calling the `_utils.stringifyScreen` function. I recognize that this may not be intended as a public function, but it does work for the default breakpoints. Is there a way to have it recognize my custom breakpoints defined under my Tailwind config?

**Comment by ben-rogerson** [comment]
Hey Benett, thanks for giving the new package a trial.

If you've added your custom breakpoints to the config then you can use them with tailwind classes as normal:

````js
tw.div`grid grid-cols-1 desktop:grid-cols-4`
````

```js
// tailwind.config.js
module.exports = {
    theme: {
        screens: {
            tablet: '640px',
            laptop: '1024px',
            desktop: '1280px'
        },
    }
}
```
Was there another reason you needed to use the stringifyScreen util?

**Comment by ben-rogerson** [comment]
If you're using them in a styled block then it's a little more complex.
You'd need to import the config and grab the screen sizes and work with them manually.
I understand this isn't ideal so I'll provide a similar function in the near future.

For now, something like this should work:

```js
// tailwind.helpers.js
import _get from 'lodash/get';
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '~./../../tailwind.config.js';
const { theme } = resolveConfig(tailwindConfig);

const SCREEN = _get(theme, 'borderColor.screens');

export { SCREEN };
```

**Comment by bennettrogers** [comment]
Thanks for replying so quickly.

I'm trying to use the `@screen` directive so that I can have a block of responsive CSS that can use styles that aren't directly supported in Tailwind (e.g. grid template areas).

I just gave your above suggestion a try, but I'm running into a problem that I've seen before: the `module.exports` vs `export default` conflict referenced in [this Tailwind issue](https://github.com/tailwindcss/tailwindcss/issues/1201).

I'll mess with it a bit more, but if I can't get this to work I may just fall back to using Tailwind separate SCSS files for cases where I need to use Tailwind directives.

Thanks again!

**Comment by ben-rogerson** [comment]
I've run into that issue before and think I fixed it with the advice on that issue.

> Adding `sourceType: 'unambiguous'` to my Babel config fixed this by allowing me to `import` a `module.exports`.

**Comment by ben-rogerson** [comment]
> I'm trying to use the `@screen` directive so that I can have a block of responsive CSS that can use styles that aren't directly supported in Tailwind (e.g. grid template areas).

Soon I'll be adding responsive tools that will support your use case.

I can also add support grid areas in the `tw` blocks.
With Twin, grid template areas could potentially be used like this:

```js
const Button = tw`lg:grid-areas-desktop`
```

```js
module.exports = {
  theme: {
    gridTemplateAreas: {
      "desktop": "'z z z' 'a b c' 'd e f'",
    }
  }
};
```

I'm not sure why grid template areas isn't added in Tailwind yet as it seems like a quick addition.

**Comment by ben-rogerson** [comment]
Take a look at the [react-tailwind-emotion-starter](https://codesandbox.io/s/react-tailwind-emotion-starter-c5mw3) that exposes the tailwind config via the theme prop.
