### ISSUE TITLE
Can't use css= or tw= with twin.macro on my project, only tw or tw.div

### ISSUE THREAD

**Issue by dredshep** [ben-rogerson/twin.macro#601]
Hello. I'm handling a [project](https://github.com/solace-fi/solace-client) that as of now can't use css attributes in the elements such as tw= or css=, forcing me to create external elements for every style I want to apply.

It has styled-components and emotion right now for all of it, and trying to set up Tailwind, I've failed at installing pure TailwindCSS, and with twin.macro, I have failed when trying to embed attributes directly on dom elements.

Example of what I want to do:

```
<div className="text-red mt-10 text-sm">
<div tw=text-red mt-10 text-sm">
<div css={tw`text-red mt-10 text-sm`}>
```

None of those work: they don't throw a TypeError anymore (added them to tsconfig dependencies) but, when saving, they don't cause any results/changes to the css, and I don't know if they even cause a change in the classes.

Example of what I do that works:

```
const MyDiv = tw.div`text-red mt-10 text-sm`
const MyDiv = styled.div`
${tw`text-red mt-10 text-sm`
`
```

Do you know what could be the cause of this, and is it a problem with the way twin.macro is compiled with webpack/babel? What can I do to fix this?

## Edit - Test results:

This input:
```
<p css={[tw`text-red-400 text-xl underline cursor-pointer bg-blue-400 p-3`]}>
  When the birbos become an undisputable truth, we will see that they were right all along, and we the
  villains.
</p>
```

Produces this when I use inspect element to see the unstyled element.
```
<p css="[object Object]" data-tw="text-red-400 text-xl underline cursor-pointer bg-blue-400 p-3">
  When the birbos become an undisputable truth, we will see that they were right all along, and we the villains.
</p>
```

![image](https://user-images.githubusercontent.com/78047001/147793135-eb2934fc-52a6-4d96-b86a-413bf45d610e.png)

This creates the exact same output:
`tw="text-red-400 text-xl underline cursor-pointer bg-blue-400 p-3"`

## Edit2: Do I need to eject to set up the `css` prop?

I'm seeing this issue: #238. I'm not really confident in being able to `npm run eject` and have a project in working state by the end of the process. Seems this is the only solution?

**Comment by ben-rogerson** [comment]
Hey there

Using CRA + Styled components is a little troublesome with the css/tw prop setup.
**I advise switching to Emotion as it works better within CRA.**

If you'd like to keep styled-components, here's what you can do:

From the [styled-components example](https://github.com/ben-rogerson/twin.examples/tree/master/cra-styled-components):

> To use the css or tw props for styling (opposed to strictly style component styling), you’ll need to import styled components in every file. This is the technique this example repo uses:
> 
> ```js
> import 'styled-components/macro'
> ```
> 
> To avoid this import annoyance, you can install [`babel-plugin-styled-components`](https://github.com/styled-components/babel-plugin-styled-components) and add it to your babel config... but there’s a catch. 
> 
> By default, CRA doesn't allow us to change the babel config but we can install a cra plugin to allow a custom babel config without ejecting:
> [craco](https://github.com/gsoft-inc/craco) / [react-app-rewired](https://github.com/timarney/react-app-rewired).
> Once that's setup, add `babel-plugin-styled-components` to your babel config.

Hope that helps!
