### ISSUE TITLE
Default border color of tailwind dont match with twin.macro

### ISSUE THREAD

**Issue by azharakbar** [ben-rogerson/twin.macro#609]
Hi,

The default border color in TailwindCSS v3.0 is 
```css
border-color: rgb(229 231 235 / var(--tw-border-opacity));
```
But in twin.macro @ v2.8.2,
it is 
```css
border-color: currentColor;
```

Please fix this

Sample Code
```css
export const StyledElement= tw.a`
    border
`;
```

**Comment by azharakbar** [comment]
Or is there any workaround currently in 2.8.2 to update the defaults with Tailwind3 ?
@ben-rogerson

**Comment by zslabs** [comment]
This library is currently being updated to support Tailwind v3. For now, use a `2.x.x` version of Tailwind. Follow https://github.com/ben-rogerson/twin.macro/issues/589 for more details.

**Comment by azharakbar** [comment]
@zslabs Thanks for the update
But, which one in the list of changes that are to be done relates to the default border-color fix?

**Comment by ben-rogerson** [comment]
The default border color in twin.macro@2.8.2 is set within the global styles and it works the same way in tailwindcss@v3.

You can set it with the default value in your tailwind config:

```js
module.exports = {
  theme: {
    extend: {
      borderColor: {
        DEFAULT: 'currentColor',
      },
    },
  },
}
```
```js
import { globalStyles } from "twin.macro";
globalStyles

// ↓ ↓ ↓ ↓ ↓ ↓

"*, ::before, ::after": {
    // ...
    "borderColor": "currentColor",
    // ...
```

**Comment by azharakbar** [comment]
@ben-rogerson 
Hi,
Unfortunately, I was not able to override the defaults of ``twin.macro``

I have changed `tailwind.config.js` to update the defaults
![image](https://user-images.githubusercontent.com/10185101/149560427-78124ecc-bfdb-4aff-809a-d8ac3801d24d.png)

But still i get `currentColor` as the default from `twin.macro`
![image](https://user-images.githubusercontent.com/10185101/149560492-bcdf409f-6c4d-4442-bad7-14bb231b96e8.png)

**Comment by azharakbar** [comment]
And also, what is the usecase of `stiches` ?

**Comment by ben-rogerson** [comment]
Just came across [this patch from v3.0.12](https://github.com/tailwindlabs/tailwindcss/pull/6926/files#diff-d0363b2e64f7e7cdb4b9ba38cbc5ce90e0aa48eedc8ebd33afe83bb7627d856cR12) - the fallback was changed to currentColor.

I'll make sure this is added in the v3 updated.

Stitches is a newer css-in-js library with a different api than emotion/styled-components. Check out [their docs](https://stitches.dev/) for more.

**Comment by ben-rogerson** [comment]
Closing this for now, after the next twin update, if this still doesn't sync with the latest version of tailwindcss, feel free to reopen.
