### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by th-km** [ben-rogerson/twin.macro#61]
I'm considering twin for a Gatsby project, however I really miss the tailwind intellisense. Any idea on how I can have a similar experience? I've tried the typescript-plugin-tw-template package, but it doesn't seems to work.

**Comment by ben-rogerson** [comment]
@kingdaro might be able to help you with that one.

**Comment by kingdaro** [comment]
@th-km Verify that the plugin is set up as stated in the usage section [here](https://github.com/kingdaro/typescript-plugin-tw-template#usage). If it's still not working for you, [open an issue](https://github.com/kingdaro/typescript-plugin-tw-template/issues/new/choose) with reproduction steps (project setup, etc.)

**Comment by th-km** [comment]
@kingdaro I'll double check that, thank you.

**Comment by ben-rogerson** [comment]
Closing this now, feel free to reopen if you need.

**Comment by luknl** [comment]
Link to a discussion about this here, and specifically to a comment with a working VSCode Extension: https://github.com/ben-rogerson/twin.macro/discussions/227#discussioncomment-258981
