### ISSUE TITLE
Rotate does apply in className but not in my styled component

### ISSUE THREAD

**Issue by lambrosx77** [ben-rogerson/twin.macro#613]
Hi,

Before starting, thank you for this excellent project. It should be a default module in bigger libraries.

My project uses:
react 17
create react app 5
styled-components 5.3
tailwindcss 3 or 2.6

If I want to apply a rotation on an element:
OK: 
```
export default fucntion MyComp() {

 return (
  <div className="rotate-90" />
 );
}
```

KO:
```
const MyDiv = styled.div`
  ${tw`rotate-90`}
`;
```
or
```
const MyDiv = tw.div`rotate-90`;

export default fucntion MyComp() {

 return (
   <MyDiv />
 );
}
```

Do I miss something or is there a bug somewhere? I tried downgrading tailwindcss version to 2.6 but same result.
I can use the className workaround but it's not the purpose.

Thank you for your feedback.

**Comment by ben-rogerson** [comment]
Hey there - glad you're enjoying it :)

In twin, the filters need to have the `GlobalStyles` applied before they work. It sounds like they haven't been added yet.

[Check out this example](https://github.com/ben-rogerson/twin.examples/blob/master/cra-styled-components/src/styles/GlobalStyles.js) to see how they're added.

The next major version of twin doesn't require GlobalStyles before the filters work, but there's a bunch of stuff in the GlobalStyles that still needs to be applied - so it'll still be necessary.

**Comment by lambrosx77** [comment]
@ben-rogerson Thank you for your help, it solves my issue.

I didn't notice GlobalStyles was expected, now I see it in cra-styled-components twin examples.

Tailwind side, I add my default styles writing plugins. I'm not sure this is the best way but I have all my configuration in the same file.

Thank you again.

**Comment by ben-rogerson** [comment]
Yep, all good adding your default styles via plugins rather than in a provider 👍
