### ISSUE TITLE
Improve debugging tw prop styling

### ISSUE THREAD

**Issue by FredyC** [ben-rogerson/twin.macro#62]
When `tw` prop is used, on the output we get for example `class="App___StyledDiv-sc-1r3ydil-0 ksfoHe"`. In a bigger tree, it's impossible to identify elements like that. I am aware that's a tradeoff of not naming components.

```jsx
export default function App() {
  return (
    <div tw="max-w-md mx-auto flex p-6 bg-gray-100 mt-10 rounded-lg shadow-xl" />
  )
}
```

Unfortunately, React Devtools is not helping here either.

![image](https://user-images.githubusercontent.com/1096340/81477918-823c0d00-921a-11ea-9f2e-f33bfce08c77.png)

It would be really useful if we could see TW styles along with the resulting CSS styles.

What comes into my mind is in DEV mode to basically include `data-tw="..."` prop with an original value that wouldn't be transformed.

```jsx
<div class="App___StyledDiv-sc-1r3ydil-0 ksfoHe" data-tw="max-w-md mx-auto flex p-6 bg-gray-100 mt-10 rounded-lg shadow-xl" />
```

I assume that React Devtools can't be improved here, that would require something from SC/Emotion.

**Comment by ben-rogerson** [comment]
This could help quite a bit in debugging when using the `tw` prop.
I wonder if any [settings mentioned in the styled-components docs](https://styled-components.com/docs/tooling#better-debugging) could help you out here?

**Comment by FredyC** [comment]
Yea those settings won't really help. The `displayName` is enabled by default and you can see result above. I mean sure I get a rough idea about wrapping component, but in case it's more complicated logic then identifying elements in that component is tricky.

**Comment by ben-rogerson** [comment]
I'm aiming to add this feature - exactly as suggested - to the next version.

Here's what you'll add to the config to enable it:

```js
twin: {
    debugProp: true,
},
```

Sound good?

**Comment by FredyC** [comment]
Is it necessary to be opt-in when it happens in DEV mode only? Perhaps provide opt-out option instead of someone finds it distracting?

**Comment by ben-rogerson** [comment]
I wasn't sure how people would react to that - still thinking it over :)

Also, worth noting that with Emotion, you can [use the `css` function to "enable" source maps](https://github.com/emotion-js/emotion/issues/1235#issuecomment-549269824).
I haven't checked if it works the same with styled-components.

**Comment by FredyC** [comment]
From my experience, when you add such debug feature as opt-in, most people won't even know about its existence unless it's a newcomer who actually read docs :)

I don't think SC has any debugging capability, I did not found any. But even the emotion variant doesn't sound that useful if we are talking about identifying `tw` decorated element.

**Comment by ben-rogerson** [comment]
Alright - you talked me into it. I'll add it as an opt-out feature 👍

**Comment by ben-rogerson** [comment]
Hey Daniel, the prop is now live in [1.3.0](https://github.com/ben-rogerson/twin.macro/releases/tag/1.3.0). Hope it works well for you!

**Comment by FredyC** [comment]
I am not sure what are "potential upsets" really. How can someone be upset for easier debugging out of the box? Oh well, thanks anyway.

**Comment by fvanwijk** [comment]
Well, I want to disable this feature in my production build so if it is opt in I definitely will set this value using an environment variable. So opt in would be a more logical choice.

**Comment by FredyC** [comment]
@fvanwijk As I suggested above, it should be available in the development only. It's not needed in production so your argument is a bit off here :)

**Comment by fvanwijk** [comment]
As I was replying on the email subscription directly I didn't check this before replying, so thanks for the heads up. It is a nice feature for developers :+1:
