### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.ts(2589)

### ISSUE THREAD

**Issue by beqramo** [ben-rogerson/twin.macro#635]
Hi guys,

I'm using `react-spring` library  and it is throwing this error, I'm pretty sure it is connected  to `twin.macro`.

The exact problem description is that when I'm using `animated.*` every child component that I'm going to place inside will throw this typescript error, functionally it works.  

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/40486471/156813732-50cf788f-3e33-495f-a085-463947980f61.png">
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/40486471/156813765-6027244f-34c9-4da1-b6f0-303f699639fd.png">

I tried to wrap `tw` component inside of `animated` but same result:
```tsx
const WithAnimated = animated(tw.div``);
```

```json
{
     "dependencies": {
    "@react-spring/web": "9.4.3",
    "@types/styled-system": "5.1.15",
    "js-cookie": "^3.0.1",
    "next": "12.0.8",
    "next-seo": "4.28.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-intersection-observer": "8.33.1",
    "react-is": "17.0.2",
    "styled-components": "5.3.3",
    "styled-system": "5.1.5",
    "swiper": "8.0.6",
    "twin.macro": "2.8.2"
  },
  "devDependencies": {
    "@babel/eslint-parser": "7.15.8",
    "@next/bundle-analyzer": "12.0.8",
    "@storybook/react": "6.4.13",
    "@svgr/webpack": "5.5.0",
    "@tailwindcss/aspect-ratio": "0.3.0",
    "@types/node": "16.4.11",
    "@types/react": "17.0.15",
    "@types/styled-components": "5.1.11",
    "@types/webpack-env": "1.16.2",
    "@typescript-eslint/eslint-plugin": "5.2.0",
    "@typescript-eslint/parser": "5.2.0",
    "autoprefixer": "^9",
    "babel-loader": "^8.2.2",
    "babel-plugin-macros": "3.1.0",
    "babel-plugin-react-require": "^3.1.3",
    "babel-plugin-styled-components": "1.13.3",
    "babel-plugin-twin": "1.0.2",
    "husky": "7.0.1",
    "lint-staged": "11.2.6",
    "postcss": "^7",
    "prettier": "2.5.1",
    "rimraf": "3.0.2",
    "shx": "^0.3.3",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
    "typescript": "4.3.5",
    "eslint": "^8.9.0",
    "eslint-config-prettier": "~8.4.0",
    "eslint-config-react-app": "^7.0.0",
    "eslint-config-standard": "16.0.3",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-import-helpers": "^1.2.1",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-prettier": "~4.0.0",
    "eslint-plugin-promise": "6.0.0",
    "eslint-plugin-react": "7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0"
  }
}
```
thanks.

**Comment by ben-rogerson** [comment]
Hey there - this looks like a known issue, check [issue #1515 in react-spring](https://github.com/pmndrs/react-spring/issues/1515).

**Comment by beqramo** [comment]
thank you very much

**Comment by AnastasiiaBardyuzha** [comment]
> thank you very much

did you solve your problem?

**Comment by dimadem** [comment]
> > thank you very much
> 
> did you solve your problem?

One workaround to this problem is to disable type checking in a single file. Of course, all this is done only taking into account the rules of the game - the typing in the file will not be completely checked. You need to write ```// @ts-nocheck``` at the beginning of the file (on the first line).
