### ISSUE TITLE
Please Change TemplateFn values type

### ISSUE THREAD

**Issue by astroplex** [ben-rogerson/twin.macro#65]
After 1.0.0 release.

It works like this ⬇️

```
export type TemplateFn<R> = (
  strings: TemplateStringsArray,
  ...values: string[]
) => R
```

![image](https://user-images.githubusercontent.com/2398863/82003327-0a973380-969b-11ea-895f-3532fc157193.png)

**Comment by ben-rogerson** [comment]
Fixed in [v1.1.0](https://github.com/ben-rogerson/twin.macro/releases/tag/1.1.0)
