### ISSUE TITLE
Can’t import TwComponent for use in TypeScript interface

### ISSUE THREAD

**Issue by MatthiasDunker** [ben-rogerson/twin.macro#653]
1. In TypeScript strict mode, my app cannot compile because of “✕ Twin doesn't recognize { TwComponent }”. I need TwComponent to create an interface which will have properties with type of TwComponents.
2. ```
    "@emotion/css": "^11.7.1",
    "@emotion/react": "^11.8.2",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.8.1"```

**Comment by MatthiasDunker** [comment]
I created a [pull request](https://github.com/ben-rogerson/twin.macro/pull/654) to solve this.

**Comment by ben-rogerson** [comment]
Hey Matthias

Before I take a look into this, could you share a code example of your usage of `TwComponent`?

**Comment by MatthiasDunker** [comment]
Hey Ben,

sure. The issue in my case is the “headlessui-like“ export of components where there is one root component and the child components are properties of the root component function/class.

```typescript
import type { StyledComponent } from "@emotion/styled";
import tw, { styled } from "twin.macro";
import type { TwComponent } from "twin.macro";

export interface CardInterface extends StyledComponent<{}> {
  Image: TwComponent<"div">;
  Text: TwComponent<"div">;
  Title: TwComponent<"h3">;
  Meta: TwComponent<"p">;
}

const Card = styled.div(
  () => tw`flex flex-col elevated-layerstyle px-1.5 py-2`,
) as CardInterface;

Card.Image = tw.div`flex h-16 justify-center items-center`;
Card.Text = tw.div`flex flex-col flex-1 justify-between space-y-3`;
Card.Title = tw.h3`small-textstyle`;
Card.Meta = tw.p`tiny-textstyle text-blue-200`;

export default Card;
```
Let me know if this does make sense and is understandable.
Thank you so much for your effort.

**Comment by MatthiasDunker** [comment]
Hey Ben,
do you need more info?
Cheers!

**Comment by ben-rogerson** [comment]
Nope, all good there - just need more time!
I'm working my way though the latest tailwind updates and will circle back to this afterwards.
For now though, you should be able to copy the `TwComponent` type into your own project types file as a workaround.

**Comment by MatthiasDunker** [comment]
OffTopic: Do you have any simple tasks among the Tailwind updates that I could help with?

**Comment by ben-rogerson** [comment]
We're actually nearing the end of it 🎉   - so not much left except testing and making sure I haven't missed anything. But I'll give you a shout if something pops up, cheers for the offer 👍

**Comment by MatthiasDunker** [comment]
Sure. Put me on the list of people willing to help.

**Comment by ben-rogerson** [comment]
The `TwComponent` import is now in the v3.0.0 release candidate:

```shell
npm install twin.macro@rc
```

Closing for now, feel free to reopen if any issues.
