### ISSUE TITLE
Transform classes do not work

### ISSUE THREAD

**Issue by mohammadsiyou** [ben-rogerson/twin.macro#660]
Hi,
I try to use tailwind transform classes like [translate ](https://tailwindcss.com/docs/translate)but generated classes do not work correctly.

For example the output of the bellow code:
```Javascript
import tw from "twin.macro";

tw`translate-y-28`;
```

is:

```
({
  "--tw-translate-y": "7rem",
  "transform": "var(--tw-transform)"
});

```

expected result:

```
({
  "--tw-translate-y": "7rem",
  "transform": "translateY(var(--tw-translate-y))"
});
```

**Comment by ben-rogerson** [comment]
See attached PRs for fixes.
