### ISSUE TITLE
twin.macro errors when moving from Babel to SWC

### ISSUE THREAD

**Issue by tettoffensive** [ben-rogerson/twin.macro#664]
Something I ran into when upgrading to Next.js 12 which is moving from Babel to SWC. It seems that [emotion](https://github.com/emotion-js/emotion/issues/2467#issuecomment-1088259201) and styled-components are being ported, but twin.macro doesn't seem to work. Not sure what the issue is, as I don't really understand what moving from Babel to SWC means

```ts
error - ./node_modules/import-fresh/node_modules/resolve-from/index.js:3:0
Module not found: Can't resolve 'module'

Import trace for requested module:
./node_modules/import-fresh/index.js
./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/loaders.js
./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/index.js
./node_modules/babel-plugin-macros/dist/index.js
./node_modules/twin.macro/macro.js
./pages/_app.tsx
```

The line in my `./pages/_app.tsx` is:
```ts
import { GlobalStyles } from 'twin.macro';
```

After removing this I was also seeing errors with twin.macro's `theme`:

```
backgroundColor: twin_macro__WEBPACK_IMPORTED_MODULE_4__.theme`colors.background`
                                                                              
TypeError: twin_macro__WEBPACK_IMPORTED_MODULE_4__.theme is not a function
```

**Comment by kpratik2015** [comment]
Sadly twin.macro doesn't support SWC https://github.com/ben-rogerson/twin.macro/discussions/516#discussioncomment-2398840

**Comment by tettoffensive** [comment]
Exactly. Just wanted to note it, in hopes of it happening someday.

**Comment by ben-rogerson** [comment]
Yep big job supporting SWC Stuart - we'd need babel-plugin-macros written in Rust and then twin would need to be decoupled (split into different packages) from babel. Thinking we're more likely to get an ESBuild plugin at this stage.

Closing in favor of the [existing discussion](https://github.com/ben-rogerson/twin.macro/discussions/516#discussioncomment-2398840)

**Comment by ben-rogerson** [comment]
I've updated the twin examples with a new workaround that'll keep SWC enabled - [ref](https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components#add-the-next--babel-config)

**Comment by sebmellen** [comment]
@ben-rogerson that deserves some celebration 🙌

**Comment by fredrivett** [comment]
Updated link for those who see the above not working as expected: https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components#add-the-next-babel-config
