### ISSUE TITLE
✕ w-fit was not found . 

### ISSUE THREAD

**Issue by saurabhmehta1601** [ben-rogerson/twin.macro#683]
![Screenshot (15)](https://user-images.githubusercontent.com/57309205/167580658-db3480b2-8e71-4e78-a435-2371ebb009e8.png)

## Current Behaviour
`w-fit` property is not listed in tailwind classes recognized by twin.macro 

## Expected Behaviour 
Should not throw compilation error  .

**Comment by saurabhmehta1601** [comment]
I am using twin.macro within styled components . All other tailwind classes work fine .

**Comment by ben-rogerson** [comment]
Next version of twin includes this class 👍 

For now:

```shell
npm install twin.macro@rc
```
