### ISSUE TITLE
Error running with Jest in a NextJS project

### ISSUE THREAD

**Issue by manavda** [ben-rogerson/twin.macro#697]
Hi, I'm experiencing the old bug of 

```
MacroError: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros. This indicates that you don't have the babel plugin "babel-plugin-macros" configured correctly. Please see the documentation for how to configure babel-plugin-macros properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md
```

When running on a NextJS app. I've setup a starter project here: 

https://github.com/manavda/nextjs-typescript-starter

With this issue.

For reference my babel config file looks like this:

![image](https://user-images.githubusercontent.com/79788114/170404135-9a8b61f7-6ac5-4d3e-b7fc-7288a1626544.png)

I've spent a few days on this issue and can't seem to resolve it, any help is appreciated!

**Comment by ben-rogerson** [comment]
I took a look at the source code behind `nextJest` and saw it sets up jest to use SWC to run the tests.

Since twin is using babel, we need to tell it to use the `babel-jest` like this:

```diff
// jest.config.js

const nextJest = require('next/jest')

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './'
})

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    // Handle module aliases (this will be automatically configured for you soon)
    '^@/components/(.*)$': '<rootDir>/components/$1',

    '^@/pages/(.*)$': '<rootDir>/pages/$1'
  },
  testEnvironment: 'jest-environment-jsdom',

+  transform: {
+    '^.+\\.(js|jsx|ts|tsx|mjs)$': 'babel-jest'
+  }
}

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = createJestConfig(customJestConfig)
```

I haven't tested extensively but the existing test now passes 👍 

Closing now as any additional questions should probably go to next.

**Comment by ben-rogerson** [comment]
Here's a related link to the [jest + react testing library example →](https://github.com/ben-rogerson/twin.examples/tree/master/jest-testing-typescript)
