### ISSUE TITLE
Typings for `styled` not exported

### ISSUE THREAD

**Issue by gausie** [ben-rogerson/twin.macro#709]
```typescript
import tw, { styled } from "twin.macro";
```

Highlights that `styled` is an undefined export in TypeScript

**Comment by ImBaedin** [comment]
Have you setup the correct type file for your css-in-js library of choice? The "Get Started" section of the documentation has links to different examples. You're looking for one of the samples marked "ts".

You can then copy the "types/twin.d.ts" file into your project and that should take care of your error.
