### ISSUE TITLE
Using tailwind directives?

### ISSUE THREAD

**Issue by jesster2k10** [ben-rogerson/twin.macro#72]
First of all, thank you a million for this amazing library. 
I was wondering if it's possible to use tailwind directives inside the tw macro like `@screen` in particular? For complicated style types.

I'm using emotion + cra + typescript

**Comment by ben-rogerson** [comment]
hey Jesster!

Twin doesn't have directives or it's own media query helpers yet.
But here's a way you could do it:
1. Get your [screen sizes from your config](https://codesandbox.io/s/cra-emotion-tailwind-twin-starter-bi1kx?file=/src/components/Theme.js)
2. Create a breakpoint function and supply with your screen sizes - [there's many ways you could set this up](https://dev.to/bidah/better-reusable-media-queries-on-emotion---4dkk)
3. Add the breakpoint function to your theme provider so you can use it within your styling library

**Comment by jesster2k10** [comment]
Alright, I'll take a look at one of the approaches. Thanks for getting back to me quickly.

**Comment by timfee** [comment]
For anyone who ended up here, I ended up doing two things:

1. Using [`styled-breakpoints`](https://github.com/mg901/styled-breakpoints) alongside styled.nav:
```jsx
const Nav = styled.nav`
  ${tw`flex items-center justify-around h-16 mx-8 bg-indigo-800`}

  ${up(`sm`)} {
    ${tw`justify-center`}
  }

  ${up(`md`)} {
    ${tw`max-w-2xl mx-auto`}
  }
`;
```
2. Then, just writing the dang thing myself :)
```jsx
const Main = styled.main`
  ${tw`max-w-4xl mx-4 transition-all duration-150 ease-linear`}

  @media(min-width: 58rem) {
    ${tw`mx-auto`}
  }
`;
```
