### ISSUE TITLE
Scale not working in twin.macro like it does in tailwind

### ISSUE THREAD

**Issue by ayomtuase** [ben-rogerson/twin.macro#723]
Scale utility classes are not working in Twin.macro like it does in regular Tailwind. 

In Twin-macro, the resulting css from `scale-75`:
```
.scale-75 {
  --tw-scale-x: .75;
  --tw-scale-y: .75;
  transform: var(--tw-transform);
}
```
while in Tailwind the resulting css from `scale-75`:
```
.scale-75 {
    --tw-scale-x: .75;
    --tw-scale-y: .75;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
```
I am using emotion for the CSS-In-JS library

https://github.com/ayomtuase/react-typescript-taskify/blob/scale-twin-macro-issue/src/components/Styles.ts

**Comment by ben-rogerson** [comment]
There's a release candidate containing this feature and more from tailwind v3. 

Install with:
```js
npm i twin.macro@rc
```

**Comment by ben-rogerson** [comment]
Follow along in https://github.com/ben-rogerson/twin.macro/discussions/679
