### ISSUE TITLE
Package doesn't work with esmudule declared configuration

### ISSUE THREAD

**Issue by ninoman** [ben-rogerson/twin.macro#728]
If you declaret your tailwind.config.js file as an ES Module, twin.macro starts to throwing an error `twin.macro: Cannot use import statement outside a module`, as I discovered it resolves the config file and uses require to import it.

As tailwind works fine with ES Module declarations, I feel twin.macro should support both. 

Thank you

**Comment by ben-rogerson** [comment]
thanks - point taken - aligns with my own thoughts 👍

**Comment by spookyuser** [comment]
Thank you sm for posting this @ninoman was getting this error and was sooo confused where it was coming from
