### ISSUE TITLE
Tailwind Custom Colors Not recompiled with Twin.macro and styled component

### ISSUE THREAD

**Issue by Ysrbolles** [ben-rogerson/twin.macro#730]
I'm trying to use a custom color, but I got a problem when I change the color on the tailwind config, Twin.macro does not recompile the style,

p.s: it's worked fine when I use it with `className`

```
// tailwind.config.js
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  important: true,
  theme: {
    extend: {
      colors: {
        // primary: '#00bcd4',
        primary: '#fde047',
      },
    },
  }
}
```

```
// babel-plugin-macros.config.js
module.exports = {
  twin: {
    preset: 'styled-components',
    autoCssProp: false,
  },
}

```

```
// .babelrc.js
module.exports = {
  presets: [['next/babel', { 'preset-react': { runtime: 'automatic' } }]],
  plugins: ['babel-plugin-macros', 'babel-plugin-styled-components'],
}

```

Example of usage

```
<div className="text-primary">Hello </div> // Color change
<div tw="text-primary">#Dégage_Akhannouch</div> // Color does not change
```

**Comment by EduardoBautista** [comment]
@Ysrbolles Do you have the `twin.macro` import at the very top?

```typescript
import "twin.macro"
```

**Comment by EduardoBautista** [comment]
Are you importing the styled component globally as well?

**Comment by Ysrbolles** [comment]
Even if I import it into the file where the color change, it's still the same problem, and it's not only for storybook, even with nextJs.

**Comment by ben-rogerson** [comment]
Sometimes babel caching gets in the way, in Next you may need to break the cache sometimes by:
- stop the dev server
- remove the `.next` folder
- start the dev server

**Comment by Ysrbolles** [comment]
@ben-rogerson  I've tried doing this several times but got the same result, I'll try to create an example on `CodePen` or something, to put you in the context.

**Comment by Ysrbolles** [comment]
Hello @ben-rogerson @EduardoBautista, You can find here an example of the problem I have : 

> https://codesandbox.io/s/twin-macro-example-mnbhkv

After the project is finished the build, please try to change the color on `tailwind.config.js` 

```
// primary: "#0070f3"
primary: "#ffc107"
```

p.s: if there is a problem with `codesandbox`, check the main repository here:

> https://github.com/Ysrbolles/twin.macro-example

Thank you.

**Comment by EduardoBautista** [comment]
The sandbox changes colors correctly after updating the config.

**Comment by Mldamico** [comment]
This is happening to me. If i write a custom color in classname it works but if i want to put it inside tw i got an error (color-name was not found). This thing only happen using Vite. Doing the same with CRA works fine.

**Comment by ben-rogerson** [comment]
@Mldamico Assuming tailwindcss and twin are using the same tailwind.config, that sounds like a configuration issue.

If you're still having issues please test with the latest `rc`:

```shell
npm i twin.macro@rc
```

**Comment by Indeedornot** [comment]
> The sandbox changes colors correctly after updating the config.

Odd, for me it does not, similiar to how it is in my project

![image](https://user-images.githubusercontent.com/49447848/196045400-9a930e60-6024-4cd5-a364-395c1d967ce4.png)
![image](https://user-images.githubusercontent.com/49447848/196045406-ece9838e-72b5-438b-83e5-6e4060391688.png)
![image](https://user-images.githubusercontent.com/49447848/196045417-94b27a7b-d57d-4390-9104-1449e3fced93.png)


I even tried the rc

**Comment by ben-rogerson** [comment]
v3 has some new de-caching features - feel free to reopen if there's still issues
