### ISSUE TITLE
Having issue with Next.js v 12+

### ISSUE THREAD

**Issue by Nate93** [ben-rogerson/twin.macro#738]
Hi, I'm facing the following errors while importing twin.macro to my component

```
Module not found: Can't resolve 'module'
Import trace for requested module:
./node_modules/import-fresh/index.js
./node_modules/cosmiconfig/dist/loaders.js
./node_modules/cosmiconfig/dist/index.js
./node_modules/babel-plugin-macros/dist/index.js
./node_modules/twin.macro/macro.js
```

**packages version**      
twin.macro: ^3.0.0-rc.3 
NextJs: 12.2.5 

This error still happens even though I downgraded twin.macro version <code>to 2.8.2</code>

**Comment by theonesean** [comment]
Hm, @Nate93, it may be a Next.js webpack issue &mdash; take a look at this: https://github.com/ben-rogerson/twin.macro/discussions/219 &mdash; and see if that solves your issue.
