### ISSUE TITLE
Eslint telling me should be installed in dependencies, not devDependencies

### ISSUE THREAD

**Issue by tettoffensive** [ben-rogerson/twin.macro#74]
# Using Next.js + Emotion + twin.macro
Warning: `twin.macro' should be listed in the project's dependencies, not devDependencies.`

I'm actually a little confused, since the docs say twin.macro is a devDependency, but emotion is a dependency. And since I'm importing twin.macro into my code, shouldn't it be a dependency? Is eslint correct?

Thanks!

**Comment by rbutera** [comment]
Hi @tettoffensive, thanks for using Twin!

This error comes from the eslint rule [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md)

As you can see, generally if you `import` a dependency then it should be listed in your dependencies, not in your dev dependencies.

The [styled-components official docs](https://github.com/styled-components/styled-components) they are installing styled-components as a dependency, not a dev dependency, so I think this is even more evidence that Twin should follow suit.

Thank you for flagging this issue!
