### ISSUE TITLE
'overflow-x-auto' - this property doesn’t work in iOS browsers (Chrome/Safari)

### ISSUE THREAD

**Issue by Medkhat** [ben-rogerson/twin.macro#745]
Hi everyone! 
Thank you for such a cool tool! I couldn't figure out what the problem is. Maybe someone knows about it. Thank you a lot!

![image](https://user-images.githubusercontent.com/42961493/194740409-3e7ce5ec-7b59-45d7-98b7-0dfe31b6af95.png)

**Comment by ben-rogerson** [comment]
Hey Medkhat, do you still have this issue?

**Comment by Medkhat** [comment]
Hi! It fixed) I'm sorry, but the problem was with another part of the application. This problem affected this part in the image above.
