### ISSUE TITLE
Problem `as` and `css` when used together.

### ISSUE THREAD

**Issue by s-kobets** [ben-rogerson/twin.macro#762]
### Describe the bug

Hi, I have problem when used as and css together.

### To Reproduce

```js
import React from "react";
import tw, { styled } from "twin.macro";
import "styled-components/macro";

const StyledTag = styled.span`
  border: 1px solid black;
  ${({ theme }) => theme === "warning" && tw`text-green-500 bg-yellow-500`}
`;

function Tag(props) {
  return <StyledTag {...props} />;
}

const App = () => (
  <>
    <StyledTag as="div" theme="warning" css={{ color: "red" }}>
      Tag 3
    </StyledTag>
    <Tag as="div" theme="warning" css={{ color: "red" }}>
      Tag 4
    </Tag>
  </>
);

export default App;
```

### Expected behavior

I want to see that Tag 3 will be to the same Tag 4. Got styles for border and background

[Example](https://codesandbox.io/s/snowpack-react-styled-components-tailwind-twin-starter-forked-ug95d8?file=/src/App.js)

**Comment by ben-rogerson** [comment]
I created an example using next.js + stitches using your example and couldn't see the same issue:

![image](https://user-images.githubusercontent.com/21288568/202847605-597967d6-6bae-4b90-9497-163ccd562c3a.png)

Could you perhaps pull down this example and see if it works for you?
https://github.com/ben-rogerson/next-stitches-as-example

**Comment by s-kobets** [comment]
Hi @ben-rogerson, your example work normal, but you used component Tag from styled. When I add wrapper for Tag, I got same problem.
```jsx
const STag = styled("span", {...})
const Tag = (props) => <STag {...props} />;
```
