### ISSUE TITLE
Twin.macro syntax doesnt works on Storybook

### ISSUE THREAD

**Issue by seongminn** [ben-rogerson/twin.macro#785]
I'm using React 18 / vite / tailwindcss / twin.macro / storybook.
But It doesn’t work with this Error.

![image](https://user-images.githubusercontent.com/88662637/220099622-253e2e9e-077a-40b2-88f1-316d1a60161c.png)

I think It is because the storybook doesn't recognize syntax of twin.macro, `tw`.
It works well when I don't use twin.macro syntax(`tw`).

I really really wanna solve this error and try to do UI component testing with storybook & twin.macro. Please Help me.🥲🥲

<details>
<summary><b>this is my vite.config.ts<b></summary>
<img src="https://user-images.githubusercontent.com/88662637/220101671-b6431d4c-545e-4919-8c2d-617e04f7e46e.png" />
</details>

<details>
<summary><b>this is my main.cjs<b></summary>
<img src="https://user-images.githubusercontent.com/88662637/220102241-0869c016-18ac-4782-af4d-b387effb6ea2.png" />
</details>

<details>
<summary><b>this is my package.json<b></summary>
<img src="https://user-images.githubusercontent.com/88662637/220102571-caf23f73-a34d-498a-8d8a-27d1c7a3c793.png" />
</details>

**Comment by ben-rogerson** [comment]
You may need to set the babel config for storybook in your `main.cjs`.
Check the [emotion storybook](https://github.com/ben-rogerson/twin.examples/blob/master/storybook-emotion/.storybook/main.js) example for the config.

**Comment by seongminn** [comment]
It works well🥲

Thank you so much!!!
