### ISSUE TITLE
addUtilities is broken (unable to add responsive or hover variants)

### ISSUE THREAD

**Issue by yeungc** [ben-rogerson/twin.macro#79]
Hello! Responsive is now no longer work with addUtilities in new version of twin.macro.

I forked a codesandbox here:
https://codesandbox.io/s/next-emotion-tailwind-twin-starter-pehh1

**Comment by rbutera** [comment]
It appears that `hover` doesn't work either, interesting. Thanks for flagging this!

**Comment by ben-rogerson** [comment]
I'm working on a fix, thanks for letting me know.

**Comment by ben-rogerson** [comment]
Hey @yeungc, the fix is now live in [1.3.0](https://github.com/ben-rogerson/twin.macro/releases/tag/1.3.0)

**Comment by NikkiJonesR** [comment]
> It appears that `hover` doesn't work either, interesting. Thanks for flagging this!

I'm still experiencing this issue where pseudo elements are not being applied within the addUtilities function on version "^1.12.0". 
For example:
`'.inline-link': {
        'text-decoration': 'underline',
        '&:hover, &:focus': {
          opacity: '0.5',
        },
      },`

**Comment by NikkiJonesR** [comment]
Also noting this does however work within the addComponents function

**Comment by ben-rogerson** [comment]
@NikkiJonesR There might be some missing functionality with twin + the addUtilities function, I'll have to look into that.
For now though, use `addComponents` as you've found.

**Comment by fvanwijk** [comment]
I had the same, but I explained to myself that the difference between utilities and components is that utilities do not support those pseudo selectors. Else you would have really weird use cases like `hover:inline-link` (!), which applies hover styles, on hover.

**Comment by NikkiJonesR** [comment]
Yeah, I think in context of a addComponent it does make more sense, since that is being imported in tailwind last. The benefit is for example a button that should always have the same hover and focus state. You do not need to add 2 or 3 classes for every instance, and is less prone to error for styling inconsistencies.

**Comment by fvanwijk** [comment]
Yes in that case I also would use `addComponent`. However, when I look in the docs, also [components can have variants](https://tailwindcss.com/docs/plugins#variants-1). So in facts I'm confused again and I cannot tell the difference from a technical perspective, except for utilities being a little bit less flexible?

I find the Tailwind docs are lacking here. There are references to '`utilities` layer' and '`components` layer' but that requires developers to understand Tailwind internals, and especially devs that use twin.macro don't want to understand those internals as they are skipping the full global PostCSS build anyway.

**Comment by ben-rogerson** [comment]
I'm glad I'm not the only one confused there frank 😆 
@NikkiJonesR You probably worked it out already, but worth a quick note on it - in Twin, all the variants are always available on all your classes so you don't need to "activate" them, even in plugins. I believe this makes the `addUtilities` function somewhat useless in Twin.
