### ISSUE TITLE
The default config stub in tailwind has been renamed in v3.3.0

### ISSUE THREAD

**Issue by manojthomas13** [ben-rogerson/twin.macro#791]
It looks like the `defaultConfig.stub` imported here https://github.com/ben-rogerson/twin.macro/blob/22530e2043b681af1a4d5c9c0db98f86685b1db8/src/core/lib/util/twImports.ts#L11 has been renamed to `config.full.js` in v3.3.0, https://github.com/tailwindlabs/tailwindcss/pull/10785/files#diff-80719d2d3e7493b57a3d73a3f9fb4fda9b407d119ff73bef44ee327b50f7576aL1

Thanks a ton for `twin.macro`

**Comment by lemihthien** [comment]
the same issue

**Comment by agrattan0820** [comment]
Yep, experiencing the same issue

**Comment by ben-rogerson** [comment]
Fixed in [v.3.3](https://github.com/ben-rogerson/twin.macro/releases/tag/3.3.0) 🎉
