### ISSUE TITLE
Regression with inset on Safari 13

### ISSUE THREAD

**Issue by TeaBough** [ben-rogerson/twin.macro#799]
Hi !

When upgrading from `twin.macro` `3.1.0` to `3.3.1` I've noticed a regression in Safari 13.
With `3.1.0` 

```
tw`inset-0`
```
is transformed to : 

```css
top: 0;
bottom: 0;
right: 0;
left: 0;
```

but in `3.3.1` it is transformed to 

```
inset: 0;
```

which doesn't work on Safari 13...
I don't know if the bug comes from tailwind or twin.macro... or if it's the expected behaviour. (i'm using emotion btw)

**Comment by ben-rogerson** [comment]
Hey there

This change comes from Tailwind 3.3.0 - you can test it out in their [playground](https://play.tailwindcss.com/NzYGaeEdlq?file=css).

As for a fix, check out [10765](https://github.com/tailwindlabs/tailwindcss/pull/10765) for the update - seems there's quite a bit of activity on this issue.
