### ISSUE TITLE
Is :hocus still supported?

### ISSUE THREAD

**Issue by JohJonker** [ben-rogerson/twin.macro#80]
I see `:hocus` was removed from README, but there are still references to `group-hocus` in CHANGELOG. Is it still supported? It doesn't seem to be working for me.

This works:
```js
const ItemWrapper = styled.div([
    (props) => props.theme.PrimaryNavigation.itemWrapper, // from my Emotion theme
    css`
      &:hover ${ChildrenWrapper} {
        ${tw`bg-black!`}
      }
    `, // ChildrenWrapper is another Emotion styled component
  ]);
```

But this doesn't:
```js
const ItemWrapper = styled.div([
    (props) => props.theme.PrimaryNavigation.itemWrapper,
    css`
      &:hocus ${ChildrenWrapper} {
        ${tw`bg-black!`}
      }
    `,
  ]);
```

**Comment by ben-rogerson** [comment]
Yeah, it's still supported but you can't use it within the css blocks.

It's a variant so you prefix your class names with it:

```js
tw`hocus:bg-black`
```

But I see what you're after in your examples is `group-hocus`.
Here's how you can use it:

```js
const ItemWrapper = styled.div.attrs({ className: "group" })([
  ({ theme }) => theme.PrimaryNavigation.itemWrapper,
]);

const ChildrenWrapper = tw.div`group-hocus:bg-black`
```

**Comment by JohJonker** [comment]
Ah, I see! I did note that it's possible to import `{ css }` from `twin.macro`, but I don't think that was what confused me. It just seemed so "natural" to use `:hocus` as a native pseudo selector that I forgot that it's actually Twin black magic.

Thanks for the group-hocus heads up! I misunderstood its function, but upon a second reading, I see it's exactly what I need. 👍
