### ISSUE TITLE
Emotion + twin.macro not working in nextjs 13 app dir

### ISSUE THREAD

**Issue by ovidiuwin** [ben-rogerson/twin.macro#800]
I'm trying to use emotion with tailwindcss and twin.macro along with the new nextjs v13 app directory. I followed the example here https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion-typescript and created a withTwin file but I get the already well known error : `createContext only works in Client Components. Add the "use client" directive at the top of the file to use it`..  

If I remove `importSource: "@emotion/react"` option from babel presets then the error is gone but then the css prop is not applied correctly and I'm faced with the `You have tried to stringify object returned from css function. It isn't supposed to be used directly (e.g. as value of the className prop), but rather handed to emotion so it can handle it (e.g. as value of css prop).` which is expected since I removed the importSource.. What am I missing here?

Codesandbox: https://codesandbox.io/p/sandbox/next13-app-react-query-forked-smn5km?file=%2Fpackage.json%3A1%2C1

**Comment by Ryan-Dia** [comment]
I have encountered the same issue. As you suggested in response to issue [#788](https://github.com/ben-rogerson/twin.macro/issues/788), I tried applying `patchedDefaultLoaders.options.hasServerComponents = false`;
but the error still occurs. 
Additionally, I also tried applying the code `patchedDefaultLoaders.options.hasReactRefresh = false`, but the error persists.

<img width="935" alt="image" src="https://github.com/ben-rogerson/twin.macro/assets/76567238/6a132d33-0462-431f-bfd5-b62323da1530">

**Comment by dzcpy** [comment]
Same issue

**Comment by rezamoosavidweb** [comment]
hello , you can create a file for import third party package in next.js and add 'use client' to top of the file the export package and use it from this export : https://nextjs.org/docs/getting-started/react-essentials#third-party-packages

**Comment by sk0x0y** [comment]
> Same issue

Same issue too

**Comment by ben-rogerson** [comment]
I'm going to take another look into this soon. Will let you know of the findings.

**Comment by ben-rogerson** [comment]
Closing in favor of https://github.com/ben-rogerson/twin.macro/issues/788#issuecomment-1598404376
