### ISSUE TITLE
NX React - Module '"twin.macro"' has no exported member 'styled'

### ISSUE THREAD

**Issue by rostgoat** [ben-rogerson/twin.macro#806]
[Closed issue](https://github.com/ben-rogerson/twin.macro/issues/452)

I believe this is still an issue with NX. I followed your suggestion above but I am still facing the same issue.

Take a look at the [stackblitz](https://stackblitz.com/edit/github-yzwzpi-uhwrjn?file=libs/app/steps/ui/src/lib/steps.styled.ts).

if you run `npm start` you will see that in `libs/app/steps/ui/src/lib/steps/steps.styled.ts`, I am seeing this error. Do you know why?

side note: I am using tailwind, daisyui, react, NX
🙏

**Comment by ben-rogerson** [comment]
The project isnt reading the `twin.d.ts` file correctly.
Drop a copy of the `twin.d.ts` file into your `/apps/my-app` directory and the error is gone.
