### ISSUE TITLE
Can't resolve 'v8' (Twin + Next.js + Styled Components)

### ISSUE THREAD

**Issue by Scipion** [ben-rogerson/twin.macro#833]
Hi all,
Following the basic steps for a new Next.js + styled components in here:
https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components

I executed `pnpm create next-app` and I selected
Typescript: No
ESLint: Yes
Tailwind: No
src/ directory: Yes
App Router: Yes
import alias: No

It failed while compiling with the following error:
```
./node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/babel.js:1:104348
Module not found: Can't resolve 'v8'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/lib/index.js
./node_modules/.pnpm/tailwindcss@3.3.3/node_modules/tailwindcss/lib/lib/load-config.js
./node_modules/.pnpm/tailwindcss@3.3.3/node_modules/tailwindcss/lib/public/load-config.js
./node_modules/.pnpm/tailwindcss@3.3.3/node_modules/tailwindcss/loadConfig.js
./node_modules/.pnpm/twin.macro@3.4.0_tailwindcss@3.3.3/node_modules/twin.macro/macro.js
./src/styles/GlobalStyles.js
```
![cant_resolve_v8](https://github.com/ben-rogerson/twin.macro/assets/767358/7ce1d387-e3fc-4aef-a213-6ca670079fc6)

For some reason jiti is using `require("v8")` and it fails, but it has also some requirements for `fs`, `process` and other node libraries witch don't fail (not sure why).

There is no extra steps I can describe because I just created a brand new next project and followed the specified in here https://github.com/ben-rogerson/twin.examples/tree/master/next-styled-components

Link to the repo: https://github.com/Scipion/next-app-1

**Comment by kon-pas** [comment]
Try adding the `v8` module to the Webpack config (in `next.config.js`), like so:

```js
// next.config.js
const withTwin = require('./withTwin.js')

/**
 * @type {import('next').NextConfig}
 */
module.exports = withTwin({
  reactStrictMode: true,
  webpack: (config, { isServer }) => {
    if (isServer)
      config.resolve.fallback = {
        ...config.resolve.fallback,
        v8: require.resolve('v8'),
      }
    return config
  },
})
```

Next has adopted Webpack 5 as default, which doesn't include Node's core modules out of the box (as Webpack 4 did) and looks like Next's default Webpack config doesn't specify the `v8` module anymore, though it still includes `fs`, `process`, etc., hence no other errors.

**Comment by kon-pas** [comment]
Try adding either `macros` or `babel-plugin-macros` to the list of Babel plugins, like so:

```js
// babel.config.js
module.exports = {
  presets: ['next/babel'],
  plugins: ['macros'],
}
```

**Comment by kon-pas** [comment]
The above resolved the issue for me, but if it still persists, you can also add the `v8` module to the Webpack config, like so:

```js
// next.config.js
const withTwin = require('./withTwin.js')

/**
 * @type {import('next').NextConfig}
 */
module.exports = withTwin({
  reactStrictMode: true,
  webpack: (config, { isServer }) => {
    if (isServer)
      config.resolve.fallback = {
        ...config.resolve.fallback,
        v8: require.resolve('v8'),
      }
    return config
  },
})
```

**Comment by Scipion** [comment]
Hi @kon-pas, thanks a lot for trying to fix it.

I've applied both changes, but just with the first one I get the following error:
```
Syntax error: "next/font" requires SWC although Babel is being used due to a custom babel config being present.
Read more: https://nextjs.org/docs/messages/babel-font-loader-conflict
```
![Screenshot from 2023-10-19 11-27-58](https://github.com/ben-rogerson/twin.macro/assets/767358/5c8e5a32-5942-4159-8f87-8d2f68ec1e81)

As per what the docs explain how to resolve this new issue:

_To address this issue, **you should remove your custom Babel configuration** (e.g. .babelrc) and instead make use of the Next.js Compiler. This ensures compatibility between your Babel configuration and next/font._


By doing that we're getting back the initial error:

You can find the changes in a branch here:
https://github.com/Scipion/next-app-1/tree/fix/babel-config-n-v8-fallback

**Comment by kon-pas** [comment]
Hi @Scipion 
Remove `next/font` from `layout.js`, like so:

```js
// src/app/layout.js
import GlobalStyles from '../styles/GlobalStyles'
import StyledComponentsRegistry from '../lib/registry'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
```

`twin.macro` currently _only supports Babel_, not SWC (#516). We must choose one and if we want to use `twin.macro`, we have to stick to Babel. Next suggests to remove the Babel config, because some of Next features, like `next/font`, are intended solely for SWC. You have to get rid of those SWC-only features.

**Comment by Scipion** [comment]
So the conclusion is that whether we use `twin.macro` (and babel) or `next/font` (and swc).

I'm adding here a small research

twin.macro Support SWC discussion (thanks @kon-pas):
https://github.com/ben-rogerson/twin.macro/discussions/516

"Babel and `next/font` Conflict" in Next.js:
https://nextjs.org/docs/messages/babel-font-loader-conflict

Closing this issue due twin.macro still can't work with swc, just babel.

**Comment by anujraghuvanshi** [comment]
What is the possible solution here? to quickly fix ?

**Comment by Scipion** [comment]
> What is the possible solution here? to quickly fix ?

It seems there is no solution yet, weather you use twin.macro and babel or next/font and swc.

**Comment by anujraghuvanshi** [comment]
Can you plz help with babel config?

**Comment by Scipion** [comment]
next/font won't work with babel as explained here https://github.com/ben-rogerson/twin.macro/issues/833#issuecomment-1771166579

**Comment by hexaaagon** [comment]
Hi @kon-pas, thanks for solution. I'm having a problem after placing your solution. this is the error:
```tsx
 ⨯ ./src/app/[locale]/(pages)/page.tsx:25:36
Syntax error: Unexpected token, expected ","

  23 | import ContactSection from "./contact.sect";
  24 |
> 25 | export default function Home(request: {
     |                                     ^
  26 |   params: { locale: "id" | "en" };
  27 |   searchParams: {
  28 |     changeLang?: "true" | "false";
  ```
  
  I guess that this issue may related into my issue. When i delete the babel config, it works BUT the v8 errors come up.
