### ISSUE TITLE
Link TypeScript instructions from main README

### ISSUE THREAD

**Issue by rbutera** [ben-rogerson/twin.macro#85]
The follow up query in issue #77 has demonstrated, in my opinion, that we've not been clear enough about the need for module annotation for TypeScript projects.

I propose, as a solution, that we link directly to these documents from the README.

**Comment by ben-rogerson** [comment]
I think I'd like to have an index page for the typescript resources that the readme can link to:

So the flow would be `README.md > docs/typescript.md > docs/styled-components/typescript.md`

**Comment by ben-rogerson** [comment]
I've added this to the next version 👍
