### ISSUE TITLE
Props don't get passed down when composing components

### ISSUE THREAD

**Issue by ymslavov** [ben-rogerson/twin.macro#853]
I believe there's a bug in how nested/wrapped components pass their props. This is the setup I have.

```ts
import tw, { styled } from "twin.macro";

export const MilestoneV1 = styled.div<MilestoneProps>(({ $isActive }) => [
  $isActive && tw`bg-accent-blue-500`,
]);

export const MilestoneV2 = styled(MilestoneV1)`
  color: ${theme`colors.base.white`};
`;
```

Usage:
```
<MilestoneV2 $isActive={true} />
```

Expected behaviour:
- I'd expect the `$isActive` prop to be passed down to the wrapped `MilestoneV1` component, so that the `bg-accent-blue-500` class is applied.

Actual behavior:
- The prop is  not passed down to the wralled `MilestoneV1` component, so it's background is now applied.

Libraries:
```
"twin.macro": "^3.4.1",
"styled-components": "^6.1.8"
```

**Comment by ben-rogerson** [comment]
Hey there

I've tested and all seems to work as expected - the prop os delivered to the original component.

## Code

```ts
type MilestoneProps = {
  $isActive?: boolean
}

export const MilestoneV1 = styled.div<MilestoneProps>(({ $isActive }) => [
  $isActive && tw`bg-black`,
])

export const MilestoneV2 = styled(MilestoneV1)`
  color: white;
`

const App = () => (
  <div>
    <MilestoneV1 $isActive={true}>...</MilestoneV1>
    <MilestoneV1 $isActive={false}>...</MilestoneV1>
    <MilestoneV2 $isActive={true}>...</MilestoneV2>
    <MilestoneV2 $isActive={false}>...</MilestoneV2>
  </div>
)
```

## Result

![image](https://github.com/ben-rogerson/twin.macro/assets/21288568/32be1d7e-7157-4d1b-b428-7a1927f1c3a6)

**Comment by ymslavov** [comment]
Ok, so in my willingness to make the example as simple as possible, I kinda simplified it wrong :) Apologies for that.

Here's the actual example which is not working on my side:
```
export const MilestoneV1 = styled.div<MilestoneProps>(({ $positionPercentage }) => [
  css`
    left: ${$positionPercentage}%;
  `,
]);

export const MilestoneV2 = styled(MilestoneV1)`
  width: 44px;
  height: 44px;
  background-color: ${theme`colors.base.white`} !important;
`;
```

```
<MilestoneV2 $positionPercentage={50} />             // This results in left: %, i.e. the number is not rendered in the CSS
```

**Comment by ben-rogerson** [comment]
This is working for me - on `"styled-components": "^6.1.8"` I can see the styles popup in the styles panel:

![image](https://github.com/ben-rogerson/twin.macro/assets/21288568/832935f5-17c4-4140-96ca-b8d00994ee6b)

I used the following test code:

```js
type MilestoneProps = {
  $positionPercentage: number
}

export const MilestoneV1 = styled.div<MilestoneProps>(
  ({ $positionPercentage }) => [
    css`
      left: ${$positionPercentage}%;
    `,
  ],
)

const MilestoneV2 = styled(MilestoneV1)`
  width: 44px;
  height: 44px;
  background-color: ${theme`colors.white`} !important;
`

const App = () => (
  <div>
    <MilestoneV2 $positionPercentage={50} />
  </div>
)
```

**Comment by ymslavov** [comment]
I ran the exact same example on my end, and it doesn't render the number in the CSS.

I then managed to narrow it down to what causes it - if I remove the `$` from the prop name (i.e. `positionPercentage` instead of `$positionPercentage`) it works as expected. Which leads me to believe it may be a misconfiguration on my end.

Do you have any ideas that can point me in the right direction?

**Comment by ben-rogerson** [comment]
Perhaps you could look at [this issue about transient props](https://github.com/styled-components/styled-components/issues/3257#issuecomment-895403153), looks like a good place to start.

> ... a "transient prop" is only available on the top-level StyledComponent and no other child component. It may sometimes become available when a styled component wraps a styled component as then those two get folded together ... but otherwise the transient prop is intentionally isolated only to the StyledComponent and not passed on.
