### ISSUE TITLE
Possible to use with Laravel and typescript?

### ISSUE THREAD

**Issue by laclance** [ben-rogerson/twin.macro#88]
I have tried many setups but these warnings when using with Laravel project running yarn dev and this error:

```app.js:151605 Uncaught TypeError: twin_macro__WEBPACK_IMPORTED_MODULE_1___default.a.div is not a function```

```WARNING in ./node_modules/babel-plugin-macros/dist/index.js 78:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/twin.macro/macro.js
 @ ./resources/ts/components/Calender.tsx
 @ ./resources/ts/app.ts
 @ multi ./resources/ts/app.ts ./resources/css/app.css

WARNING in ./node_modules/twin.macro/macro.js 41:61-80
Critical dependency: the request of a dependency is an expression
 @ ./resources/ts/components/Calender.tsx
 @ ./resources/ts/app.ts
 @ multi ./resources/ts/app.ts ./resources/css/app.css

WARNING in ./node_modules/import-fresh/index.js 31:31-48
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/loaders.js
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/index.js
 @ ./node_modules/babel-plugin-macros/dist/index.js
 @ ./node_modules/twin.macro/macro.js
 @ ./resources/ts/components/Calender.tsx
 @ ./resources/ts/app.ts
 @ multi ./resources/ts/app.ts ./resources/css/app.css```

**Comment by ben-rogerson** [comment]
Hey Laclance
Twin works with Laravel, here are the steps to the setup I successfully tested:

```bash
npm i babel-plugin-macros react react-dom styled-components twin.macro
```

```js
// webpack.mix.js
mix.react('resources/js/app.js', 'public/js')
```

```js
// .babelrc
{
    "plugins": ["babel-plugin-macros"]
}
```

```js
// package.json
{
    "babelMacros": {
        "twin": {
            "preset": "styled-components",
            "autoCssProp": true
        }
    }
}
```

```js
// App.js
import React from "react";
import ReactDOM from "react-dom";
import tw from "twin.macro";

const TwProp = () => <Wrap tw="font-bold">Prop example</Wrap>;

const Wrap = tw.div`font-bold`;
const StyledComponent = () => <Wrap>Styled component example</Wrap>;

const App = () => (
    <>
        <TwProp />
        <StyledComponent />
    </>
);

ReactDOM.render(<App />, document.getElementById("app"));
```

```php
<!-- app.php -->
<!DOCTYPE html>
<html>
    <body>
        <div id="app"></div>
        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>
```

**Comment by laclance** [comment]
Thank you, sorry should have mentioned that I am using typescript, however there is one thing from your example I have not tried, the `"autoCssProp": true`

**Comment by laclance** [comment]
yup, same error, btw without ```  .webpackConfig({
    node: {
      fs: 'empty',
      module: 'empty'
    }})```
I get errors: `Can't resolve 'fs'` and `Can't resolve 'module'`

**Comment by ben-rogerson** [comment]
I've updated my setup with typescript above.

I'm getting these warnings too but not having luck getting rid of them.
I'm various issues, I'm seeing suggestions to filter them out with a webpack plugin.

Looking for help on this issue.

**Comment by laclance** [comment]
I think the problem is babel macros do not work with ts-loader so I got it working with laravel-mix using babel-loader instead by using laravel-mix-react-typescript-extension.

**Comment by ben-rogerson** [comment]
Nice one, after [reading this article](https://iamturns.com/typescript-babel/) it seems like the right way to go.

**Comment by ben-rogerson** [comment]
As a side note - I just added a repo that shows how to setup [Twin + TypeScript + Laravel](https://github.com/ben-rogerson/laravel-typescript-react-tailwind-twin)

**Comment by laclance** [comment]
Cool thanks for your help and the awesome library :) Yeah I'm surprised Laravel hasn't switch to babel or added a way to do it, I guess they don't have enough typescript users yet.
