### ISSUE TITLE
Can't change taliwind config

### ISSUE THREAD

**Issue by wispyco** [ben-rogerson/twin.macro#89]
I have the following config pointer to my tailwind.config.js file in my package.json

```
"babelMacros": {
    "twin": {
      "config":"./tailwind.config.js",
      "preset": "styled-components"
    }
  }
```

This is my tailwind.config

```
module.exports = {
  purge: [],
  theme: {
    extend: {},
    minWidth: {
      "0": "0",
      "1/4": "25%",
      "1/2": "50%",
      "3/5": "60%",
      full: "100%",
    },
  },
  variants: {},
  plugins: [],
}
```

When using `min-w-3/5` I get a compilaiton error, but `min-w-3/4` works so I think my config file isn't getting picked up. I am running gatsby and have run restarted my server and run gatsby clean, to clear the cache. Not sure what to do to get this working.

Thanks

**Comment by ben-rogerson** [comment]
Everything you've posted looks fine - here's a [working example with your setup](https://codesandbox.io/s/gatsby-styled-components-tailwind-twin-starter-xugkr?file=/src/pages/index.js)

There are some known issues with Gatsby and caching, but you can defeat the cache doing the following:

1. Make a new change in the component that's caching, this forces a fresh cache to be created

_or_

1. Remove the .cache folder
2. Restart your development server

When these issues are tackled, it should help minimise caching issue: https://github.com/ben-rogerson/twin.macro/issues/11 https://github.com/ben-rogerson/twin.macro/issues/37

**Comment by kmcaloon** [comment]
It's very strange. Even after cleaning cache and restarting sometimes the change don't show up. I have some custom utilities whose updates seem to never seem to show up on the frontend consistently.

**Comment by ben-rogerson** [comment]
Do you want to post some code up? I can take a look at it for you.

**Comment by ben-rogerson** [comment]
You could also try removing babel register:
`rm -rf ./node_modules/.cache/@babel/register`
[Source](https://github.com/kentcdodds/babel-plugin-preval/issues/19#issuecomment-513910643)

Caching is a [known issue with Babel](https://github.com/kentcdodds/babel-plugin-macros#babel-cache-problem) but it seems to affect Gatsby more than the other frameworks I've tested.

I'll close this issue for now, as we already have open issues for caching #11 #37
