### ISSUE TITLE
Cannot use macro in codesandbox

### ISSUE THREAD

**Issue by denvash** [ben-rogerson/twin.macro#9]
Trying to check the library in [a codesandbox](https://codesandbox.io/s/cra-tailwind-emotion-starter-bi1kx) leads to error, also not works [on my own example](https://codesandbox.io/s/twinmacro-example-nwdl9). 

```
Error
/index.js: Error: ENOENT: No such file or directory., '/empty.js'
```

Only works from `1.0.0-alpha.4`

**Comment by ben-rogerson** [comment]
Not quite sure how to fix this yet, it's working fine in the containerized codesandbox (the gatsby example) but the other two are having issues. I'll look into it.

**Comment by ben-rogerson** [comment]
Seems to be working now, I needed to add a `empty.js` in the root folder, then refresh, then deleted the file again. I'm thinking there was an issue with CodeSandbox 🤷

Here's [your sandbox running 1.0.0-alpha.7](https://codesandbox.io/s/twinmacro-example-erfzu)
