### ISSUE TITLE
tailwindcss as peerDependency

### ISSUE THREAD

**Issue by screendriver** [ben-rogerson/twin.macro#90]
What do you think about to declare [tailwindcss](https://www.npmjs.com/package/tailwindcss) as a `peerDependency`? With that I could use whatever version I want in my project and am not dependent on the version that `twin.macro` uses.

I could create a merge request if you want for that including updating the docs for the installation.

**Comment by ben-rogerson** [comment]
Twin doesn't use too much of tailwindcss so I don't think it would be worth adding as a peer dependency.
The two spots in the code I'm using tailwindcss code is for initially processing your tailwind.config.js and for initially processing the user plugin functions.
With that in mind, do you still think there's a case for the change?

**Comment by screendriver** [comment]
Oh, then maybe this is a miss understanding on my side. When I do a `import 'tailwindcss/dist/base.min.css` in my `gatsby-browser.js` it is the CSS file from "your" dependency. But when I think about a second time I just can install `tailwindcss` as a normal dependency in my project and it will then take this one, right?

**Comment by ben-rogerson** [comment]
Yeah you got it, when you install the custom version, you'll then import from there:

```
// After "npm i tailwindcss@[custom-version]"
- node_modules
  - tailwindcss (custom version)
  - twin.macro
    - node_modules
      - tailwindcss (v^1.4.0)
```

```js
// Custom tailwind version base
import 'tailwindcss/dist/base.min.css'
```

**Comment by screendriver** [comment]
👍
