### ISSUE TITLE
Question regarding usage with react-spring

### ISSUE THREAD

**Issue by Bowriverstudio** [ben-rogerson/twin.macro#91]
Hello and thank you for this project.  

In React-Spring I've got some syntax like:

```
const background = mode === "dark" ? "#FFF" : "#AAA";

  const animations = useSpring({
    background,
    config: config.slow,
  });

```

With the repo - https://github.com/davecalnan/tailwind-config it seems like I could import the Tailwind colors but it has dependencies that conflict with my project.

Ideally, I'd like to be able to write something like:

```
const background = mode === "dark" ? tw('gray-900'): tw('gray-500');

  const animations = useSpring({
    background,
    config: config.slow,
  });

```

Is this possible with twin.macro?

Best Regards

**Comment by ben-rogerson** [comment]
Hey there! 
Yes you can style the spring values with tailwind classes.
[Here's a code sandbox demo](https://codesandbox.io/embed/spring-cra-emotion-tailwind-twin-starter-7sk36?file=/src/App.js)

**Comment by Bowriverstudio** [comment]
Thank you that is exactly what I wanted to accomplish.
