### ISSUE TITLE
emotion + Next.js production build

### ISSUE THREAD

**Issue by pix2D** [ben-rogerson/twin.macro#93]
Hello, I am trying to convert from styled-components to emotion. In dev everything works fine.

When building for production everything builds fine (no errors), but when viewing the site half the styles are missing and upon viewing source I see things like `<div css="[object Object]">`.

I did some Googling and found a solution in some random emotion issue to add the following to the file when `css` is used:

```
/** @jsx jsx */ import { jsx } from '@emotion/core'
```

This fixes it, but since I have many dozens of files, I just thought I would double check I'm not doing something wrong here? Anyone else have this issue?

My .babelrc:

```
{
  "presets": [
    "next/babel",
    "@emotion/babel-preset-css-prop"
  ],
  "plugins": [
    "graphql-tag",
    "babel-plugin-macros"
  ]
}
```

[edit] I just noticed this warning when building:

```Conflict: Multiple assets emit different content to the same filename static/css/b1b273a9747f5859e84c.css```

Not sure what it's from... if someone has any pointers where to start debugging I would be grateful.

**Comment by ben-rogerson** [comment]
It seems like the css prop is being added in development but not in production but that doesn't explain the css conflict during build.

I'll need a reproducible test repo so I can investigate further.

**Comment by pix2D** [comment]
I will try to prepare one, it's a decently sized project so it may take a bit unfortunately. The annoying thing is that everything works fine with styled-components. I import css from twin.macro so the swap was quite simple in terms of code changes, but of course with a different result.

I tried to pull down the example just to confirm it works with the latest version of Next and I couldn't reproduce it there.

**Comment by ben-rogerson** [comment]
Check out this issue - they have mentioned some workarounds with Emotion + Next: https://github.com/emotion-js/emotion/issues/1237
