### ISSUE TITLE
Using custom CSS utilities with tw`` doesn't work

### ISSUE THREAD

**Issue by vharvala** [ben-rogerson/twin.macro#94]
I would like to define my own CSS classes using Tailwind utilities in my `tailwind.css` file e.g. like this: 

``` 
@tailwind base;
@tailwind components;
@tailwind utilities;

.py-responsive {
  @apply py-4
}

@screen tablet {
  .py-responsive {
    @apply py-6
  }
}
```

But this results to `py-responsive was not found` error if used like this:

```
import tw from 'twin.macro';
import { css } from 'emotion/css';

const styles = css`
    ${tw`py-responsive`}
`
``` 

Have anyone managed to do something like this?

My stack:
- Next.js 9.4.4
- Tailwindcss: 1.4.6
- Twin.macro: 1.4.1
- Emotion: 10.0.27

**Comment by ben-rogerson** [comment]
Twin as it doesn't use PostCss like Tailwind as it's in css-in-js territory.

You have a couple of options:

- Convert those utilities into a plugin and add it to your tailwind.config.js
- Add the styles to a variable which you could export and use around your app

**Comment by wildfrontend** [comment]
so if we custom tailwind.config 

we need to write tailwind className outside

like :

```js
const App = () =>{
       return <StyleComponent className="py-responsive" />
}
```

but  i think it will spread css design logic

have any good pattern?

**Comment by ben-rogerson** [comment]
[Take a look at this demo](https://codesandbox.io/embed/responsive-pattern-example-y6n2r?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.js&theme=dark) that shows you the preferred approach.

**Comment by vharvala** [comment]
@wildfrontend yeah that is how I use it currently and you described the problem perfectly. It does spread the css design logic. 

@ben-rogerson thanks for the clarification and options! Didn't think about the latter one so that might be the way to go. Thanks for the help 👍

**Comment by vharvala** [comment]
I will close this issue since it is not actually an issue.
