### ISSUE TITLE
Habilite Pulge 

### ISSUE THREAD

**Issue by Eriickson** [ben-rogerson/twin.macro#95]
(Reactjs + Emotion + Tailwindcss) Pulge takes into account the classes that are added to the styled components (twin.macro) since they do not inject the classes directly, but instead compile the styles of those classes and then unify them into one  only class????

**Comment by ben-rogerson** [comment]
Hey Eriickson, I'm not sure what "Habilite" or "Pulge" is and I don't quite understand this issue.
Could you please reword it?
