### ISSUE TITLE
richText config from Typography plugin not working

### ISSUE THREAD

**Issue by fvanwijk** [ben-rogerson/twin.macro#97]
I'm trying to configure the [typography](https://github.com/benface/tailwindcss-typography) plugin in Tailwind and use it through twin.macro. Accoring to the [plugin support](https://twin-docs.netlify.app/plugin-support) page this plugin is supported, but still I have some issues.

There are config keys for h1, h2, etc and they create utils that can be applied to style heading, for example:

```html
<div tw="h1">Heading 1</div>
```

This works fine.

There is also a `richText` key, so that you can style multiple vanilla HTML elements that are wrapped by a container that has `rich-text` applied, for example:

```html
<div class="rich-text">
  <h1>Heading 1</h1>
</div>
```

This works also fine, but note the `class` attribute (or `className="rich-text"` for that matter), however it does not apply styling to the `h1` when I do `<div tw="rich-text"><h1>Heading 1</h1></div>`.

However I see some styles being applied to the container itself.
![image](https://user-images.githubusercontent.com/963136/85723383-771e3d00-b6f3-11ea-87e3-ee59851cc50e.png)
These are not my styles, it looks like these are the plugin defaults (?).

This is my config:
```js
textStyles: theme => ({
  heading: {
    output: false,
    lineHeight: theme('lineHeight.snug'),
  },
  h1: { // creates .h1 { ... }
    extends: 'heading',
    fontWeight: theme('fontWeight.bold'),
    fontSize: theme('fontSize.5xl'),
  },
  // Additional config removed for brevity
  richText: {
    lineHeight: theme('lineHeight.loose'),
    '> * + *': {
      marginTop: '1em',
    },
    h1: { // creates .rich-text h1 { ... } ?
      extends: 'h1',
    },
    // Additional config removed for brevity
  },
})
```
```js
plugins: [require('tailwindcss-typography')({ componentPrefix: '' })]
```

I'm not sure whether I'm doing something wrong, twin.macro has a bug or tailwindcss-typography has a bug.

**Comment by ben-rogerson** [comment]
Thanks for raising this issue too, I'm pushing a fix in the next version due shortly.

**Comment by ben-rogerson** [comment]
Hey Frank, the fix for this is up in [v1.5.0](https://github.com/ben-rogerson/twin.macro/releases/tag/1.5.0) 🎉 

I've also made you a [rich-text demo in CRA →](https://codesandbox.io/embed/typography-plugin-rich-text-demo-6v8gz?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.js&theme=dark)

**Comment by fvanwijk** [comment]
Thanks for improving typography plugin support.

I bumped twin.macro to 1.5.0 and replaced `className` with `tw`.
Due to some nasty caching in CRA/Storybook it took some time for the proper rich-text styles to appear, but now everything is fine 😬.

On a side note, I cannot define `'b, strong'` and `'i, em'` because then I get error:
> twin.macro: Only a single selector is supported: ".rich-text i, .rich-text em"

So I have to define them separately.

**Comment by ben-rogerson** [comment]
Yeah, the caching can be pretty annoying, I'm hoping to reduce it in the coming versions.

I'd say there's still some caching because I removed that single selector error message in v1.5.0.
If you haven't tried already, try [making a change in the code to force a recompile](https://github.com/kentcdodds/babel-plugin-macros#babel-cache-problem).
