### ISSUE TITLE
How to add custom fonts using twin.macro?

### ISSUE THREAD

**Issue by theairbend3r** [ben-rogerson/twin.macro#98]
I want to replace the default "serif" and "sans" fonts in Tailwindcss with another font. How can go about doing that? I'm using Next.js if it helps. 

More specifically, where do I save the downloaded font and configure twin to use it?

**Comment by rbutera** [comment]
@theairbend3r please see [Tailwind's official documentation on customizing fonts](https://tailwindcss.com/docs/font-family)

**Comment by rodolphoasb** [comment]
@rbutera Hey, could you give further explanations on how to do this? I'm using twin.macro with styled components. Do I need to change something inside next.config.js? I added the font inside public/fonts but can't get this to work. Already read the Tailwind documentation...

**Comment by ben-rogerson** [comment]
I've used the next-fonts package to load fonts, perhaps take a look at that.

[next-fonts](https://www.npmjs.com/package/next-fonts) / [how to setup with styled-components](https://github.com/rohanray/next-fonts-example/tree/master/with-styled-comp)
