### ISSUE TITLE
Extended colour does not change on reload (Next.js)

### ISSUE THREAD

**Issue by theairbend3r** [ben-rogerson/twin.macro#99]
I'm trying to extend the theme. I want to add a new colour while using Next.js.
To install the libraries, I followed the instructions given in this repo. 

When I first set a colour in `tailwind.config.js`, it works. 
```
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        lol: "#ddad12",
      },
    },
  },
}
```  

I save the file and use it as follows. 

```
import "twin.macro"

const Main = () => {
  return <div tw="bg-lol p-1 h-full">Main</div>
}

export default Main
```

But when I change the colour in the `tailwind.config.js` as - 

```
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        lol: "#bb15bb",
      },
    },
  },
}
```

The changes do not happen on the page. I can still see the previous colour. I tried this out in the Codesandbox for Next.js and it happens there as well.

I even restarted the `npm run dev` but effects do not take effect.

**Comment by ben-rogerson** [comment]
This is fixed by making a change in your code to force a recompile - it's part of the caching in next.

I'm aiming to defeat this cache automatically in an upcoming patch 🤞

**Comment by trkaplan** [comment]
@ben-rogerson is this issue solved? I have nextjs + emotion + tailwndcss + twin.macro setup. 
After extending a tw class in tailwind.config.js, I have to restart the dev server to take effect. 

package.json
```json
{
  "name": "nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@emotion/react": "^11.1.4",
    "@emotion/styled": "^11.0.0",
    "next": "10.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "twin.macro": "^2.0.8"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@types/node": "^14.14.20",
    "@types/react": "^17.0.0",
    "postcss": "^8.2.4",
    "tailwindcss": "^2.0.2",
    "typescript": "^4.1.3"
  }
}
```

twin.d.ts
```typescript
// twin.d.ts
import "twin.macro";
import styledImport from "@emotion/styled";
import { css as cssImport } from "@emotion/react";

// The css prop
// https://emotion.sh/docs/typescript#css-prop
import {} from "@emotion/react/types/css-prop";

declare module "twin.macro" {
  // The styled and css imports
  const styled: typeof styledImport;
  const css: typeof cssImport;
}

// The 'as' prop on styled components
declare global {
  namespace JSX {
    interface IntrinsicAttributes<T> extends DOMAttributes<T> {
      as?: string;
    }
  }
}
```
.babelrc
```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-react": {
          "runtime": "automatic",
          "importSource": "@emotion/react"
        }
      }
    ]
  ],
  "plugins": ["@emotion/babel-plugin", "babel-plugin-macros"]
}
```

**Comment by ben-rogerson** [comment]
Yeah it's nothing to do with those files, it's about babel and it's ability to read a changed file when you start up your server. 
I can't find a way to tell babel to re-read tailwind.config.js on startup so it grabs from it's own cache instead. 
Best you can do at this stage is to adjust your dev script to delete the cache folder eg: `rimraf .next`.
